import React from 'react';
import {useQuery} from '@tanstack/react-query';
import {useAuth} from '@/lib/AuthContext';
import {base44} from '@/api/base44Client';
import useProject360 from '@/components/projects/useProject360';
import AlsightAttention from '@/components/AlsightAttention';
import {formatDate} from '@/lib/portal';
export default function ProjectAttention({project}) {
 const {user}=useAuth(),overview=useProject360(project),today=new Date().toLocaleDateString('en-CA');
 const actions=useQuery({queryKey:['project-attention-actions',project.id,user?.id,user?.role,today],queryFn:()=>base44.entities.ProjectAction.aggregate({query:{project_id:project.id,status:{$ne:'done'},due_date:{$lt:today,$nin:['',null]}},groupBy:'priority',limit:5})});
 const overdue=actions.data?.rows.reduce((sum,row)=>sum+row.count,0) || 0,critical=actions.data?.rows.some(row=>row.priority==='high' && row.count>0),delivery=overview.data?.delivery;
 const datePassed=delivery?.forecast_pc && delivery.forecast_pc.slice(0,10)<today && !delivery.pc_achieved;
 const pending=overview.data?.legalPending || 0;
 return <section className="space-y-3"><h2 className="text-sm font-semibold">What matters</h2>{(overview.isPending || actions.isPending) && <p role="status" className="text-xs text-muted-foreground">Checking project records…</p>}{(overview.error || actions.error) && <p role="alert" className="text-xs text-destructive">Some attention information is unavailable; no missing-record conclusion has been inferred. <button className="underline" onClick={()=>{overview.refetch();actions.refetch();}}>Retry</button></p>}{overdue>0 && <AlsightAttention title={`${overdue} overdue ${overdue===1 ? 'action' : 'actions'}`} severity={critical ? 'urgent' : 'attention'} explanation={critical ? 'At least one open high-priority action has a recorded due date in the past. Review its status, owner and due date within ALSight.' : 'Open actions have recorded due dates in the past. Review their current status, assignments and due dates within ALSight.'} actions={[{label:'Review actions',to:`/projects/${project.id}?tab=delivery`}]}/>} {datePassed && <AlsightAttention title="Forecast Practical Completion date has passed" explanation={`The recorded forecast is ${formatDate(delivery.forecast_pc)} and no PC-achieved date is recorded here. This is not a conclusion about the works or contractual delay.`} actions={[{label:'Review programme',to:`/projects/${project.id}?tab=delivery`}]}/>} {pending>0 && <AlsightAttention title={`${pending} recorded agreements await execution / PO evidence`} explanation="Applicable agreement records do not yet hold the execution or PO evidence used by ALSight. Review their recorded statuses; no legal conclusion is implied." actions={[{label:'Review documents',to:`/projects/${project.id}?tab=drafting`}]}/>} {!overdue && !datePassed && !pending && overview.isSuccess && actions.isSuccess && <p className="text-xs text-muted-foreground">No overdue-action, recorded-completion-date or agreement-evidence prompts currently require attention.</p>}</section>;
}