import React from 'react';
import {Link} from 'react-router-dom';
import {useInfiniteQuery} from '@tanstack/react-query';
import {base44} from '@/api/base44Client';
import {Button} from '@/components/ui/button';
import {formatDate} from '@/lib/portal';
export default function ProjectApprovalLinks({project,user}) {
  const query=useInfiniteQuery({queryKey:['project-command-approvals',project.id,user.id,user.role],initialPageParam:null,queryFn:({pageParam})=>base44.entities.DocumentApprovalRequest.filter({project_id:{$in:[project.id,project.dataverse_id].filter(Boolean)},status:'pending',source_requires_approval:true},{sort:'requested_at',limit:25,...(pageParam ? {cursor:pageParam} : {})}),getNextPageParam:page=>page.has_more ? page.next_cursor : undefined});
  return <section className="space-y-4 rounded-xl border border-border bg-card p-5"><h2 className="text-xl font-semibold">Pending project approvals</h2><p className="text-sm text-muted-foreground">Only approval records you are permitted to view are shown. Decisions remain in the existing Approval Centre.</p>{query.isPending ? <p role="status">Loading approvals…</p> : query.error ? <p role="alert" className="text-destructive">Unable to load approvals. <button className="underline" onClick={()=>query.refetch()}>Retry</button></p> : !query.data?.pages[0].items.length ? <p className="text-sm text-muted-foreground">No accessible pending approvals recorded for this project.</p> : <ul className="divide-y divide-border">{query.data.pages.flatMap(page=>page.items).map(item=><li key={item.id}><Link to={`/approvals?approval=${encodeURIComponent(item.id)}`} className="block py-4 hover:text-primary"><strong className="text-sm">{item.document_title}</strong><span className="mt-1 block text-xs text-muted-foreground">Requested {formatDate(item.requested_at)} · Review approval</span></Link></li>)}</ul>}{query.hasNextPage && <Button variant="outline" disabled={query.isFetchingNextPage} onClick={()=>query.fetchNextPage()}>Load more approvals</Button>}</section>;
}