import React, { useState } from 'react';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import FinanceMappingRow from '@/components/finance/FinanceMappingRow';
import { financeCall } from '@/components/finance/financeClient';
export default function FinanceMappingAdmin(){
 const client=useQueryClient(),[status,setStatus]=useState('review'),[cursor,setCursor]=useState(null),[after,setAfter]=useState(null),[scanStarted,setScanStarted]=useState(false),[scanDone,setScanDone]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const s=useQuery({queryKey:['finance-status'],queryFn:()=>financeCall({action:'status'})});
 const q=useQuery({queryKey:['finance-mappings',status,cursor],queryFn:()=>financeCall({action:'mappings',status,cursor}),enabled:Boolean(s.data?.confirmed)});
 async function discover(){setBusy(true);setError('');try{const d=await financeCall({action:'list',after});setAfter(d.next);setScanStarted(true);setScanDone(!d.has_more);setNotice(`${d.items.length} source project groups checked${d.has_more?'. Continue discovery to check the next page.':'. All remaining source project groups have been checked.'}`);await client.invalidateQueries({queryKey:['finance-mappings']});}catch(e){setError(e.message);}finally{setBusy(false);}}
 const saved=()=>{client.invalidateQueries({queryKey:['finance-mappings']});client.invalidateQueries({queryKey:['finance']});};
 return <section className="space-y-4 rounded-panel border border-border bg-card p-6"><div><h2 className="font-heading text-xl font-semibold">Project matching & reconciliation</h2><p className="mt-2 text-sm text-muted-foreground">Unique project-name matches are linked automatically. Ambiguous and unmatched names require an administrator. Saved links override later automatic matching, including different codes below PROJ600; original codes are never changed.</p></div><div className="flex flex-wrap items-center gap-3"><Button disabled={busy||!s.data?.confirmed} onClick={()=>{if(scanDone){setAfter(null);setScanDone(false);setScanStarted(false);}else discover();}}>{busy?'Discovering…':scanDone?'Restart discovery':scanStarted?'Discover next source projects':'Discover source projects'}</Button><select aria-label="Mapping status" className="rounded-md border border-input bg-card p-2 text-sm" value={status} onChange={e=>{setStatus(e.target.value);setCursor(null);}}><option value="review">Needs review</option><option value="linked">Linked projects</option><option value="all">All discovered projects</option></select></div>{!s.data?.confirmed&&<p className="text-sm text-muted-foreground">Confirm the reporting connection to discover and link source projects.</p>}{notice&&<p role="status" className="text-sm text-success">{notice}</p>}{error&&<p role="alert" className="text-destructive">{error}</p>}{q.isFetching&&<p role="status">Loading mappings…</p>}{q.error&&<p role="alert" className="text-destructive">{q.error.message}</p>}{q.data?.items.map(m=><FinanceMappingRow key={m.source_key} mapping={m} onSaved={saved}/>)}{q.data&&!q.data.items.length&&<p className="text-sm text-muted-foreground">No discovered projects in this category. Discovery checks one page at a time; undiscovered projects are not considered reconciled.</p>}<div className="flex gap-2">{cursor&&<Button variant="outline" onClick={()=>setCursor(null)}>First page</Button>}{q.data?.has_more&&<Button variant="outline" onClick={()=>setCursor(q.data.next_cursor)}>Next mappings</Button>}</div></section>;
}