import React,{useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {formatCurrency} from '@/lib/portal';
import {financeCall} from '@/components/finance/financeClient';
const money=v=>v==null?'Not available':formatCurrency(v);
import useCommercialScope from '@/components/finance/useCommercialScope';
export default function FinanceDataverseDetail({recordId,onClose,projectId}){
 const scope=useCommercialScope();
 const [cursor,setCursor]=useState(null),q=useQuery({queryKey:['finance','dataverse-detail',scope,recordId,cursor,projectId||null],queryFn:()=>financeCall({action:projectId?'projectOrderDetail':'dvDetail',recordId,cursor,...(projectId?{projectId}:{})}),staleTime:60000}),d=q.data,r=d?.record;
 const net=d?.totals.find(t=>t.has_amount),missing=d?.totals.find(t=>!t.has_amount)?.count||0;
 return <section className="space-y-3 rounded-panel border border-border bg-muted p-4"><div className="flex justify-between gap-4"><h3 className="font-semibold">Transaction detail</h3><Button variant="ghost" onClick={onClose}>Close detail</Button></div>{q.isPending&&<p role="status">Reading synced detail…</p>}{q.error&&<p className="text-destructive" role="alert">{q.error.message}</p>}{r&&<><dl className="grid gap-3 text-sm sm:grid-cols-3">{[['Reference',r.reference],['Net value',money(r.amount)],['VAT',money(r.vat)],['Gross value',money(r.gross)],['Supplier',d.supplier?.name||'Not linked / unavailable'],['Customer',d.customer?.name||'Not linked / unavailable'],['Approval',r.approval||'Not recorded'],['Source table',r.source_table],['Approved',r.approved?'Yes':'No'],['Sent',r.sent?'Yes':'No'],['Line-item net',net?money(net.sum_amount):'No valued line items']].filter(([label])=>r.kind!=='line_items'||!['Supplier','Customer','Approval','Approved','Sent','Line-item net'].includes(label)).map(([label,value])=><div key={label}><dt className="text-muted-foreground">{label}</dt><dd>{value}</dd></div>)}</dl><p className="text-xs text-muted-foreground">Source last modified: {r.source_modified_at?new Date(r.source_modified_at).toLocaleString('en-GB'):'Not supplied'}. Synced: {new Date(r.synced_at).toLocaleString('en-GB')}.</p>{missing>0&&<p className="text-sm text-destructive">{missing} line items have missing net values.</p>}{!missing&&net&&r.amount!=null&&Math.abs(net.sum_amount-r.amount)>0.01&&<p className="text-sm text-destructive">PO header and line-item net totals differ; review is required.</p>}{r.kind==='invoices'&&!r.has_amount&&<p className="text-sm text-destructive">This invoice has no mapped or recorded net value in the completed snapshot.</p>}{r.kind==='line_items'&&<p className="text-sm text-muted-foreground">PO lookup: {r.parent_id||'Missing'}. {r.description}</p>}{d.lines.items.length>0&&<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Line item','Net','VAT','Gross'].map(v=><th key={v} className="p-2">{v}</th>)}</tr></thead><tbody>{d.lines.items.map(l=><tr className="border-t border-border" key={l.id}><td className="p-2">{l.description||l.name}</td><td className="p-2">{money(l.amount)}</td><td className="p-2">{money(l.vat)}</td><td className="p-2">{money(l.gross)}</td></tr>)}</tbody></table></div>}{d.lines.has_more&&<Button variant="outline" onClick={()=>setCursor(d.lines.next_cursor)}>Next line items</Button>}{cursor&&<Button variant="outline" onClick={()=>setCursor(null)}>First line items</Button>}</>}</section>;
}