import React,{useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {financeCall} from '@/components/finance/financeClient';
import FinanceDataverseTableMapping from '@/components/finance/FinanceDataverseTableMapping.jsx';
import FinanceDataverseSyncPanel from '@/components/finance/FinanceDataverseSyncPanel';
export default function FinanceDataverseMappings(){
 const client=useQueryClient(),[candidates,setCandidates]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const q=useQuery({queryKey:['finance-dataverse-field-mappings'],queryFn:()=>financeCall({action:'dvMappingStatus'})});
 async function discover(){setBusy(true);setError('');try{const result=await financeCall({action:'dvDiscover'});setCandidates(result.tables);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="space-y-5"><section className="space-y-4 rounded-panel border border-border bg-card p-5"><header><h2 className="font-heading text-xl font-semibold">Finance Dataverse tables & field mappings</h2><p className="mt-1 text-sm text-muted-foreground">Finance projects, suppliers, customers, purchase orders, PO line items and sales invoices have their own snapshot mappings. Inspect each table, select its fields and verify your changes before starting a new finance sync below.</p></header>{q.isPending&&<p role="status" className="text-sm">Loading finance mappings…</p>}{q.error&&<p role="alert" className="text-sm text-destructive">{q.error.message}</p>}{q.data&&!q.data.configured&&<p className="text-sm text-muted-foreground">Confirm the shared Dataverse read account before inspecting or saving finance mappings.</p>}<div className="flex gap-2"><Button variant="outline" disabled={busy||!q.data?.configured} onClick={discover}>{busy?'Discovering finance tables…':'Discover finance tables'}</Button><Button variant="outline" disabled={q.isFetching} onClick={()=>q.refetch()}>Reload mappings</Button></div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{q.data?.tables.map(table=><FinanceDataverseTableMapping key={`${table.key}:${table.verified_at||'default'}`} table={table} candidates={candidates} onSaved={()=>client.invalidateQueries({queryKey:['finance-dataverse-field-mappings']})}/>)}<p className="text-xs text-muted-foreground">Saved mappings apply to the next finance sync, not an import already running. Financial figures remain unavailable where no amount field is mapped. No source records are edited.</p></section><FinanceDataverseSyncPanel/></div>;
}