import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { formatCurrency,formatDate } from '@/lib/portal';
import { financeCall } from '@/components/finance/financeClient';
const money=v=>v==null?'Not recorded':formatCurrency(v);
export default function FinancePODetail({poId,onClose}){
 const [cursor,setCursor]=useState(null),q=useQuery({queryKey:['finance-po',poId,cursor],queryFn:()=>financeCall({action:'poDetail',poId,cursor}),staleTime:60000}),p=q.data?.po;
 return <section className="space-y-3 rounded-panel border border-border bg-muted p-4"><div className="flex justify-between gap-4"><h3 className="font-heading text-lg font-semibold">{p?.po_number||'Purchase-order detail'}</h3><Button variant="ghost" onClick={onClose}>Close PO</Button></div>{q.isPending&&<p role="status">Reading purchase order…</p>}{q.error&&<p role="alert" className="text-destructive">{q.error.message}</p>}{p&&<><p className="text-xs text-muted-foreground">{q.data.source} Last saved: {new Date(p.updated_date).toLocaleString('en-GB')}.</p><dl className="grid gap-3 text-sm sm:grid-cols-2 xl:grid-cols-4">{[['Original project reference',p.project_ref||'Not supplied'],['PO net value',money(p.total_net_value)],['Available line-item net total',q.data.total?.count?money(q.data.total.sum_net_value):'No line items'],['Approval',p.approval_status||'Not supplied'],['Approved',p.approved?'Yes':'No'],['Sent',p.sent?'Yes':'No'],['Approval date',p.approval_date?formatDate(p.approval_date):'Not supplied'],['Sent date',p.sent_date?formatDate(p.sent_date):'Not supplied']].map(([label,value])=><div key={label}><dt className="text-muted-foreground">{label}</dt><dd>{value}</dd></div>)}</dl>{p.notes&&<p className="whitespace-pre-wrap text-sm">{p.notes}</p>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Line item','Net','VAT','Gross','RIBA stage'].map(v=><th key={v} className="p-2">{v}</th>)}</tr></thead><tbody>{q.data.lines.items.map(r=><tr key={r.id} className="border-t border-border"><td className="p-2">{r.description||r.name}</td><td className="p-2">{money(r.net_value)}</td><td className="p-2">{money(r.vat_value)}</td><td className="p-2">{money(r.gross_value)}</td><td className="p-2">{r.riba_stage||'Not supplied'}</td></tr>)}</tbody></table></div>{!q.data.lines.items.length&&<p className="text-sm text-muted-foreground">No synced line items available.</p>}<div className="flex gap-2">{cursor&&<Button variant="outline" onClick={()=>setCursor(null)}>First line items</Button>}{q.data.lines.has_more&&<Button variant="outline" onClick={()=>setCursor(q.data.lines.next_cursor)}>Next line items</Button>}</div></>}</section>;
}