import React, {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {financeCall} from '@/components/finance/financeClient';
export default function FinanceDataverseSyncPanel(){
 const client=useQueryClient(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const q=useQuery({queryKey:['finance-status'],queryFn:()=>financeCall({action:'status'}),refetchInterval:query=>query.state.data?.sync?.status==='running'?5000:false}),s=q.data?.sync;
 async function start(){setBusy(true);setError('');try{await financeCall({action:'dvStart'});await client.invalidateQueries({queryKey:['finance-status']});await client.invalidateQueries({queryKey:['finance']});await client.invalidateQueries({queryKey:['finance-mappings']});}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="space-y-4 rounded-panel border border-border bg-card p-6"><h2 className="font-heading text-xl font-semibold">Dataverse finance sync</h2><p className="text-sm text-muted-foreground">Sync finance projects, both supplier directories, customers, purchase orders, PO line items and sales-invoice headers. Project names are matched to ALSight projects without changing legacy codes. A new snapshot is published only after every table finishes.</p><Button disabled={busy||s?.status==='running'} onClick={start}>{busy?'Checking table access…':s?.status==='running'?'Syncing finance tables…':'Sync Dataverse finance tables'}</Button>{q.isPending&&<p role="status">Checking sync status…</p>}{(error||q.error||s?.error)&&<p role="alert" className="text-destructive">{error||q.error?.message||s.error}</p>}{s&&<><p className="text-sm">Status: {s.status}{s.last_completed_at?` · Last completed ${new Date(s.last_completed_at).toLocaleString('en-GB')}`:''}</p><div className="grid gap-2 text-sm md:grid-cols-2">{s.tables?.list?.map(t=><div key={t.logical} className="rounded-md bg-muted p-3"><p className="font-medium">{t.logical}</p><p className="text-muted-foreground">{t.processed} records · {t.complete?'Complete':'Pending / syncing'}</p></div>)}</div></>}<p className="text-sm text-muted-foreground">Invoice amounts are available only when a compatible amount field is mapped and synchronised. Unmapped monetary values remain unavailable. No sales-order source is configured. Existing completed figures remain visible while syncing.</p></section>;
}