import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {formatCurrency} from '@/lib/portal';
import FinanceDataverseDetail from '@/components/finance/FinanceDataverseDetail';
import {financeCall} from '@/components/finance/financeClient';
import FinanceNameMatchFlag from '@/components/finance/FinanceNameMatchFlag.jsx';
export default function FinanceDataverseTransactions({row}){
 const [kind,setKind]=useState('orders'),[after,setAfter]=useState(null),[selected,setSelected]=useState(null);
 const q=useQuery({queryKey:['finance-orders',row.source_key,kind,after],queryFn:()=>financeCall({action:kind,type:'PO',sourceKey:row.source_key,after}),staleTime:60000});
 return <div className="space-y-4"><p className="text-sm text-muted-foreground">Original finance reference: {row.Code}. Net values exclude VAT. Missing values are shown as unavailable, not zero.</p>{row.mapping.project_id?<Link to={`/projects/${row.mapping.project_id}`} className="text-primary underline">Linked project: {row.mapping.project_name} · {row.mapping.project_code}</Link>:<p className="text-sm text-destructive">Project mapping needs administrator review; original references have not been changed.</p>}<FinanceNameMatchFlag mapping={row.mapping}/><div className="flex gap-2">{[['orders','Purchase orders'],['invoices','Sales invoices']].map(([v,label])=><Button variant={kind===v?'default':'outline'} key={v} onClick={()=>{setKind(v);setAfter(null);setSelected(null);}}>{label}</Button>)}</div>{q.isPending&&<p role="status">Reading Dataverse snapshot transactions…</p>}{q.error&&<p className="text-destructive" role="alert">{q.error.message}</p>}{q.data&&<><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-muted"><tr>{['Reference','Net value','Approval',''].map((v,i)=><th className="p-3" key={i}>{v}</th>)}</tr></thead><tbody>{q.data.items.map(r=><tr key={r.id} className="border-b border-border"><td className="p-3">{r.reference}</td><td className="p-3">{r.has_amount?formatCurrency(r.amount):'Value not available'}</td><td className="p-3">{r.approval||'Not recorded'}</td><td className="p-3"><Button variant="outline" onClick={()=>setSelected(r.id)}>View detail</Button></td></tr>)}</tbody></table></div>{!q.data.items.length&&<p className="text-muted-foreground">No active transactions found for this finance project.</p>}<div className="flex gap-2">{after&&<Button variant="outline" onClick={()=>setAfter(null)}>First transactions</Button>}{q.data.has_more&&<Button variant="outline" onClick={()=>setAfter(q.data.next_cursor)}>Next transactions</Button>}</div></>}{selected&&<FinanceDataverseDetail key={selected} recordId={selected} onClose={()=>setSelected(null)}/>}</div>;
}