import React, {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {financeCall} from '@/components/finance/financeClient';
import FinanceDataverseMappingFields from '@/components/finance/FinanceDataverseMappingFields.jsx';
export default function FinanceDataverseTableMapping({table,candidates,onSaved}){
 const [logical,setLogical]=useState(table.logical),[fields,setFields]=useState(table.fields),[metadata,setMetadata]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const dirty=logical!==table.logical||JSON.stringify(fields)!==JSON.stringify(table.fields);
 async function inspect(){setBusy(true);setError('');setNotice('');try{const data=await financeCall({action:'dvInspect',logical});setMetadata(data);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');setNotice('');try{const result=await financeCall({action:'dvSaveMapping',key:table.key,logical,fields});await onSaved();setNotice(result.notice);}catch(e){setError(e.message);}finally{setBusy(false);}}
 function changeTable(value){setLogical(value);setMetadata(null);setNotice('');if(value!==logical)setFields(Object.fromEntries(table.definitions.map(d=>[d.key,''])));}
 return <details className="rounded-md border border-border bg-card p-4"><summary className="cursor-pointer font-heading font-semibold">{table.label} <span className="ml-2 text-xs font-normal text-muted-foreground">{table.logical} · {table.configured?'Saved mapping':'Default mapping'}</span></summary><div className="mt-4 space-y-4"><p className="text-xs text-muted-foreground">Finance-only snapshot mapping. This does not change the existing project, account or document synchronisation.</p><div className="flex flex-wrap items-center gap-2"><Input className="max-w-sm" aria-label={`${table.label} table logical name`} value={logical} disabled={busy} maxLength={100} onChange={e=>changeTable(e.target.value)} placeholder="Dataverse table logical name"/>{candidates.length>0&&<select className="max-w-sm rounded-md border border-input bg-card p-2 text-sm" aria-label={`Discovered ${table.label} table`} disabled={busy} value={candidates.some(t=>t.logical===logical)?logical:''} onChange={e=>e.target.value&&changeTable(e.target.value)}><option value="">Choose discovered table</option>{candidates.map(t=><option key={t.logical} value={t.logical}>{t.label} · {t.logical}</option>)}</select>}<Button variant="outline" disabled={busy||!logical} onClick={inspect}>Inspect fields</Button></div>{metadata&&<><FinanceDataverseMappingFields definitions={table.definitions} metadata={metadata} fields={fields} disabled={busy} onChange={(key,value)=>{setFields(f=>({...f,[key]:value}));setNotice('');}}/><Button disabled={busy||metadata.logical!==logical||(!dirty&&table.configured)} onClick={save}>Verify & save mapping</Button></>}{!metadata&&<p className="text-xs text-muted-foreground">Inspect this table to view and remap its fields, including monetary values where available.</p>}{table.verified_at&&<p className="text-xs text-muted-foreground">Last verified: {new Date(table.verified_at).toLocaleString('en-GB')}</p>}{busy&&<p role="status" className="text-sm text-muted-foreground">Checking Dataverse fields…</p>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{notice&&<p role="status" className="text-sm text-success">{notice}</p>}</div></details>;
}