import React, { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { financeCall } from '@/components/finance/financeClient';
import FinanceForecastMonths from '@/components/finance/FinanceForecastMonths.jsx';
import FinanceForecastProjects from '@/components/finance/FinanceForecastProjects.jsx';
import FinanceForecastChart from '@/components/finance/FinanceForecastChart';
export default function FinanceForecast(){
 const [text,setText]=useState(''),[filters,setFilters]=useState({search:'',horizon:12,windowOffset:0,offset:0,month:null,excluded:false});
 useEffect(()=>{const timer=setTimeout(()=>setFilters(f=>({...f,search:text,offset:0})),350);return()=>clearTimeout(timer);},[text]);
 const q=useQuery({queryKey:['finance','forecast',filters],queryFn:()=>financeCall({action:'forecast',...filters}),staleTime:60000});
 const period=(change)=>setFilters(f=>({...f,...change,month:null,offset:0}));
 return <section className="finance-card finance-section finance-delay-3 space-y-4">
  <div><h2 className="font-heading text-lg font-semibold">Monthly invoice & PO forecast <span className="ml-2 rounded-md bg-primary/15 px-2 py-1 text-xs text-foreground">Estimates only</span></h2><p className="mt-2 text-sm text-muted-foreground">All valued projects, spread evenly across remaining calendar months from today through the recorded programme end. Submitted fee proposals take precedence over estimates. All amounts exclude VAT.</p><p className="mt-1 text-xs text-muted-foreground">Invoices use client value; POs use supplier cost budgets less recorded commitments. These are separate income and cost views, not an additive split. Missing invoice amounts leave a clearly labelled full-value planning baseline. Missing cost budgets are unavailable, not zero. No actual invoices or POs are created.</p></div>
  <div className="finance-controls"><Input className="max-w-sm" value={text} maxLength={120} onChange={e=>setText(e.target.value)} placeholder="Search valued projects…" aria-label="Search forecast projects"/><label className="text-sm">Period <select className="ml-2 rounded-md border border-input bg-card px-3 py-2" value={filters.horizon} onChange={e=>period({horizon:Number(e.target.value),windowOffset:0})}><option value={6}>6 months</option><option value={12}>12 months</option><option value={24}>24 months</option></select></label><Button variant="outline" disabled={q.isFetching||filters.windowOffset===0} onClick={()=>period({windowOffset:Math.max(0,filters.windowOffset-filters.horizon)})}>Earlier months</Button><Button variant="outline" disabled={q.isFetching||!q.data?.has_later||filters.windowOffset+filters.horizon>1200} onClick={()=>period({windowOffset:filters.windowOffset+filters.horizon})}>Later months</Button><Button variant="outline" disabled={q.isFetching} onClick={()=>q.refetch()}>Refresh forecast</Button></div>
  {q.isFetching&&<p role="status" className="text-sm text-muted-foreground">Calculating project forecasts…</p>}{q.error&&<p role="alert" className="text-sm text-destructive">{q.error.message}</p>}
  {q.data&&<><p className="text-xs text-muted-foreground">As of {q.data.today} (UK date) · {q.data.eligible} projects scheduled · {q.data.excluded} excluded without a usable future programme or positive value. {q.data.snapshot_at?'Deductions use the last completed Dataverse snapshot.':'No completed Dataverse snapshot: figures are budget baselines without verified deductions.'}</p><FinanceForecastChart rows={q.data.monthly} selected={q.data.month}/><FinanceForecastMonths rows={q.data.monthly} selected={q.data.month} onSelect={month=>setFilters(f=>({...f,month,offset:0,excluded:false}))}/><div className="flex gap-2"><Button data-variant={!filters.excluded?'selected':undefined} variant={filters.excluded?'outline':'secondary'} disabled={q.isFetching} onClick={()=>setFilters(f=>({...f,excluded:false,offset:0}))}>Monthly contributions</Button><Button data-variant={filters.excluded?'selected':undefined} variant={filters.excluded?'secondary':'outline'} disabled={q.isFetching} onClick={()=>setFilters(f=>({...f,excluded:true,offset:0}))}>Excluded projects ({q.data.excluded})</Button></div><FinanceForecastProjects data={q.data} excluded={filters.excluded}/><div className="flex items-center gap-3"><Button variant="outline" disabled={q.isFetching||filters.offset===0} onClick={()=>setFilters(f=>({...f,offset:Math.max(0,f.offset-25)}))}>Previous projects</Button><span className="text-xs text-muted-foreground">{q.data.total>0?`${filters.offset+1}–${Math.min(filters.offset+25,q.data.total)} of ${q.data.total}`:'0 projects'}</span><Button variant="outline" disabled={q.isFetching||!q.data.has_more} onClick={()=>setFilters(f=>({...f,offset:f.offset+25}))}>Next projects</Button></div></>}
 </section>;
}