import React,{useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import powerBIConnectionCall from '@/components/finance/powerBIConnectionClient';
export default function PowerBIUserConnection(){
 const client=useQueryClient(),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reportURL,setReportURL]=useState('');
 const q=useQuery({queryKey:['powerbi-user-connection'],queryFn:()=>powerBIConnectionCall('status')});
 async function run(action){setBusy(action);setError('');setNotice('');try{const result=await powerBIConnectionCall(action,action==='check'?{reportURL}:{});if(action==='begin'){window.location.assign(result.authorization_url);return;}setNotice(result.notice||'Power BI connection removed.');await client.invalidateQueries({queryKey:['powerbi-user-connection']});}catch(e){setError(e.message);}finally{setBusy('');}}
 return <section className="space-y-4 rounded-panel border border-border bg-card p-6"><div><h2 className="font-heading text-xl font-semibold">Power BI Microsoft sign-in</h2><p className="mt-2 text-sm text-muted-foreground">Select Jake Savage’s Microsoft account to authorise read-only Power BI access for finance reporting. His password is entered only on Microsoft’s sign-in page. This does not replace the existing Dataverse finance source.</p></div>
 <div className="space-y-2 text-sm text-muted-foreground"><p>IT must register this Web return address on the Power BI application:</p><code className="block break-all text-foreground">https://alsight.base44.app/powerbi-callback</code><p>Delegated permissions: Report.Read.All and Dataset.Read.All. Jake also needs report access and Read/Build permission on its semantic model.</p></div>
 {q.isPending?<p role="status">Loading Power BI connection…</p>:q.error?<p role="alert" className="text-destructive">{q.error.message}</p>:<><p className="text-sm">{q.data.connected?`Microsoft sign-in connected${q.data.account_name?` as ${q.data.account_name}`:''}.`:'Not connected.'}</p><div className="flex flex-wrap gap-3"><Button disabled={Boolean(busy)} onClick={()=>run('begin')}>{busy==='begin'?'Opening Microsoft…':q.data.connected?'Reconnect with Microsoft':'Sign in with Microsoft'}</Button>{q.data.connected&&<Button variant="outline" disabled={Boolean(busy)} onClick={()=>run('disconnect')}>{busy==='disconnect'?'Disconnecting…':'Disconnect'}</Button>}</div>
 {q.data.connected&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();run('check');}}><label htmlFor="powerbi-access-report" className="block text-sm font-medium">Report link to check</label><Input id="powerbi-access-report" type="url" required value={reportURL} onChange={e=>setReportURL(e.target.value)} placeholder="Paste the Power BI workspace report link"/><Button variant="outline" disabled={Boolean(busy)}>{busy==='check'?'Checking report and model…':'Check report access'}</Button>{q.data.last_checked_at&&<p className="text-sm text-muted-foreground">Last successful check: {new Date(q.data.last_checked_at).toLocaleString('en-GB')}</p>}</form>}</>}
 {error&&<p role="alert" className="text-destructive">{error}</p>}{notice&&<p role="status" className="text-success">{notice}</p>}</section>;
}