import React,{useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {meetingWriter} from '@/components/projects/workspace/meetingSessionActivity';
import MeetingSessionHistory from '@/components/projects/workspace/MeetingSessionHistory';
import MeetingSessionSummary from '@/components/projects/workspace/MeetingSessionSummary';
import MeetingFollowUpPicker from '@/components/projects/workspace/MeetingFollowUpPicker';
import MeetingFollowUpActions from '@/components/projects/workspace/MeetingFollowUpActions';
import MeetingOperationContext from '@/components/projects/workspace/MeetingOperationContext';
import MeetingPeopleEditor from '@/components/projects/workspace/MeetingPeopleEditor';
import MeetingPeopleSummary from '@/components/projects/workspace/MeetingPeopleSummary';
export default function MeetingSessionControls({manager,user,total,project,index,projects,onSelect}) {
 const [name,setName]=useState('Regional Review'),[history,setHistory]=useState(false),[summary,setSummary]=useState(null),[followUp,setFollowUp]=useState(false),[followUpSession,setFollowUpSession]=useState(null),[people,setPeople]=useState(false);
 const {session,active,busy,error,counts}=manager;
 const end=async()=>{const row=await manager.end();if(row){setSummary(session);manager.clear();}};
 return <section className="space-y-3 rounded-xl border border-border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">{session?.subject || 'Meeting sessions'}</h2>{session && <p className="mt-1 text-xs text-muted-foreground">{counts.reviewed} reviewed · {total ?? '…'} currently filtered projects · {counts.actions} actions created · {counts.completed} completed · {counts.notes} notes saved{manager.ended ? ' · Ended' : ''}</p>}</div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>{setFollowUpSession(null);setFollowUp(true);}}>Follow up actions</Button><Button size="sm" variant="outline" onClick={()=>setHistory(true)}>Meeting history</Button>{session && <Button size="sm" variant="outline" onClick={()=>setSummary(session)}>View summary</Button>}{active && <Button size="sm" variant="outline" disabled={busy || manager.operations>0} onClick={()=>setPeople(true)}>Hosts and attendees</Button>}{active && <Button size="sm" disabled={busy || manager.operations>0 || manager.pendingRecords.length>0 || manager.marks.isFetching} onClick={end}>{busy ? 'Saving…' : 'End meeting'}</Button>}{session && !busy && !manager.operations && !manager.pendingRecords.length && <Button size="sm" variant="ghost" onClick={manager.clear}>{manager.ended ? 'New meeting' : 'Leave for later'}</Button>}</div></div>
 {session && <MeetingPeopleSummary session={session}/>}
 {manager.pendingRecords.length>0 && <p role="alert" className="text-sm text-destructive">Some saved actions still need their meeting records saved before this meeting can end. <Button size="sm" variant="outline" disabled={busy} onClick={manager.retryRecords}>Retry meeting records</Button></p>}
 {!session && !manager.current.isFetching && meetingWriter(user) && <form onSubmit={async e=>{e.preventDefault();await manager.start(name);}} className="flex flex-wrap items-end gap-2"><label className="min-w-48 flex-1 text-xs">Meeting name<Input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><Button size="sm" disabled={busy || !name.trim()}>{busy ? 'Starting…' : 'Start meeting'}</Button></form>}
 {!meetingWriter(user) && <p className="text-sm text-muted-foreground">Your role can view accessible meeting history but cannot host a meeting.</p>}
 {(manager.current.isFetching || (session && manager.query.isPending)) && <p role="status" className="text-sm text-muted-foreground">Loading saved meeting…</p>}
 {(error || manager.current.error || manager.query.error) && <p role="alert" className="text-sm text-destructive">{error || manager.current.error?.message || manager.query.error?.message} {(manager.current.error || manager.query.error) && <button className="underline" onClick={()=>{if(manager.current.error)manager.current.refetch();if(session)manager.query.refetch();}}>Retry loading</button>}</p>}
 {active && <div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={index<=0} onClick={()=>onSelect(projects[index-1])}>Previous Project</Button><Button size="sm" disabled={!project || busy || manager.marks.isPending || !!manager.marks.error || manager.reviewed.includes(project.id)} onClick={()=>manager.reviewedProject(project)}>{project && manager.reviewed.includes(project.id) ? 'Reviewed' : 'Mark Reviewed'}</Button><Button size="sm" variant="outline" disabled={index<0 || index>=projects.length-1} onClick={()=>onSelect(projects[index+1])}>Next Project</Button></div>}
 {manager.marks.error && <p role="alert" className="text-sm text-destructive">Review markers unavailable. <button className="underline" onClick={()=>manager.marks.refetch()}>Retry</button></p>}
 <Dialog open={history} onOpenChange={setHistory}><DialogContent className="max-h-[85dvh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>Meeting history</DialogTitle><DialogDescription>Open a saved summary or resume a meeting, including one previously ended.</DialogDescription></DialogHeader><MeetingSessionHistory user={user} activeId={!manager.ended ? session?.id : null} busy={busy || manager.operations>0} error={error} onResume={async s=>{const resumed=await manager.continueMeeting(s);if(resumed)setHistory(false);}}/></DialogContent></Dialog>
 <Dialog open={!!summary} onOpenChange={open=>{if(!open)setSummary(null);}}><DialogContent className="max-h-[85dvh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{summary?.subject || 'Meeting summary'}</DialogTitle><DialogDescription>Saved meeting activity and review outcomes.</DialogDescription></DialogHeader>{summary && <MeetingSessionSummary session={summary} user={user} busy={busy || manager.operations>0} error={error} onResume={async s=>{const resumed=await manager.continueMeeting(s);if(resumed)setSummary(null);}}/>}</DialogContent></Dialog>
 <Dialog open={followUp} onOpenChange={setFollowUp}><DialogContent className="max-h-[85dvh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>Follow up actions</DialogTitle><DialogDescription>Review outstanding actions from previous meetings, add notes or mark them complete.</DialogDescription></DialogHeader>{followUpSession ? <MeetingOperationContext.Provider value={manager.operationContext}><Button size="sm" variant="outline" onClick={()=>setFollowUpSession(null)}>Back to meetings</Button><MeetingFollowUpActions key={followUpSession.id} session={followUpSession} user={user} manager={manager}/></MeetingOperationContext.Provider> : <MeetingFollowUpPicker user={user} currentSession={session} onSelect={setFollowUpSession}/>}</DialogContent></Dialog>
 <Dialog open={people} onOpenChange={open=>{if(!manager.operations)setPeople(open);}}><DialogContent className="max-h-[85dvh] max-w-xl overflow-y-auto"><DialogHeader><DialogTitle>Meeting hosts and attendees</DialogTitle><DialogDescription>Choose registered ALSight staff for this meeting.</DialogDescription></DialogHeader>{session && <MeetingOperationContext.Provider value={manager.operationContext}><MeetingPeopleEditor key={session.id} session={session} onSaved={s=>{manager.resume(s);manager.refresh();setPeople(false);}}/></MeetingOperationContext.Provider>}</DialogContent></Dialog>
 </section>;
}