import React,{useState,useContext} from 'react';
import MeetingOperationContext from '@/components/projects/workspace/MeetingOperationContext';
import {base44} from '@/api/base44Client';
import {Button} from '@/components/ui/button';
import MeetingPersonPicker from '@/components/projects/workspace/MeetingPersonPicker';
export default function MeetingPeopleEditor({session,onSaved}) {
 const operation=useContext(MeetingOperationContext);
 const [hosts,setHosts]=useState(session.meeting_hosts || [{id:session.owner_id,name:session.author_name || 'Original organiser'}]),[attendees,setAttendees]=useState(session.meeting_attendees || []),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const add=(setter,person)=>setter(items=>items.some(item=>item.id===person.id) ? items : [...items,person]);
 const save=async e=>{e.preventDefault();setBusy(true);setError('');operation.begin();try{const {data}=await base44.functions.invoke('manageMeetingPeople',{action:'save',sessionId:session.id,hostIds:hosts.map(person=>person.id),attendeeIds:attendees.map(person=>person.id)});if(data.error)throw new Error(data.error);onSaved(data.session);}catch(e){setError(e.response?.data?.error || e.message);}finally{setBusy(false);operation.finish();}};
 return <form onSubmit={save} className="space-y-4"><section className="space-y-2"><h3 className="text-sm font-semibold">Hosts</h3><p className="text-xs text-muted-foreground">Hosts can resume, review and end this meeting. The original organiser remains a host.</p>{hosts.map(person=><div key={person.id} className="flex items-center justify-between gap-2 rounded-md bg-muted p-2 text-sm"><span>{person.name}</span>{person.id!==session.owner_id && <Button type="button" size="sm" variant="ghost" disabled={busy} onClick={()=>setHosts(items=>items.filter(item=>item.id!==person.id))}>Remove</Button>}</div>)}{hosts.length<10 && <MeetingPersonPicker kind="host" disabled={busy} onSelect={person=>add(setHosts,person)}/>}</section><section className="space-y-2"><h3 className="text-sm font-semibold">Attendees</h3><p className="text-xs text-muted-foreground">Listed attendees can view the saved meeting and its activity; project access stays unchanged.</p>{attendees.map(person=><div key={person.id} className="flex items-center justify-between gap-2 rounded-md bg-muted p-2 text-sm"><span>{person.name}</span><Button type="button" size="sm" variant="ghost" disabled={busy} onClick={()=>setAttendees(items=>items.filter(item=>item.id!==person.id))}>Remove</Button></div>)}{attendees.length<50 && <MeetingPersonPicker kind="attendee" disabled={busy} onSelect={person=>add(setAttendees,person)}/>}</section>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button disabled={busy}>{busy ? 'Saving…' : 'Save hosts and attendees'}</Button></form>;
}