import React from 'react';
import {useInfiniteQuery} from '@tanstack/react-query';
import {base44} from '@/api/base44Client';
import {Button} from '@/components/ui/button';
import {formatDateTime} from '@/lib/portal';
import ReviewQueryState from '@/components/projects/workspace/ReviewQueryState';
export default function MeetingFollowUpPicker({user,currentSession,onSelect}) {
 const query=useInfiniteQuery({queryKey:['meeting-history','follow-up',user.id,user.role,currentSession?.key_points],initialPageParam:null,queryFn:({pageParam})=>base44.entities.CRMActivity.filter({type:'internal_meeting',next_action:'meeting_start',...(currentSession ? {key_points:{$ne:currentSession.key_points}} : {})},{sort:'-occurred_at',limit:20,...(pageParam ? {cursor:pageParam} : {})}),getNextPageParam:page=>page.has_more ? page.next_cursor : undefined});
 return <ReviewQueryState query={query}><div className="space-y-3"><p className="text-sm text-muted-foreground">Choose a previous meeting to review its actions that are still open or in progress.</p>{query.data?.pages.flatMap(page=>page.items).map(session=><button type="button" key={session.id} onClick={()=>onSelect(session)} className="block w-full rounded-lg border border-border p-4 text-left hover:bg-muted"><span className="block text-sm font-semibold">{session.subject}</span><span className="mt-1 block text-xs text-muted-foreground">{session.author_name} · {formatDateTime(session.occurred_at)}</span><span className="mt-2 block text-xs underline">Review outstanding actions</span></button>)}{!query.data?.pages[0].items.length && <p className="text-sm text-muted-foreground">No accessible previous meetings yet.</p>}{query.hasNextPage && <Button size="sm" variant="outline" disabled={query.isFetchingNextPage} onClick={()=>query.fetchNextPage()}>{query.isFetchingNextPage ? 'Loading…' : 'Load more meetings'}</Button>}</div></ReviewQueryState>;
}