import React from 'react';
import {Button} from '@/components/ui/button';
import {aseError} from '@/components/ase/aseClient';
import useASEAutomation from '@/components/ase/useASEAutomation';
import ASEAutomationProgress from '@/components/ase/ASEAutomationProgress';
import ASEAutomationReport from '@/components/ase/ASEAutomationReport';
export default function ASEAutomationPanel({accountId}) {
  const {scope,status,action,cursor,setCursor,outcome,filter}=useASEAutomation(accountId),run=status.data?.run,active=run && ['queued','running'].includes(run.status);
  return <section className="space-y-4 rounded-xl border border-border bg-card p-5"><div><h3 className="text-lg font-semibold">Automatic ASE {accountId ? 'assessment' : 'portfolio run'}</h3><p className="mt-2 text-sm text-muted-foreground">Refresh applicable sources and publish each assessment automatically. No approval step. HMRC is excluded; missing, ambiguous and no-result evidence never becomes a favourable score.</p><p className="mt-2 text-xs text-muted-foreground">Gazette collection respects its 21:00–07:00 UK fair-use window. Blackflag is reported as blocked until permitted authenticated API access is configured.</p></div>{scope.isPending ? <p role="status" className="text-sm">Checking Account coverage…</p> : scope.error ? <p role="alert" className="text-sm text-destructive">{aseError(scope.error)}</p> : <div className="flex flex-wrap items-center gap-3"><Button disabled={action.isPending || active || !scope.data.eligible_count} onClick={()=>action.mutate({action:'automationStart'})}>{action.isPending ? 'Saving request…' : accountId ? 'Refresh sources and auto-publish' : 'Start automatic portfolio run'}</Button><p className="text-xs text-muted-foreground">{scope.data.eligible_count} supported live Accounts · {scope.data.excluded_count} unsupported Accounts excluded · demos never included.</p></div>}{(action.error || status.error) && <p role="alert" className="text-sm text-destructive">{aseError(action.error || status.error)}</p>}{status.isPending ? <p role="status" className="text-sm">Loading run progress…</p> : run ? <><ASEAutomationProgress run={run} current={status.data.current} totals={status.data.totals} action={action}/><ASEAutomationReport jobs={status.data.jobs} outcome={outcome} filter={filter} cursor={cursor} setCursor={setCursor} action={action}/></> : <p className="text-sm text-muted-foreground">No automatic run started yet. Accounts with insufficient validated evidence will be published as Not assessed, not given a poor rating.</p>}</section>;
}