import React, { useState } from 'react';
import { useInfiniteQuery,useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/lib/AuthContext';
import { Button } from '@/components/ui/button';
import { Link } from 'react-router-dom';
import { formatCurrency,formatDate } from '@/lib/portal';
import { aseRequest,aseError } from '@/components/ase/aseClient';
import ASECommercialTermsForm from '@/components/ase/ASECommercialTermsForm';
export default function ASECommercialContractReview({accountId}) {
  const {user}=useAuth(),cache=useQueryClient(),[editing,setEditing]=useState(null);
  const query=useInfiniteQuery({queryKey:['ase','commercial-contracts',accountId,'pathway-fee-v4',user?.id],initialPageParam:null,queryFn:({pageParam})=>aseRequest('commercialContracts',{accountId,...(pageParam ? {cursor:pageParam} : {})}),getNextPageParam:page=>page.has_more ? page.next_cursor : undefined});
  const saved=()=>{setEditing(null);cache.invalidateQueries({queryKey:['ase','commercial',accountId]});cache.invalidateQueries({queryKey:['ase','commercial-contracts',accountId]});cache.invalidateQueries({queryKey:['ase','detail',accountId]});};
  return <div className="mt-4 space-y-3"><h4 className="text-sm font-semibold">Accessible signed contracts</h4>{query.isPending ? <p role="status" className="text-xs">Loading contracts…</p> : query.error ? <p role="alert" className="text-xs text-destructive">{aseError(query.error)} <button className="underline" onClick={()=>query.refetch()}>Try again</button></p> : <>{query.data.pages.flatMap(page=>page.items).map(contract=><div key={contract.id} className="rounded-lg border border-border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-semibold">{contract.project_name || contract.document_id} · {contract.document_id} · {contract.status} record · {contract.commercial_reviewed ? 'Terms reviewed' : contract.pathway_terms && contract.recorded_terms?.start && contract.recorded_terms?.end ? 'Pathway proposal estimate' : 'Missing proposal / programme or reviewed terms'}</p>{user?.role==='admin' && <Button variant="outline" size="sm" onClick={()=>setEditing(contract.id)}>{contract.commercial_reviewed ? 'Review terms' : 'Verify terms'}</Button>}</div><p className="mt-2 text-xs text-muted-foreground">Signed: {formatDate(contract.date_of_execution)}{contract.pathway_terms?.value>0 ? <> · Pathway contractor proposal R{contract.pathway_terms.revision || 1}: {formatCurrency(contract.pathway_terms.value)} (estimated, excluding VAT)</> : contract.recorded_terms?.value>0 && <> · Recorded project contract sum: {formatCurrency(contract.recorded_terms.value)} (not yet verified for this comparison)</>}</p><div className="mt-2 flex gap-3 text-xs">{contract.project_record_id && <Link className="underline" to={`/projects/${contract.project_record_id}`}>View project</Link>}{contract.link_to_file && /^https:\/\//i.test(contract.link_to_file) && <a className="underline" href={contract.link_to_file} target="_blank" rel="noreferrer">Open JCT document</a>}</div>{editing===contract.id && <ASECommercialTermsForm key={contract.id} accountId={accountId} contract={contract} onSaved={saved} onCancel={()=>setEditing(null)}/>}</div>)}{!query.data.pages[0].items.length && <p className="text-xs text-muted-foreground">No accessible executed contractor-side JCT records are linked to this account.</p>}{query.hasNextPage && <Button variant="outline" size="sm" disabled={query.isFetchingNextPage} onClick={()=>query.fetchNextPage()}>{query.isFetchingNextPage ? 'Loading…' : 'Load more contracts'}</Button>}{user?.role!=='admin' && <p className="text-xs text-muted-foreground">Company-matched current Pathway proposal values with complete programme dates count as estimates. An administrator can review signed terms to replace those estimates.</p>}</>}</div>;
}