import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { aseRequest,aseError } from '@/components/ase/aseClient';
import ASECommercialDateInputs from '@/components/ase/ASECommercialDateInputs';
export default function ASECommercialTermsForm({accountId,contract,onSaved,onCancel}) {
  const [form,setForm]=useState({value:contract.commercial_value ?? contract.pathway_terms?.value ?? contract.recorded_terms?.value ?? '',start:contract.commercial_date_basis==='project_programme' ? '' : contract.commercial_start || '',end:contract.commercial_date_basis==='project_programme' ? '' : contract.commercial_end || '',dateBasis:contract.commercial_date_basis || (contract.commercial_start && contract.commercial_end ? 'contract_dates' : 'project_programme'),reference:contract.commercial_reference || contract.document_id || '',confirmed:false}),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const submit=async event=>{event.preventDefault();setBusy(true);setError('');try {await aseRequest('reviewCommercialTerms',{accountId,contractId:contract.id,...form,value:Number(form.value)});onSaved();} catch(error) {setError(aseError(error));} finally {setBusy(false);}};
  return <form onSubmit={submit} className="mt-3 space-y-3 rounded-lg border border-border bg-muted/40 p-3"><h4 className="text-sm font-semibold">Verify signed contract terms · {contract.document_id}</h4><p className="text-xs text-muted-foreground">Use this company’s signed GBP income excluding VAT, not the client’s expenditure or an estimated project budget. Use one record per signed contract. {contract.pathway_terms ? <span>{contract.pathway_terms.source} Verify this value against the signed document before marking it reviewed.</span> : contract.recorded_terms && <span>{contract.recorded_terms.source}</span>} Confirm the contract is still current even if its imported record is marked inactive.</p><div className="grid gap-3 sm:grid-cols-2">{[['value','Company contract value (£)','number'],['reference','Signed contract reference','text']].map(([key,label,type])=><label className="text-xs" key={key}>{label}<Input className="mt-1" required type={type} min={key==='value' ? '0.01' : undefined} step={key==='value' ? '0.01' : undefined} maxLength={key==='reference' ? 500 : undefined} value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})}/></label>)}</div><ASECommercialDateInputs form={form} setForm={setForm} programme={contract.recorded_terms}/><label className="flex items-start gap-2 text-xs"><input type="checkbox" required checked={form.confirmed} onChange={event=>setForm({...form,confirmed:event.target.checked})}/><span>I have checked the signed document and company-specific value, reviewed the selected date basis, and confirmed this is a current, non-duplicate contract; project programme dates are estimates, not confirmed contract dates.</span></label>{error && <p role="alert" className="text-xs text-destructive">{error}</p>}<div className="flex gap-2"><Button disabled={busy || (form.dateBasis==='project_programme' && (!contract.recorded_terms?.start || !contract.recorded_terms?.end))} size="sm" type="submit">{busy ? 'Saving…' : 'Save verified terms'}</Button><Button type="button" disabled={busy} variant="ghost" size="sm" onClick={onCancel}>Cancel</Button></div></form>;
}