import React, { useState } from 'react';
import { useInfiniteQuery,useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/lib/AuthContext';
import { Button } from '@/components/ui/button';
import { aseRequest,aseError } from '@/components/ase/aseClient';
import ASECommercialTermsForm from '@/components/ase/ASECommercialTermsForm';
export default function ASECommercialContractReview({accountId}) {
  const {user}=useAuth(),cache=useQueryClient(),[editing,setEditing]=useState(null);
  const query=useInfiniteQuery({queryKey:['ase','commercial-contracts',accountId,user?.id],initialPageParam:null,queryFn:({pageParam})=>aseRequest('commercialContracts',{accountId,...(pageParam ? {cursor:pageParam} : {})}),getNextPageParam:page=>page.has_more ? page.next_cursor : undefined});
  const saved=()=>{setEditing(null);cache.invalidateQueries({queryKey:['ase','commercial',accountId]});cache.invalidateQueries({queryKey:['ase','commercial-contracts',accountId]});cache.invalidateQueries({queryKey:['ase','detail',accountId]});};
  return <div className="mt-4 space-y-3"><h4 className="text-sm font-semibold">Accessible active signed contracts</h4>{query.isPending ? <p role="status" className="text-xs">Loading contracts…</p> : query.error ? <p role="alert" className="text-xs text-destructive">{aseError(query.error)} <button className="underline" onClick={()=>query.refetch()}>Try again</button></p> : <>{query.data.pages.flatMap(page=>page.items).map(contract=><div key={contract.id} className="rounded-lg border border-border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-semibold">{contract.document_id} · {contract.commercial_reviewed ? 'Terms reviewed' : 'Terms not verified'}</p>{user?.role==='admin' && <Button variant="outline" size="sm" onClick={()=>setEditing(contract.id)}>{contract.commercial_reviewed ? 'Review terms' : 'Verify terms'}</Button>}</div>{editing===contract.id && <ASECommercialTermsForm key={contract.id} accountId={accountId} contract={contract} onSaved={saved} onCancel={()=>setEditing(null)}/>}</div>)}{!query.data.pages[0].items.length && <p className="text-xs text-muted-foreground">No accessible active, executed contractor-side JCT records are linked to this account.</p>}{query.hasNextPage && <Button variant="outline" size="sm" disabled={query.isFetchingNextPage} onClick={()=>query.fetchNextPage()}>{query.isFetchingNextPage ? 'Loading…' : 'Load more contracts'}</Button>}{user?.role!=='admin' && <p className="text-xs text-muted-foreground">An administrator must verify signed contract terms before they count towards the comparison.</p>}</>}</div>;
}