import React from 'react';
import {BarChart3, ShieldCheck, FileCheck2, TrendingUp, TrendingDown, Minus} from 'lucide-react';
const confidenceClasses={High:'bg-success',Medium:'bg-risk-moderate',Low:'bg-risk-high'};
export default function ASEDialFacts({current,loading}) {
 const change=current?.change,Trend=change>0 ? TrendingUp : change<0 ? TrendingDown : Minus;
 const confidence=current?.data_confidence,filled={High:3,Medium:2,Low:1}[confidence] || 0;
 return <div className="grid min-w-0 gap-3 text-left">
  <div className="rounded-lg bg-muted p-3"><div className="flex items-start gap-2"><BarChart3 className="mt-0.5 h-4 w-4 shrink-0"/><div className="min-w-0 flex-1"><p className="text-xs font-medium">Previous rating</p><div className="mt-1 flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-muted-foreground">{current?.previous_rating!=null ? `${current.previous_rating}/5` : 'Not available'}</p>{current?.previous_rating!=null && change!=null && <span className={`inline-flex items-center gap-1 text-xs font-semibold ${change>0 ? 'text-success' : change<0 ? 'text-destructive' : 'text-muted-foreground'}`}><Trend className="h-4 w-4"/>{change>0 ? '+' : ''}{change}<span className="sr-only">{change>0 ? 'Improved' : change<0 ? 'Declined' : 'Unchanged'}</span></span>}</div></div></div></div>
  <div className="rounded-lg bg-muted p-3"><div className="flex items-start gap-2"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0"/><div className="min-w-0 flex-1"><p className="text-xs font-medium">Data confidence</p><p className="mt-1 text-sm font-semibold">{loading ? 'Loading…' : confidence || 'Not assessed'}</p><div className="mt-2 flex gap-1" aria-hidden="true">{[1,2,3,4].map(segment=><span key={segment} className={`h-1.5 flex-1 rounded-full ${segment<=filled ? confidenceClasses[confidence] : 'bg-border'}`}/>)}</div></div></div></div>
  <div className="rounded-lg bg-muted p-3"><div className="flex items-start gap-2"><FileCheck2 className="mt-0.5 h-4 w-4 shrink-0"/><div className="min-w-0"><p className="text-xs font-medium">Assessment status</p><p className="mt-1 text-sm font-semibold">{loading ? 'Calculating…' : current?.is_provisional ? 'Provisional' : current?.displayed_rating ? 'Published' : 'Awaiting evidence'}</p><p className="mt-1 text-[11px] text-muted-foreground">{current?.is_provisional ? 'Calculated from available evidence; not a published rating' : current?.displayed_rating ? 'Based on recorded evidence' : 'No scored evidence available'}</p></div></div></div>
 </div>;
}