import React,{useState} from 'react';
import ASEEvidenceForm from '@/components/ase/ASEEvidenceForm';
import {aseSourceRequest} from '@/components/ase/useASESources';
export default function ASEGovernanceReview({accountId,rules,evidence,onSaved}) {
  const [verification,setVerification]=useState({primary_reference:evidence.governance_review?.primary_reference || '',document_status:evidence.governance_review?.document_status || '',audit_basis:evidence.governance_review?.audit_basis || '',operative_from:evidence.governance_review?.operative_from || '',operative_to:evidence.governance_review?.operative_to || '',identity_confirmed:false,primary_document_checked:false,material_findings_confirmed:false});
  const set=(key,value)=>setVerification(old=>({...old,[key]:value})),audit=evidence.component==='audit',input='mt-1 w-full rounded-md border border-input bg-background p-2 text-sm';
  return <ASEEvidenceForm accountId={accountId} rules={rules.filter(rule=>rule.key===evidence.component)} initialEvidence={evidence} onSaved={onSaved} submitEvidence={draft=>aseSourceRequest('review',{accountId,source:evidence.external_key.split(':')[2],evidenceId:evidence.id,evidence:draft,verification})}>
    <fieldset className="space-y-3 rounded-lg border border-border p-3"><legend className="px-1 text-sm font-semibold">Council audit / intervention verification</legend><p className="text-xs text-muted-foreground">Confirm the full council identity, actual financial period and operative dates. Search mentions, inspection, publication delays and missing matches are not verified adverse events.</p>
      <label className="block text-sm">Primary council / auditor report or signed notice URL<input required type="url" maxLength={1000} className={input} value={verification.primary_reference} onChange={e=>set('primary_reference',e.target.value)} placeholder="https://…"/></label>
      <label className="block text-sm">Documented position<select required className={input} value={verification.document_status} onChange={e=>set('document_status',e.target.value)}><option value="">Choose status</option><option value="current">Current</option><option value="resolved">Resolved</option><option value="historic">Historic</option></select></label>
      {audit ? <><label className="block text-sm">Audit opinion basis<select required className={input} value={verification.audit_basis} onChange={e=>set('audit_basis',e.target.value)}><option value="">Choose the verified basis</option><option value="substantive">Substantive auditor findings / opinion</option><option value="mixed">Mixed: backstop limitation and substantive findings</option><option value="backstop_only">Backstop-only disclaimer / limitation, context only</option></select></label><p className="text-xs text-muted-foreground">Backstop-only limitations are excluded from scoring regardless of the classification selected above. Mixed findings require independent confirmation of material issues before a material or adverse classification.</p>{verification.audit_basis==='mixed' && <label className="flex gap-2 text-sm"><input type="checkbox" checked={verification.material_findings_confirmed} onChange={e=>set('material_findings_confirmed',e.target.checked)}/>Substantive material findings are confirmed independently of the backstop.</label>}</> : <div className="grid gap-3 sm:grid-cols-2">{[['operative_from','Commencement / notice date'],['operative_to','Resolved / ended date']].map(([key,label])=><label key={key} className="text-sm">{label}<input type="date" max={new Date().toISOString().slice(0,10)} className={input} value={verification[key]} onChange={e=>set(key,e.target.value)}/></label>)}</div>}
      <label className="flex gap-2 text-sm"><input required type="checkbox" checked={verification.identity_confirmed} onChange={e=>set('identity_confirmed',e.target.checked)}/>I verified this primary document concerns this exact council.</label>
      <label className="flex gap-2 text-sm"><input required type="checkbox" checked={verification.primary_document_checked} onChange={e=>set('primary_document_checked',e.target.checked)}/>I read the primary document and verified the findings, period and current status.</label>
    </fieldset>
  </ASEEvidenceForm>;
}