import React from 'react';
import {Info, CheckCircle2, ChevronRight} from 'lucide-react';
import ASEGauge from '@/components/ase/ASEGauge';
import ASEDialFacts from '@/components/ase/ASEDialFacts';
import ASERefreshTime from '@/components/ase/ASERefreshTime';
import allSeeingEyeText from '@/components/ase/allSeeingEyeText';
export default function ASEOverviewContent({current,loading,error}) {
 const available=!error && !loading && current?.displayed_rating;
 return <div className="space-y-4">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-lg font-bold">All Seeing Eye Rating <Info className="h-3.5 w-3.5 text-muted-foreground" aria-hidden="true"/></p><p className="text-xs text-muted-foreground">{!current || current.methodology==='ASE v2' ? 'All Seeing Eye · Current methodology' : current.is_legacy ? 'Legacy assessment · awaiting ASE v2' : 'All Seeing Eye · Legacy methodology'}</p></div><div className="text-right">{available && <span className={`inline-flex items-center gap-1 rounded-md px-2 py-1 text-[11px] font-semibold ${current.is_provisional ? 'bg-risk-high/10 text-risk-high' : 'bg-success/10 text-success'}`}><CheckCircle2 className="h-3 w-3"/>{current.is_provisional ? 'Provisional' : 'Published'}</span>}<ASERefreshTime date={current?.assessment_date}/></div></div>
  <div className="grid items-center gap-4 sm:grid-cols-[minmax(0,1.15fr)_minmax(0,1fr)]"><div className="min-w-0 text-center"><div className="mx-auto max-w-64"><ASEGauge rating={error ? null : current?.displayed_rating} precise={current?.precise_score} label={current?.rating_label} loading={loading} showScale decimal={current?.methodology==='ASE v2'}/></div><p className="mx-auto -mt-4 max-w-64 text-xs leading-relaxed text-muted-foreground">{loading ? 'Loading the latest assessment…' : error ? 'Assessment details are currently unavailable.' : available ? current?.methodology==='ASE v2' ? `${current.coverage?.toFixed(1)}% evidence coverage · ${current.is_provisional ? `Provisional score from available evidence; ${current.evidence_minimum}% coverage is required for a published rating` : 'Alliance-specific stability and exposure'}` : 'Internal organisational-health assessment' : 'Insufficient data to display a published All Seeing Eye rating.'}</p>{current?.is_demo && <p className="mt-2 text-xs font-semibold text-primary">Fictional demonstration</p>}</div><ASEDialFacts current={error ? null : current} loading={loading}/></div>
  {current?.explanation && !error && <p className="line-clamp-3 text-xs leading-relaxed text-muted-foreground">{allSeeingEyeText(current.explanation)}</p>}
  <div className="flex items-center justify-center gap-2 rounded-md bg-als-navy px-4 py-2.5 text-xs font-semibold text-sidebar-foreground">Why this rating? <ChevronRight className="h-4 w-4"/></div>
 </div>;
}