import React, { useState } from 'react';
import { useMutation,useQueryClient } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { aseRequest,aseError,invalidateASE } from '@/components/ase/aseClient';
export default function ASEPolicyEditor({policy,onSaved}) {
  const cache=useQueryClient();
  const [weights,setWeights]=useState(()=>Object.fromEntries(Object.entries(policy.models).map(([model,rules])=>[model,Object.fromEntries(rules.map(r=>[r.key,r.weighting]))])));
  const totals=Object.fromEntries(Object.entries(weights).map(([model,values])=>[model,Object.values(values).reduce((sum,value)=>sum+Number(value),0)]));
  const save=useMutation({mutationFn:()=>aseRequest('savePolicy',{weights}),onSuccess:()=>{invalidateASE(cache);onSaved();}});
  return <form onSubmit={event=>{event.preventDefault();save.mutate();}} className="space-y-5"><div className="grid gap-5 xl:grid-cols-2">{Object.entries(policy.models).map(([model,rules])=><section className="rounded-xl border border-border bg-card p-5" key={model}><h3 className="mb-4 font-semibold">{model==='company' ? 'UK Limited Companies & PLCs' : 'English Local Authorities'}</h3><div className="space-y-4">{rules.map(rule=><label className="block" key={rule.key}><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium">{rule.label}</span><div className="flex items-center gap-2"><input aria-label={`${model} ${rule.label} weighting`} type="number" min="0" max="100" step="0.1" required className="w-20 rounded-md border border-input bg-background p-2 text-sm" value={weights[model][rule.key]} onChange={e=>setWeights(old=>({...old,[model]:{...old[model],[rule.key]:Number(e.target.value)}}))}/><span>%</span></div></div><p className="mt-1 text-xs text-muted-foreground">{rule.choices ? rule.choices.map(c=>`${c.score}: ${c.label}`).join(' · ') : `${rule.unit}. Boundaries: ${rule.thresholds.join(', ')}. ${rule.descending ? 'Lower is stronger' : 'Higher is stronger'}; crossing each boundary changes the rating by one. ${rule.strict ? 'Upper limits inclusive.' : 'Lower limits inclusive.'}`}</p></label>)}</div><p className={`mt-4 text-sm font-semibold ${Math.abs(totals[model]-100)<0.000001 ? 'text-success' : 'text-destructive'}`}>Total: {totals[model]}% / 100%</p></section>)}</div><p className="text-xs text-muted-foreground">Approved scoring thresholds stay fixed. Commercial concentration is derived from contract and turnover inputs; estimates and incomplete comparisons are Low confidence and make the overall rating provisional. Local authorities do not use this component. Saving weightings creates a new policy version; only future assessments use it. Missing components are excluded and remaining weights normalised. At least one usable positively weighted component produces a provisional rating. Standard ratings require at least 60% weighting, three components and no Low-confidence evidence. Provisional ratings always have Low confidence; no usable evidence remains Not assessed. High confidence: ≥90% coverage, financial period ≤18 months, three annual periods, checks ≤90 days. Medium: ≥60%, ≤30 months, two periods, checks ≤180 days. Otherwise Low.</p>{save.error && <p role="alert" className="text-destructive">{aseError(save.error)}</p>}<Button disabled={save.isPending || Object.values(totals).some(value=>Math.abs(value-100)>0.000001)} type="submit">{save.isPending ? 'Saving policy version…' : 'Save approved weightings'}</Button></form>;
}