import React,{useState} from 'react';
import { useMutation,useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { aseError,invalidateASE } from '@/components/ase/aseClient';
import { aseSourceRequest } from '@/components/ase/useASESources';
export default function ASESourceIdentifiers({account}) {
  const cache=useQueryClient(),[vat,setVat]=useState(account.vat_number),[code,setCode]=useState(account.local_authority_code);
  const preview=useMutation({mutationFn:()=>aseSourceRequest('previewCouncil',{accountId:account.id,code:code.trim().toUpperCase()})});
  const save=useMutation({mutationFn:()=>base44.entities.Account.update(account.id,{vat_number:vat.trim().toUpperCase(),local_authority_code:code.trim().toUpperCase()}),onSuccess:()=>{invalidateASE(cache);cache.invalidateQueries({queryKey:['account',account.id]});}});
  return <form className="rounded-lg border border-border p-3" onSubmit={e=>{e.preventDefault();save.mutate();}}><h4 className="text-sm font-semibold">Source identifiers</h4><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-xs">Account’s UK VAT number<input className="mt-1 w-full rounded-md border border-input bg-background p-2 text-sm" value={vat} maxLength={20} onChange={e=>setVat(e.target.value)} placeholder="GB followed by 9 or 12 digits" pattern="(GB|gb)?[0-9 ]{9,16}"/></label><label className="text-xs">English council ONS code<input className="mt-1 w-full rounded-md border border-input bg-background p-2 text-sm" value={code} maxLength={9} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="For example E08000032" pattern="E[0-9]{8}"/></label></div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" type="submit" variant="outline" disabled={save.isPending}>{save.isPending ? 'Saving…' : 'Save identifiers'}</Button><Button size="sm" type="button" variant="outline" disabled={!/^E\d{8}$/.test(code) || preview.isPending} onClick={()=>preview.mutate()}>{preview.isPending ? 'Checking official returns…' : 'Check council code'}</Button></div>{preview.data && <p className="mt-2 text-xs">Code resolves to {preview.data.summary.authority_name} · Financial years: {preview.data.summary.financial_years.join(', ')}. Confirm this is the correct Account before saving.</p>}{save.isSuccess && <p className="mt-2 text-xs text-success">Identifiers saved. Run the relevant source check below.</p>}{(save.error || preview.error) && <p role="alert" className="mt-2 text-sm text-destructive">{aseError(save.error || preview.error)}</p>}</form>;
}