import React,{useState} from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/lib/AuthContext';
import { aseError,invalidateASE } from '@/components/ase/aseClient';
import useASESources,{aseSourceRequest} from '@/components/ase/useASESources';
import ASESourceCard from '@/components/ase/ASESourceCard';
import ASESourceIdentifiers from '@/components/ase/ASESourceIdentifiers';
import ASEEvidenceTable from '@/components/ase/ASEEvidenceTable';
import ASEEvidenceForm from '@/components/ase/ASEEvidenceForm';
import ASERegistrySource from '@/components/ase/ASERegistrySource';
import ASESourceCoverage from '@/components/ase/ASESourceCoverage';
export default function ASESourcesPanel({accountId,data}) {
  const {user}=useAuth(),cache=useQueryClient(),{query,refresh}=useASESources(accountId,user),[review,setReview]=useState(null),admin=user?.role==='admin';
  const evidence=(data.sourceEvidence || []).filter(row=>row.external_key?.startsWith('ase-source:') && query.data?.sources.some(source=>source.audit?.id===row.source_refresh_id));
  const canReview=row=>admin && data.model && row.source!=='HMRC VAT' && row.component!=='external_risk_score';
  const keyFor=row=>row.external_key.split(':')[2];
  return <section className="space-y-4 rounded-xl border border-border p-4"><h3 className="font-semibold">ASE connected evidence sources</h3><p className="text-xs text-muted-foreground">Collect registry and financial evidence here for this Account. Full registry details remain in the Account overview. Collected facts are context or review candidates; only administrator-approved normalised evidence can affect a new ASE assessment. Previous ratings are never rewritten.</p>{query.isPending ? <p role="status" className="text-sm">Loading source connections…</p> : query.error ? <p role="alert" className="text-sm text-destructive">{aseError(query.error)} <button className="underline" onClick={()=>query.refetch()}>Retry</button></p> : <>{admin && <ASESourceIdentifiers key={query.data.account.vat_number+query.data.account.local_authority_code} account={query.data.account}/>}<div className="grid gap-3 md:grid-cols-2"><ASERegistrySource accountId={accountId} model={data.model} admin={admin}/>{query.data.sources.map(source=><ASESourceCard key={source.key} accountId={accountId} source={source} admin={admin} refresh={refresh}/>)}</div></>}<ASESourceCoverage model={data.model}/>{refresh.error && <p role="alert" className="text-sm text-destructive">{aseError(refresh.error)}</p>}{refresh.isSuccess && <p className="text-sm text-success">{refresh.data.evidenceCount} source records saved for review. The existing ASE rating is unchanged.</p>}{!!evidence.length && <ASEEvidenceTable evidence={evidence} title="Collected source evidence" renderAction={row=>canReview(row) && <button className="mt-2 text-xs font-semibold underline" onClick={()=>setReview(row)}>{row.score_eligible ? 'Review approved component' : 'Review for ASE scoring'}</button>}/>} {review && data.model && <div><button className="text-xs underline" onClick={()=>setReview(null)}>Close review</button><ASEEvidenceForm key={review.id} accountId={accountId} rules={data.policy.models[data.model]} initialEvidence={review} submitEvidence={evidence=>aseSourceRequest('review',{accountId,source:keyFor(review),evidenceId:review.id,evidence})} onSaved={()=>{setReview(null);invalidateASE(cache);}}/></div>}</section>;
}