import React,{useState} from 'react';
import { useMutation } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { formatDateTime } from '@/lib/portal';
import { aseError } from '@/components/ase/aseClient';
import ASESourceInsight from '@/components/ase/ASESourceInsight';
const descriptions={accounts:'Primary Companies House XML/iXBRL filings, GBP financial facts and deterministic ratio candidates. PDF-only accounts require manual evidence.',blackflag:'Permitted public company crawl: financial facts, external R-Score, court-check status and distressed-debtor exposure.',gazette:'Official insolvency notices, matched by company number and checked against notice bodies.',hmrc:'Live production VAT registration lookup. VAT registration is not proof of financial strength.',local_authority:'MHCLG financial returns by ONS code, Exceptional Financial Support registers and official governance-document discovery.'};
export default function ASESourceCard({accountId,source,admin,refresh}) {
  const [requester,setRequester]=useState(''),audit=source.audit,latest=source.latest,busy=refresh.isPending;
  const download=useMutation({mutationFn:async()=>{const {signed_url}=await base44.integrations.Core.CreateFileSignedUrl({file_uri:audit.raw_file_uri});window.open(signed_url,'_blank','noopener,noreferrer');}});
  return <article className="min-w-0 rounded-lg border border-border bg-card p-4"><h4 className="font-semibold">{source.name}</h4><p className="mt-2 text-xs text-muted-foreground">{descriptions[source.key]}</p>{source.blocked ? <p className="mt-3 text-xs text-muted-foreground">{source.blocked}</p> : <><p className="mt-3 text-xs">Identifier: {source.identifier} · {audit ? `${audit.summary?.evidence_count || 0} source records collected` : 'Not checked'}</p>{audit && <p className="mt-1 text-xs text-muted-foreground">Last collection: {formatDateTime(audit.refreshed_at)}</p>}{latest?.status==='pending' && <p role="status" className="mt-2 text-xs">Collection started at {formatDateTime(latest.refreshed_at)}; a pending or interrupted check is not a clean result.</p>}{latest?.status==='failed' && <p role="alert" className="mt-2 text-xs text-destructive">Last check failed: {latest.error}</p>}{source.key==='accounts' && audit && <p className="mt-2 text-xs">{audit.summary.documents_retrieved} documents retrieved · {audit.summary.financial_periods?.join(', ') || 'No supported tagged financial periods'} · {audit.summary.normalised_candidates || 0} scoring candidates awaiting review</p>}{audit?.summary?.external_score!=null && <p className="mt-2 text-sm">Blackflag R-Score: {audit.summary.external_score}/100 · {audit.summary.risk_label || 'Unknown band'} <span className="text-xs text-muted-foreground">(not ASE)</span></p>}{source.key==='hmrc' && audit && <p className="mt-2 text-xs">{audit.summary.registered ? `VAT registered: ${audit.summary.registered_name}` : 'VAT number not found'} · {audit.summary.consultation_reference ? `HMRC reference: ${audit.summary.consultation_reference}` : 'Simple lookup, no HMRC reference'}</p>}{admin && source.key==='hmrc' && <label className="mt-3 block text-xs">Your organisation’s VAT (optional, for a referenced HMRC check)<input className="mt-1 w-full rounded-md border border-input bg-background p-2" maxLength={20} value={requester} onChange={e=>setRequester(e.target.value)}/></label>}{admin && <Button className="mt-3" size="sm" variant="outline" disabled={busy} onClick={()=>refresh.mutate({source:source.key,requesterVat:requester})}>{busy && refresh.variables?.source===source.key ? 'Collecting source evidence…' : source.key==='hmrc' ? 'Check live VAT registration' : 'Refresh source'}</Button>}{audit?.warnings?.map((warning,index)=><p className="mt-2 text-xs text-muted-foreground" key={index}>{warning}</p>)}{audit && <><ASESourceInsight key={audit.id} accountId={accountId} source={source.key} audit={audit} admin={admin}/><Button className="mt-3" size="sm" variant="ghost" disabled={download.isPending} onClick={()=>download.mutate()}>{download.isPending ? 'Preparing download…' : 'Download private source snapshot'}</Button>{download.error && <p role="alert" className="text-xs text-destructive">{aseError(download.error)}</p>}</>}</>}</article>;
}