import React from 'react';
import {Link} from 'react-router-dom';
import RelationshipStrength from '@/components/relationships/RelationshipStrength';
const date=value=>value ? new Date(value).toLocaleDateString('en-GB') : 'Not recorded';
export default function PeopleResults({rows,view}) {
  const person=row=><Link to={`/people/${row.person.id}`} className="flex items-center gap-3 font-semibold hover:text-primary"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-secondary text-xs">{row.person.full_name?.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><span>{row.person.full_name}{row.profile?.key_decision_maker && <span className="ml-1 text-primary" title="Key decision-maker">★</span>}</span></Link>;
  const org=row=>row.organisation ? <Link className="hover:text-primary hover:underline" to={`/accounts/${row.organisation.id}`}>{row.organisation.name}</Link> : row.person.company_name || 'Organisation not linked';
  if(!rows.length) return <div className="rounded-xl border border-dashed border-border bg-card px-6 py-16 text-center"><h2 className="font-semibold">Find the people behind your relationships</h2><p className="mt-2 text-sm text-muted-foreground">No people match this selection. Clear the filters or search a different name or organisation.</p></div>;
  if(view==='cards') return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map(row=><article key={row.person.id} className="space-y-4 rounded-xl border border-border bg-card p-5 shadow-sm">{person(row)}<div className="text-sm"><p>{row.person.job_title || row.person.officer_role || 'Role not recorded'}</p><p className="mt-1 text-muted-foreground">{org(row)}</p></div><RelationshipStrength profile={row.profile} last={row.last}/><dl className="grid grid-cols-2 gap-3 text-xs"><div><dt className="text-muted-foreground">Last interaction</dt><dd className="mt-1">{date(row.last)}</dd></div><div><dt className="text-muted-foreground">Relationship owner</dt><dd className="mt-1">{row.owner || 'Not assigned'}</dd></div></dl><p className="border-t border-border pt-3 text-xs">Next: {row.next?.title || 'Set a next action in this person’s workspace'}</p></article>)}</div>;
  return <div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="w-full min-w-[1080px] text-left text-xs"><thead className="border-b border-border bg-muted/50 text-muted-foreground"><tr>{['Person','Job title','Organisation','Relationship','Last interaction','Next action','Relationship owner'].map(h=><th className="px-4 py-3 font-medium" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{rows.map(row=><tr className="hover:bg-muted/40" key={row.person.id}><td className="px-4 py-4">{person(row)}</td><td className="max-w-40 px-4 py-4 text-muted-foreground">{row.person.job_title || row.person.officer_role || 'Not recorded'}</td><td className="max-w-44 px-4 py-4">{org(row)}</td><td className="px-4 py-4"><RelationshipStrength profile={row.profile} last={row.last}/></td><td className="px-4 py-4">{date(row.last)}</td><td className="max-w-52 px-4 py-4"><Link className="hover:underline" to={`/people/${row.person.id}?tab=overview&action=task`}>{row.next?.title || 'Set next action'}</Link>{row.next?.due_at && <p className={`mt-1 ${Date.parse(row.next.due_at)<Date.now() ? 'text-primary' : 'text-muted-foreground'}`}>{date(row.next.due_at)}</p>}</td><td className="px-4 py-4">{row.owner || 'Not assigned'}</td></tr>)}</tbody></table></div>;
}