import React,{useEffect,useState} from 'react';
import {base44} from '@/api/base44Client';
import {useQueryClient} from '@tanstack/react-query';
import {useAuth} from '@/lib/AuthContext';
export default function PeopleFilters({filters,onChange}) {
  const cache=useQueryClient(),{user}=useAuth();
  const [owners,setOwners]=useState([]),[organisations,setOrganisations]=useState([]),[term,setTerm]=useState('');
  useEffect(()=>{let active=true;cache.fetchQuery({queryKey:['people-staff',user?.id,user?.role],staleTime:60000,retry:false,queryFn:()=>base44.entities.Contact.filter({portal_role:{$in:['admin','director','regional_director','bsm','finance','bdm']}},{limit:100,sort:'full_name',fields:['full_name','portal_role']})}).then(p=>{if(active)setOwners(p.items);});return()=>{active=false;};},[cache,user?.id,user?.role]);
  useEffect(()=>{const timer=setTimeout(()=>base44.entities.Account.filter(term ? {name:{$regex:term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),$options:'i'}} : {},{limit:50,sort:'name',fields:['name']}).then(p=>setOrganisations(p.items)),300);return()=>clearTimeout(timer);},[term]);
  const select=(key,label,choices)=><label className="sr-only">{label}</label>;
  const field=(key,label,choices)=><select aria-label={label} className="max-w-56 rounded-lg border border-input bg-card px-3 py-2 text-xs" value={filters[key] || ''} onChange={e=>onChange({...filters,[key]:e.target.value})}><option value="">{label}</option>{choices.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select>;
  return <div className="flex flex-wrap items-center gap-2"><input aria-label="Find organisation filter" className="w-40 rounded-lg border border-input bg-card px-3 py-2 text-xs" placeholder="Find organisation…" value={term} onChange={e=>setTerm(e.target.value)}/>{field('organisation','Organisation',organisations.map(a=>[a.id,a.name]))}{field('strength','User-set strength',['strong','developing','cooling','new','limited','established'].map(v=>[v,v[0].toUpperCase()+v.slice(1)]))}{field('owner','Relationship owner',owners.map(p=>[p.id,p.full_name]))}{field('key','Decision-makers',[['yes','Key decision-makers']])}{field('strategic','Strategic relationship',[['yes','Strategic']])}{field('live','Live opportunity',[['yes','Linked to live opportunities']])}{field('portal','Portal user',[['yes','Linked portal identity'],['no','No linked portal identity']])}{field('status','Status',[['active','Active'],['inactive','Inactive']])}<button className="ml-auto text-xs text-muted-foreground hover:text-foreground" onClick={()=>{setTerm('');onChange({});}}>Clear all</button></div>;
}