import React,{useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {base44} from '@/api/base44Client';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {STAGES,updateCRMOpportunity,logCRMActivity} from '@/components/crm/crm';
export default function CommercialQuickAction({selection,user,onClose,onSaved}){
 const navigate=useNavigate(),{item,kind}=selection,[form,setForm]=useState({title:'',description:'',type:'call',due_date:'',stage:item.stage || 'lead',budget:item.budget ?? ''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const titles={interaction:'Log interaction',note:'Add note',action:'Set next action',stage:'Move stage',value:'Update value'},input='mt-1 w-full rounded-lg border border-input bg-background p-2 text-sm';
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{if(kind==='stage' && ['won','lost'].includes(form.stage)){onClose();navigate(`/opportunities/${item.id}?outcome=${form.stage}`);return;}if(kind==='stage')await updateCRMOpportunity(item,{stage:form.stage},user);else if(kind==='value')await updateCRMOpportunity(item,{budget:Number(form.budget)},user);else if(kind==='action'){await base44.entities.CRMTask.create({opportunity_id:item.id,account_id:item.account_id,title:form.title.trim(),description:form.description,due_date:form.due_date,owner_id:user.id,owner_name:user.full_name || user.email,line_manager_id:user.data?.line_manager_id || user.line_manager_id || '',status:'open',priority:'normal'});await logCRMActivity(item,user,'system',`Next action set: ${form.title.trim()}`,`Owner: ${user.full_name || user.email}\nDue: ${form.due_date}`);}else await logCRMActivity(item,user,kind==='note' ? 'note' : form.type,form.title.trim(),form.description.trim());await onSaved();onClose();}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <Dialog open onOpenChange={v=>!v && onClose()}><DialogContent><DialogHeader><DialogTitle>{titles[kind]}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{item.title}</p><form onSubmit={save} className="space-y-4">{['interaction','note','action'].includes(kind) && <label className="block text-sm">{kind==='action' ? 'Action' : 'Subject'}<input required maxLength={200} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className={input}/></label>}{kind==='interaction' && <label className="block text-sm">Interaction type<select className={input} value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{['call','meeting','email'].map(v=><option key={v} value={v}>{v}</option>)}</select></label>}{['interaction','note'].includes(kind) && <label className="block text-sm">Summary<textarea maxLength={3000} className={input} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>}{kind==='action' && <><label className="block text-sm">Due date<input required type="date" className={input} value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></label><p className="text-xs text-muted-foreground">Action owner: {user.full_name || user.email}. Existing task permissions assign this action to you.</p></>}{kind==='stage' && <label className="block text-sm">Stage<select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})} className={input}>{STAGES.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></label>}{kind==='value' && <label className="block text-sm">Opportunity value (£)<input required type="number" min="0" className={input} value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/></label>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex gap-2"><Button disabled={busy}>{busy ? 'Saving…' : kind==='stage' && ['won','lost'].includes(form.stage) ? 'Review outcome' : 'Save'}</Button><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Cancel</Button></div></form></DialogContent></Dialog>;
}