import React from 'react';
import RecordUpdatedAt from '@/components/RecordUpdatedAt';
import {Link} from 'react-router-dom';
import {MoreHorizontal} from 'lucide-react';
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {chance,stageLabel} from '@/components/crm/crm';
import {formatCurrency} from '@/lib/portal';
export default function CommercialCard({item,editable,onAction}){
 const age=item.stage_entered_at ? Math.max(0,Math.floor((Date.now()-Date.parse(item.stage_entered_at))/86400000)) : null,signal=item.overdue ? 'Next action overdue' : !item.next ? 'No next action' : item.expected_decision_date && item.expected_decision_date<new Date().toISOString().slice(0,10) && item.status==='open' ? 'Close date passed' : item.noRecent && item.status==='open' ? 'No recorded activity in 30 days' : '';
 return <article className="min-w-0 break-words rounded-xl border border-border bg-card p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><Link className="text-sm font-semibold leading-snug hover:text-primary" to={`/opportunities/${item.id}`}>{item.title}</Link><DropdownMenu><DropdownMenuTrigger aria-label={`Actions for ${item.title}`} className="rounded p-1 text-muted-foreground hover:bg-muted"><MoreHorizontal className="h-4 w-4"/></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem asChild><Link to={`/opportunities/${item.id}`}>Open opportunity</Link></DropdownMenuItem>{editable && [['interaction','Log interaction'],['note','Add note'],['action','Set next action'],['stage','Move stage'],['value','Update value']].filter(([key])=>item.status==='open' || ['interaction','note'].includes(key)).map(([key,label])=><DropdownMenuItem key={key} onSelect={()=>onAction(item,key)}>{label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div><Link className="mt-1 block text-xs text-muted-foreground hover:underline" to={`/accounts/${item.account_id}`}>{item.organisation?.name || 'Open organisation'}</Link><p className="mt-3 text-[11px] font-medium text-muted-foreground">{stageLabel(item.stage)}</p><p className="mt-3 text-sm font-semibold">{formatCurrency(item.budget)} <span className="font-normal text-muted-foreground">· {chance(item)}%</span></p><p className="mt-1 text-[11px] text-muted-foreground">Close: {item.expected_decision_date || 'Not set'} · {age===null ? 'Stage entry not recorded' : `${age} days in stage`}</p><div className="mt-3 flex items-center justify-between gap-2 text-[11px]"><span>{item.owner_name || 'Owner not assigned'}</span>{item.person && <Link className="truncate text-muted-foreground hover:text-primary" to={`/people/${item.person.id}`}>{item.person.full_name}</Link>}</div><div className="mt-3 border-t border-border pt-3 text-xs"><p className="text-muted-foreground">Next action</p><p className="mt-1 font-medium">{item.next?.title || 'Set the next step'}</p>{item.next && <p className="mt-1 text-[11px] text-muted-foreground">{item.next.due_date || 'Due date not set'} · {item.next.owner_name || 'Action owner not set'}</p>}</div><RecordUpdatedAt record={item} className="mt-3" />{signal && <p className={`mt-3 rounded-md px-2 py-1 text-[10px] ${item.overdue ? 'bg-primary/10 text-foreground' : 'bg-muted text-muted-foreground'}`}>{signal}</p>}</article>;
}