import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {base44} from '@/api/base44Client';
import {Button} from '@/components/ui/button';
import RelationshipStrength from '@/components/relationships/RelationshipStrength';
export default function OpportunityPeople({item,account,contacts,canEdit,onSave,busy}){
 const person=contacts.find(p=>p.id===item.contact_id),[editing,setEditing]=useState(false),[selected,setSelected]=useState(item.contact_id || '');
 const query=useQuery({queryKey:['opportunity-primary-person',person?.id],enabled:!!person,queryFn:async()=>{const [p,a,c]=await Promise.all([base44.entities.ContactProfile.filter({contact_id:person.id},{limit:1}),base44.entities.CRMActivity.filter({contact_id:person.id},{sort:'-occurred_at',limit:1}),base44.entities.Conversation.filter({contact_id:person.id},{sort:'-occurred_at',limit:1})]);return {profile:p.items[0],last:[a.items[0]?.occurred_at,c.items[0]?.occurred_at].filter(Boolean).sort().at(-1)};}});
 return <section className="rounded-xl border border-border bg-card p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">People</h2>{canEdit && <Button size="sm" variant="outline" onClick={()=>setEditing(v=>!v)}>{person ? 'Change primary person' : 'Link primary person'}</Button>}</div>{person ? <div className="mt-5 flex flex-wrap items-start gap-5 rounded-lg border border-border p-4"><div className="min-w-48"><Link className="font-semibold hover:text-primary" to={`/people/${person.id}`}>{person.full_name}</Link><p className="mt-1 text-xs text-muted-foreground">{person.job_title || 'Job title not recorded'}</p><Link className="mt-1 block text-xs hover:underline" to={`/accounts/${account.id}`}>{person.company_name || account.name}</Link></div><div><p className="text-xs text-muted-foreground">Opportunity role</p><p className="mt-1 text-sm">Primary person</p></div><div><p className="mb-1 text-xs text-muted-foreground">Relationship</p><RelationshipStrength profile={query.data?.profile} last={query.data?.last}/></div><div><p className="text-xs text-muted-foreground">Last interaction</p><p className="mt-1 text-xs">{query.isPending ? 'Loading…' : query.data?.last ? new Date(query.data.last).toLocaleDateString('en-GB') : 'Not recorded'}</p></div>{canEdit && <Button className="ml-auto" size="sm" variant="ghost" disabled={busy} onClick={()=>onSave({contact_id:''})}>Remove from opportunity</Button>}</div> : <p className="mt-5 text-sm text-muted-foreground">Link an existing person so the opportunity and relationship remain connected.</p>}{editing && <form className="mt-4 flex flex-wrap gap-2" onSubmit={async e=>{e.preventDefault();if(await onSave({contact_id:selected}))setEditing(false);}}><select aria-label="Primary person" required value={selected} onChange={e=>setSelected(e.target.value)} className="rounded-lg border border-input bg-background p-2 text-sm"><option value="">Select a person at this organisation</option>{contacts.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select><Button size="sm" disabled={busy}>Save link</Button></form>}</section>;
}