export const pathwayHelpArticles = [
  { title: '01 · Scope — opportunity and scoping', intro: 'Define the client need and proposed project before developing the delivery plan.', steps: ['Record the scope summary, client objectives, funding route, constraints and key stakeholders.', 'Record feasibility and the site visit, and capture the next action.'], note: 'Live completion uses recorded scoping indicators. Feasibility marked complete can set this stage to 100% even when the site visit remains outstanding; always read the individual checks.' },
  { title: '02 · Fee — fee proposal', intro: 'Establish services, fees and engagement terms.', steps: ['Review the current fee proposal, services included / excluded and delivery-team fees.', 'Record the proposal status and client acceptance when confirmed.'], note: 'The live stage checks for a current fee proposal and acceptance of that proposal. A prepared or sent proposal is not accepted.' },
  { title: '03 · Prepare — pre-construction', intro: 'Bring together the commercial, legal and procurement foundations.', steps: ['Review the access agreement, accepted fee proposal and required appointments.', 'Check the contractor appointment, applicable development agreement, contractor identity and relevant RIBA completion evidence.', 'Use the individual readiness checks and source documents to identify outstanding records.'], note: 'Required checks vary with the applicable agreement route. An architect appointment is optional in the current readiness calculation.' },
  { title: '04 · Design — design and consultant team', intro: 'Coordinate design activity and the appointed team through design development.', steps: ['Review the PM, Principal Designer CDM and Principal Designer Building Regulations appointments.', 'Review the contractor appointment / purchase-order evidence or executed JCT, and coordinate design information and reviews.'], note: 'Live stage readiness is based on the recorded appointment and contractor checks; it is not an automatic certification that all RIBA design work is complete.' },
  { title: '05 · Programme — dates and milestones', intro: 'Maintain the programme and its key dependencies.', steps: ['Review recorded stage dates, agreement milestones and construction / completion dates.', 'Keep the relevant source dates current and check the milestone evidence shown in Pathway.'], note: 'The Pathway uses recorded programme milestones. A date in the programme is not proof that the underlying activity has been completed.' },
  { title: '06 · Act — action register', intro: 'Maintain the shared log of work to be done.', steps: ['Record each action with an owner, priority and due date.', 'Update progress, comments and completion status as the action is resolved.'], note: 'Use the action register and its explanation rather than treating this ongoing log as a one-off approval gateway.' },
  { title: '07 · Decide — decision register', intro: 'Keep a traceable record of project decisions and their effects.', steps: ['Record the decision request, decision maker, required date and supporting document.', 'Record the agreed decision, agreed date, financial adjustment and programme impact.'], note: 'Only agreed financial adjustments feed the valuation contract adjustment. An open request is not an agreed decision.' },
  { title: '08 · De-risk — risk register', intro: 'Record exposure, mitigation and stakeholder review.', steps: ['Identify risks, assess probability and impact, record owners and mitigation, and maintain the live risk status.', 'Use the approval panel to issue locked versions for verified stakeholder acceptance and review row-level feedback.', 'Check approval applicability after changing live risks.'], note: 'Risk status, register completion and verified acceptance are distinct. Read the current progress explanation and approval status rather than assuming that acceptance closes every risk.' },
  { title: '09 · Build — construction', intro: 'Track contract delivery, progress, valuations and completion.', steps: ['Maintain contractor, contract dates, progress percentages, site issues and meeting information.', 'Review valuations, changes, programme forecasts and practical completion evidence.'], note: 'Saved programme completion is limited to 0–99% until practical completion is recorded; practical completion sets the construction stage to 100%.' },
  { title: '10 · Handover — practical completion and close-out', intro: 'Bring together completion evidence and the information needed for operation.', steps: ['Review practical completion, final accounts, O&M manuals, health and safety information, warranties, training, assets and client handover.', 'Maintain the handover pack, applicability decisions and evidence; record lessons learned.'], note: 'Pathway close-out checks and handover-pack completeness are separate measures. Neither replaces competent contractual or statutory assessment.' },
];