import { makeSourceFact } from './aseSourceCommon.ts';
export function accountsEvidence(account,number,refresh,periods) {
  const facts=[];
  const add=(period,slug,data)=>{
    const pdf=period.origin==='pdf',needed={strength:['net_assets','assets','current_assets','fixed_assets'],liquidity:['current_assets','current_liabilities'],debt:['borrowings','cash','assets','current_assets','fixed_assets'],trend:['revenue']}[slug] || [slug];
    const citations=pdf ? Object.entries(period.metrics).filter(([key])=>needed.includes(key)).map(([key,row])=>`${key} p.${row.page} (units ×${row.multiplier}): ${row.quote.slice(0,170)}`).join('; ').slice(0,650) : '';
    facts.push(makeSourceFact(account,'accounts',number,refresh,`${period.end}-${slug}`,{source_reference:period.source_url,source_date:period.filed_at,reporting_period:period.end,evidence_type:'financial',currency:'GBP',...data,confidence:pdf ? 'Low' : 'High',notes:pdf ? `ALICE PDF extraction: provisional, not independently verified. Company ${number}; GBP; ${period.end}. ${citations}. ${data.notes}` : data.notes}));
  };
  for(const period of periods) {
    const m=period.metrics,value=key=>m[key]?.value,defined=key=>Number.isFinite(value(key));
    for(const [key,row] of Object.entries(m).filter(([key])=>key!=='fixed_assets' || !defined('assets'))) add(period,key,{component:'filed_financials',title:`Filed ${key.replaceAll('_',' ')} · ${period.end}`,value:key==='employees' ? String(row.value) : `GBP ${row.value}`,notes:`Primary Companies House tagged accounts. Concept ${row.concept}; company ${number}; ${row.start ? 'period '+row.start+' to '+row.end : 'balance at '+row.end}. Non-dimensional matching entity context only. Missing or conflicting facts are excluded. Automatic validation checks entity, currency, dates and supported definitions.`,...(row.annual ? {period_months:12} : {})});
    const assets=defined('assets') ? value('assets') : defined('current_assets') && defined('fixed_assets') ? value('current_assets')+value('fixed_assets') : null;
    if(assets>0 && defined('net_assets')) add(period,'strength',{component:'financial_strength',title:`Filed financial strength candidate · ${period.end}`,value:String(100*value('net_assets')/assets),notes:`Net assets ${value('net_assets')} / total assets ${assets} × 100. Deterministic calculation from tagged accounts. Automatically validated only for supported, unambiguous tagged definitions.`});
    if(defined('current_assets') && value('current_assets')>=0 && defined('current_liabilities') && value('current_liabilities')>0) add(period,'liquidity',{component:'liquidity',title:`Filed liquidity candidate · ${period.end}`,value:String(value('current_assets')/value('current_liabilities')),notes:`Current assets ${value('current_assets')} / current liabilities ${value('current_liabilities')}. Automatic validation retains only the supported current-liability definition.`});
    if(assets>0 && defined('borrowings') && value('borrowings')>=0 && defined('cash') && value('cash')>=0) add(period,'debt',{component:'debt',title:`Filed net-debt candidate · ${period.end}`,value:String(100*(value('borrowings')-value('cash'))/assets),notes:`(Borrowings ${value('borrowings')} minus cash ${value('cash')}) / assets ${assets} × 100. Automatic scoring requires the explicit TotalBorrowings concept; generic borrowings remain context. Creditors are never substituted for borrowings.`});
    const previous=periods.find(row=>Number(row.end.slice(0,4))===Number(period.end.slice(0,4))-1 && row.end.slice(5)===period.end.slice(5));
    if(m.revenue?.annual && previous?.metrics.revenue?.annual && previous.metrics.revenue.value>0) add(period,'trend',{component:'financial_trend',title:`Filed revenue trend candidate · ${period.end}`,value:String(100*(value('revenue')/previous.metrics.revenue.value-1)),period_months:12,previous_value:String(previous.metrics.revenue.value),notes:`Annual GBP revenue ${value('revenue')} versus ${previous.metrics.revenue.value} for ${previous.end}; percentage change. Automatic validation requires comparable annual GBP periods; ambiguous or conflicting facts are excluded.`});
  }
  return facts;
}