import { sourceJson,makeSourceFact } from './aseSourceCommon.ts';
export async function retrieveBlackflag(account,number,refresh) {
  if(!/^\d{8}$/.test(number)) throw new Error('Blackflag public coverage is England and Wales numeric company numbers only.');
  // This is the same unauthenticated, public data request made by the permitted company page, not the key-restricted v2 API.
  const raw=await sourceJson(`https://blackflagalert.com/api/v1/company/${number}`);
  if(raw.company?.company_number!==number) throw new Error('Blackflag company-number match failed.');
  const company=raw.company,score=raw.latest_score || {},url=`https://blackflagalert.com/company?company=${number}`,facts=[],today=refresh.refreshed_at.slice(0,10);
  const add=(slug,data)=>facts.push(makeSourceFact(account,'blackflag',number,refresh,slug,{source_reference:url,...data}));
  const validDate=date=>typeof date==='string' && /^\d{4}-\d{2}-\d{2}$/.test(date) && Date.parse(date)<=Date.now();
  const finite=value=>typeof value==='number' && Number.isFinite(value);
  const financials=(Array.isArray(raw.financials) ? raw.financials : []).filter(row=>validDate(row.period_end_date)).sort((a,b)=>b.period_end_date.localeCompare(a.period_end_date)).slice(0,3);
  add('external-score',{component:'external_risk_score',title:'Blackflag proprietary R-Score (not ASE)',value:finite(score.r_score) ? `${score.r_score}/100 · ${score.risk_label || 'Band not provided'}` : 'Not available',reporting_period:validDate(score.period_end_date) ? score.period_end_date : today,notes:'Third-party score is contextual only. It is never converted to an ASE rating or component score.'});
  add('court-check',{component:'court_records',title:'County Court Judgment check',value:company.court_record_status==='pending' || company.ccj_count==null ? 'Unknown / pending' : `${company.ccj_count} reported CCJs; status ${company.court_record_status || 'not specified'}`,notes:'Pending or missing court records are not a clean check. Confirm currency, identity, materiality and resolution before classifying an adverse event.'});
  add('vat-reported',{component:'vat_reported',title:'VAT number reported by Blackflag (not a live HMRC check)',value:raw.vat?.vat_number || 'Not provided',evidence_type:'compliance',notes:'Save and confirm the VAT identifier before running the separate live HMRC check. A third-party VAT claim is not a fresh HMRC verification.'});
  for(const row of financials) {
    const period=row.period_end_date,base={reporting_period:period,evidence_type:'financial',currency:'GBP',source_date:today};
    const values=['turnover','operating_profit','net_assets','total_current_assets','total_fixed_assets','creditors_within_1yr','total_borrowings','cash'].filter(key=>finite(row[key])).map(key=>`${key}: GBP ${row[key]}`).join('; ');
    add(`financials-${period}`,{...base,component:'filed_financials',title:`Blackflag filed financial facts · ${period}`,value:'Financial figures retrieved',notes:values+'; Accounts period start: '+(row.period_start_date || 'unknown')+'. Third-party extraction must be checked against filed accounts.'});
    const assets=finite(row.total_current_assets) && finite(row.total_fixed_assets) ? row.total_current_assets+row.total_fixed_assets : null;
    if(assets>0 && finite(row.net_assets)) add(`strength-${period}`,{...base,component:'financial_strength',title:`Financial strength candidate · ${period}`,value:(100*row.net_assets/assets).toFixed(6),notes:`Derived deterministically: net assets ${row.net_assets} / total assets (${row.total_current_assets} + ${row.total_fixed_assets}) × 100. Requires administrator source review before scoring.`});
    if(finite(row.total_current_assets) && finite(row.creditors_within_1yr) && row.creditors_within_1yr>0) add(`liquidity-${period}`,{...base,component:'liquidity',title:`Liquidity candidate · ${period}`,value:(row.total_current_assets/row.creditors_within_1yr).toFixed(6),notes:`Derived deterministically: current assets ${row.total_current_assets} / creditors within one year ${row.creditors_within_1yr}. This may differ from Blackflag’s displayed ratio; verify the filed definitions before approval.`});
  }
  for(const [index,debtor] of (raw.distressed_debtors || []).slice(0,3).entries()) add(`debtor-${index}`,{component:'distressed_debtor',title:'Reported exposure to distressed debtor',value:`${debtor.debtor_company_name || 'Unnamed debtor'} · ${finite(debtor.amount_owed) ? 'GBP '+debtor.amount_owed : 'Amount unknown'}`,notes:`Statement-of-affairs evidence: ${debtor.debtor_company_number || 'unknown company'}; filed ${debtor.filing_date || 'unknown'}. Not proof of a current unrecovered balance or insolvency of this Account.`,severity:'moderate'});
  return {facts,raw,summary:{company_number:number,company_name:company.company_name,external_score:score.r_score ?? null,risk_label:score.risk_label || null,court_status:company.court_record_status || 'unknown',financial_periods:financials.map(row=>row.period_end_date),reported_vat:raw.vat?.vat_number || null},warnings:['Public-page data is secondary evidence. Candidates require source review; no automatic ASE score is imported.','Missing accounting-period starts prevent automatic comparable annual revenue-growth scoring.']};
}