import {accountModel} from './asePolicy.ts';
import {commercialTurnover,hmrcStatus} from './aseCommercialTurnover.ts';
import {commercialContractExposure} from './aseCommercialExposure.ts';
export async function commercialInsight(base44,account,options={}) {
  const now=options.at ? new Date(options.at) : new Date(),date=now.toISOString().slice(0,10);
  if(accountModel(account)!=='company') return {status:'not_applicable',reason:'Turnover concentration applies to supported company accounts, not local-authority spending.',checked_at:now.toISOString()};
  const [turnover,exposure]=await Promise.all([commercialTurnover(base44,account,now),commercialContractExposure(base44,account,date)]);
  if(exposure.reason==='Contract totals exceed the validation limit.') return {status:'unavailable',reason:exposure.reason,turnover,percentage:null,annualised_value:null,checked_at:now.toISOString()};
  const {eligible,duplicateRefs}=exposure;
  const [allCount,contracts,hmrc]=await Promise.all([
    exposure.candidate_count,
    base44.entities.JCT.filter(eligible,{limit:20,...(options.cursor ? {cursor:options.cursor} : {}),fields:['document_id','project_id','commercial_reviewed_at','commercial_reviewed_by','commercial_effective_value','commercial_effective_start','commercial_effective_end','commercial_effective_annual_value','commercial_effective_reference','commercial_effective_date_basis','commercial_effective_mode','commercial_effective_source']}),hmrcStatus(base44,account)
  ]);
  const included=exposure.included_count,annual=exposure.annualised_value,excluded=allCount-included;
  const programmeCount=exposure.programme_proxy_count,proposalCount=exposure.proposal_proxy_count;
  const comparison=turnover.status==='available' ? turnover : turnover.balance_sheet_proxy || turnover;
  const proxy=comparison.basis==='balance_sheet_total';
  const available=included>0 && comparison.status==='available' && Number.isFinite(annual);
  const warnings=[...(exposure.warnings || [])];
  if(comparison.limitation) warnings.push(comparison.limitation);
   if(proposalCount) warnings.push(`${proposalCount} included contract(s) use the current Pathway fee proposal's company-matched contractor build-up including OHP, excluding VAT, ALS and other direct suppliers' fees. These are proposal estimates, not verified signed-contract income.`);
  if(programmeCount) warnings.push(`${programmeCount} included contract(s) use a recorded project programme as a date proxy, not confirmed contract dates; the comparison is estimated. Saved programme changes refresh Pathway estimates; reviewed signed terms remain fixed until reviewed again.`);
  if(excluded) warnings.push(`${excluded} accessible signed contract / appointment record(s) excluded: missing company-specific fees or complete programme dates, outside the current term, or duplicate reference.`);
  if(duplicateRefs.length) warnings.push('All records sharing a duplicate signed-contract reference are excluded, not double counted.');
  if(contracts.has_more && options.snapshot) warnings.push('This historical context retains the first 20 contract inputs; the aggregate includes all eligible accessible contracts.');
  const supplier=account.account_type==='supplier' || account.relationship_types?.some(type=>['supplier','contractor','consultant'].includes(type));
  if(!supplier) warnings.push('Only contractor-side JCT links count as this company’s income. Client-side project expenditure, unsigned appointments and purchase orders are not treated as verified company income.');
  return {version:'commercial-concentration-v1',status:available ? excluded ? 'incomplete' : 'available' : 'unavailable',comparison_basis:proxy ? 'balance_sheet_total' : 'turnover',comparison_note:proxy ? comparison.limitation : null,comparison_denominator:comparison,percentage:available ? annual/comparison.value*100 : null,annualised_value:annual,included_count:included,programme_proxy_count:programmeCount,proposal_proxy_count:proposalCount,estimated:proxy || proposalCount>0 || programmeCount>0 || turnover.annual_verified===false,excluded_count:excluded,candidate_count:allCount,turnover,hmrc,contracts:[...contracts.items,...(exposure.appointment_contracts || [])].map(row=>({...row,commercial_value:row.commercial_effective_value,commercial_start:row.commercial_effective_start,commercial_end:row.commercial_effective_end,commercial_annual_value:row.commercial_effective_annual_value,commercial_reference:row.commercial_effective_reference,commercial_date_basis:row.commercial_effective_date_basis,commercial_date_source:row.commercial_effective_source?.date_source,value_source:row.commercial_effective_source?.source,value_basis:row.commercial_effective_mode,project_name:row.commercial_effective_source?.project_name,project_record_id:row.commercial_effective_source?.project_id,fee_proposal_id:row.commercial_effective_source?.proposal_id,fee_proposal_revision:row.commercial_effective_source?.revision,fee_proposal_status:row.commercial_effective_source?.status})), ...(!options.snapshot ? {has_more:contracts.has_more,next_cursor:contracts.next_cursor} : {}),checked_at:now.toISOString(),warnings,
    reason:available ? proxy ? comparison.limitation : 'Indicative current annualised contract value compared with historical annual turnover. Not realised income or a time-matched market-share measure.' : !included ? exposure.reason+(exposure.appointment_count ? ` ${exposure.appointment_count} signed professional appointment(s) are linked to this company; the excluded fee and programme inputs are explained below.` : '') : turnover.reason,
    method:(proxy ? comparison.limitation+' '+comparison.derivation+'. ' : '')+'Signed professional appointments are included alongside contractor-side JCT contracts. Use recorded company-specific appointment fees, or an unambiguous company-and-role matched current Pathway proposal, with complete project programme dates explicitly labelled as estimates; exclude overlapping same-project, same-role appointments. Each included company-specific GBP value × 365.25 ÷ inclusive term days. Reviewed signed terms take priority; otherwise use the current Pathway fee proposal’s contractor build-up matched by company number, including OHP but excluding VAT, ALS fees and other direct suppliers’ fees, with the recorded project programme. Pathway proposals are explicitly labelled estimates and refreshed from saved Pathway inputs. Confirmed contract dates take priority; where unknown, reviewed project programme dates are retained as an explicitly labelled estimate. Where neither date pair is available, exclude the contract rather than assume a duration; aggregate active signed contractor-side contracts and professional appointments once, then divide by '+(proxy ? 'the company-specific filed GBP balance-sheet total (net assets: total assets minus all liabilities)' : 'the latest company-specific Companies House filed GBP turnover')+' × 100. Current contract activity is not aligned to the historical turnover year. Turnover older than 913 days (approximately 30 months) is excluded. Group turnover and generic project budgets are not substituted. Company-only annual turnover extracted from a Companies House PDF is usable only with its page citation and is explicitly Low confidence, not independently verified. Missing evidence never means zero business or low dependence. '+(proxy ? 'This net-assets proxy remains excluded from turnover-based ASE scoring.' : 'Future company ASE assessments score this comparison using the approved commercial-concentration weighting and thresholds.')+' Estimated or incomplete comparisons produce Low-confidence evidence and Low overall confidence. Missing comparisons remain unscored; previously published ratings are unchanged.'};
}