import {accountModel} from './asePolicy.ts';
import {commercialTurnover,hmrcStatus} from './aseCommercialTurnover.ts';
import {commercialContractExposure} from './aseCommercialExposure.ts';
export async function commercialInsight(base44,account,options={}) {
  const now=options.at ? new Date(options.at) : new Date(),date=now.toISOString().slice(0,10);
  if(accountModel(account)!=='company') return {status:'not_applicable',reason:'Turnover concentration applies to supported company accounts, not local-authority spending.',checked_at:now.toISOString()};
  const [turnover,exposure]=await Promise.all([commercialTurnover(base44,account,now),commercialContractExposure(base44,account,date)]);
  if(exposure.reason==='Contract totals exceed the validation limit.') return {status:'unavailable',reason:exposure.reason,turnover,percentage:null,annualised_value:null,checked_at:now.toISOString()};
  const {eligible,duplicateRefs}=exposure;
  const [allCount,contracts,hmrc]=await Promise.all([
    exposure.candidate_count,
    base44.entities.JCT.filter(eligible,{limit:20,...(options.cursor ? {cursor:options.cursor} : {}),fields:['document_id','project_id','commercial_reviewed_at','commercial_reviewed_by','commercial_effective_value','commercial_effective_start','commercial_effective_end','commercial_effective_annual_value','commercial_effective_reference','commercial_effective_date_basis','commercial_effective_mode','commercial_effective_source']}),hmrcStatus(base44,account)
  ]);
  const included=exposure.included_count,annual=exposure.annualised_value,excluded=allCount-included;
  const programmeCount=exposure.programme_proxy_count,proposalCount=exposure.proposal_proxy_count;
  const available=included>0 && turnover.status==='available' && Number.isFinite(annual);
  const warnings=[];
  if(turnover.limitation) warnings.push(turnover.limitation);
   if(proposalCount) warnings.push(`${proposalCount} included contract(s) use the current Pathway fee proposal's company-matched contractor build-up including OHP, excluding VAT, ALS and other direct suppliers' fees. These are proposal estimates, not verified signed-contract income.`);
  if(programmeCount) warnings.push(`${programmeCount} included contract(s) use a recorded project programme as a date proxy, not confirmed contract dates; the comparison is estimated. Saved programme changes refresh Pathway estimates; reviewed signed terms remain fixed until reviewed again.`);
  if(excluded) warnings.push(`${excluded} accessible signed contract record(s) excluded: no usable company-matched Pathway proposal and programme or reviewed terms, outside the current term, or duplicate reference.`);
  if(duplicateRefs.length) warnings.push('All records sharing a duplicate signed-contract reference are excluded, not double counted.');
  if(contracts.has_more && options.snapshot) warnings.push('This historical context retains the first 20 contract inputs; the aggregate includes all eligible accessible contracts.');
  const supplier=account.account_type==='supplier' || account.relationship_types?.some(type=>['supplier','contractor','consultant'].includes(type));
  if(!supplier) warnings.push('Only contractor-side JCT links count as this company’s income. Client-side project expenditure, unsigned appointments and purchase orders are not treated as verified company income.');
  return {version:'commercial-concentration-v1',status:available ? excluded ? 'incomplete' : 'available' : 'unavailable',percentage:available ? annual/turnover.value*100 : null,annualised_value:annual,included_count:included,programme_proxy_count:programmeCount,proposal_proxy_count:proposalCount,estimated:proposalCount>0 || programmeCount>0 || turnover.annual_verified===false,excluded_count:excluded,candidate_count:allCount,turnover,hmrc,contracts:contracts.items.map(row=>({...row,commercial_value:row.commercial_effective_value,commercial_start:row.commercial_effective_start,commercial_end:row.commercial_effective_end,commercial_annual_value:row.commercial_effective_annual_value,commercial_reference:row.commercial_effective_reference,commercial_date_basis:row.commercial_effective_date_basis,commercial_date_source:row.commercial_effective_source?.date_source,value_source:row.commercial_effective_source?.source,value_basis:row.commercial_effective_mode,project_name:row.commercial_effective_source?.project_name,project_record_id:row.commercial_effective_source?.project_id,fee_proposal_id:row.commercial_effective_source?.proposal_id,fee_proposal_revision:row.commercial_effective_source?.revision,fee_proposal_status:row.commercial_effective_source?.status})), ...(!options.snapshot ? {has_more:contracts.has_more,next_cursor:contracts.next_cursor} : {}),checked_at:now.toISOString(),warnings,
    reason:available ? 'Indicative current annualised contract value compared with historical annual turnover. Not realised income or a time-matched market-share measure.' : !included ? 'No signed contracts currently have usable company-matched Pathway fee proposal values and current programme dates, or reviewed signed-contract terms. Record the missing proposal or programme inputs in the Pathway; this is not zero concentration.' : turnover.reason,
    method:'Each included company-specific GBP value × 365.25 ÷ inclusive term days. Reviewed signed terms take priority; otherwise use the current Pathway fee proposal’s contractor build-up matched by company number, including OHP but excluding VAT, ALS fees and other direct suppliers’ fees, with the recorded project programme. Pathway proposals are explicitly labelled estimates and refreshed from saved Pathway inputs. Confirmed contract dates take priority; where unknown, reviewed project programme dates are retained as an explicitly labelled estimate. Where neither date pair is available, exclude the contract rather than assume a duration; aggregate active signed contractor-side contracts once, then divide by the latest company-specific Companies House filed GBP turnover × 100. Current contract activity is not aligned to the historical turnover year. Turnover older than 913 days (approximately 30 months) is excluded. Group turnover and generic project budgets are not substituted. Company-only annual turnover extracted from a Companies House PDF is usable only with its page citation and is explicitly Low confidence, not independently verified. Missing evidence never means zero business or low dependence. Future company ASE assessments score this comparison using the approved commercial-concentration weighting and thresholds. Estimated or incomplete comparisons produce Low-confidence evidence and Low overall confidence. Missing comparisons remain unscored; previously published ratings are unchanged.'};
}