export async function saveLeadershipReview(db,account,input,user,policy) {
  const page=await db.ASELeadershipRun.filter({account_id:account.id},{sort:'-created_date',limit:1}),run=page.items[0],subject=run?.subjects?.find(s=>s.key===input.personKey && s.current);if(!subject) throw new Error('Choose a current person or entity from the latest screening roster.');
  if(!['disqualification','sanctions','individual_insolvency'].includes(input.source) || !['CLEAR','ADVERSE','HISTORIC','CONFIRMED MATCH','MANUAL REVIEW'].includes(input.state) || input.confirmed!==true || typeof input.reference!=='string' || !input.reference.trim() || input.reference.length>500 || typeof input.note!=='string' || input.note.length<10 || input.note.length>600) throw new Error('Provide verified source reference, matching basis and a factual review note.');
  if(input.source==='individual_insolvency' && subject.entity) throw new Error('Personal insolvency applies only to natural persons.');
  const allowed=['birth_date','address','nationality','registration_number','person_number','company_relationship'],identifiers=Array.isArray(input.identifiers) ? [...new Set(input.identifiers)] : [];
  if(identifiers.some(k=>!allowed.includes(k)) || input.state!=='MANUAL REVIEW' && (identifiers.length<2 || !identifiers.some(k=>['birth_date','address','registration_number','person_number'].includes(k)))) throw new Error('Name-only matching is insufficient. Verify two corroborating identifiers including birth date, address or an official identifier.');
  const existing=run.checks.find(c=>c.person_key===subject.key && c.source===input.source),candidate=existing?.candidates?.find(c=>c.evidence_key===input.evidenceKey);
  if(input.source!=='individual_insolvency' && !candidate) throw new Error('Select an actual official-source candidate from the current screening.');
  if(input.source==='sanctions' && !['CLEAR','CONFIRMED MATCH','MANUAL REVIEW'].includes(input.state)) throw new Error('Sanctions require a confirmed, dismissed or unresolved match decision.');
  const today=new Date().toISOString().slice(0,10),validDate=d=>typeof d==='string' && /^\d{4}-\d{2}-\d{2}$/.test(d) && Number.isFinite(Date.parse(d));
  if(input.source==='individual_insolvency' && ['ADVERSE','HISTORIC'].includes(input.state) && (!validDate(input.start) || input.start>today || input.state==='HISTORIC' && (!validDate(input.end) || input.end>=today))) throw new Error('Provide valid operative dates for the verified individual insolvency event.');
  const saved=await db.ASELeadershipReview.create({account_id:account.id,person_key:subject.key,source:input.source,evidence_key:candidate?.evidence_key || 'individual-insolvency:'+input.reference.trim(),evidence_reference:input.reference.trim(),state:input.state,matching_identifiers:identifiers,reviewed_by:user.id,reviewed_at:new Date().toISOString(),event_start:input.start || '',event_end:input.end || '',verified:input.state!=='MANUAL REVIEW',note:input.note});return {id:saved.id,state:saved.state};
}
export function applyLeadershipReviews(checks,reviews,policy) {
  return checks.map(original=>{const check=structuredClone(original),fresh=reviews.filter(r=>r.person_key===check.person_key && r.source===check.source && Date.now()-Date.parse(r.reviewed_at)<policy.manual_freshness_days*86400000);
    if(check.source==='individual_insolvency') {const r=fresh[0];if(r) Object.assign(check,{match_status:r.state==='ADVERSE' && r.event_end && r.event_end<new Date().toISOString().slice(0,10) ? 'HISTORIC' : r.state,matching_confidence:r.verified ? 'High' : 'Low',human_review:true,reviewed_by:r.reviewed_by,reviewed_at:r.reviewed_at,evidence_reference:r.evidence_reference,evidence_key:r.evidence_key,reason:'Verified manual Individual Insolvency Register evidence; governance relevance only, not evidence of company financial distress.',event_end:r.event_end});return check;}
    if(check.candidates) {check.candidates=check.candidates.map(candidate=>{const r=fresh.find(r=>r.evidence_key===candidate.evidence_key);if(!r) return candidate;return {...candidate,match_status:r.state==='CLEAR' ? 'NO MATCH' : r.state,matching_confidence:r.verified ? 'High' : 'Low',human_review:true,reviewed_by:r.reviewed_by,reviewed_at:r.reviewed_at,matching_basis:r.matching_identifiers,evidence_reference:r.evidence_reference};});const statuses=check.candidates.map(c=>c.match_status);check.match_status=statuses.includes('CONFIRMED MATCH') ? 'CONFIRMED MATCH' : statuses.includes('ADVERSE') ? 'ADVERSE' : statuses.some(s=>['POTENTIAL MATCH','MANUAL REVIEW'].includes(s)) ? 'MANUAL REVIEW' : statuses.includes('HISTORIC') ? 'HISTORIC' : 'CLEAR';check.human_review=check.candidates.some(c=>c.human_review);check.matching_confidence=['CLEAR','ADVERSE','HISTORIC','CONFIRMED MATCH'].includes(check.match_status) ? 'High' : 'Low';}
    return check;});
}