import {readSourceResponse} from './aseSourceCommon.ts';
import {possibleName,compareLeadershipIdentity,leadershipAudit} from './aseLeadershipIdentity.ts';
export const sanctionsXMLURL='https://sanctionslist.fcdo.gov.uk/docs/UK-Sanctions-List.xml';
let cache=null;
const decode=value=>String(value).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'");
const values=(xml,tag)=>[...xml.matchAll(new RegExp('<'+tag+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+tag+'>','g'))].map(m=>decode(m[1].replace(/<[^>]+>/g,'').trim()));
export function parseUKSanctions(xml) {
  if(/<!DOCTYPE|<!ENTITY/i.test(xml) || !xml.includes('</Designations>')) throw new Error('Unrecognised official sanctions format.');
  const blocks=[...xml.matchAll(/<Designation>([\s\S]*?)<\/Designation>/g)];if(!blocks.length) throw new Error('No sanctions designations parsed; clearance not inferred.');
  const generated=values(xml,'DateGenerated')[0];if(!/^\d{2}\/\d{2}\/\d{4}$/.test(generated || '')) throw new Error('Official sanctions publication date is unavailable.');
  const date=generated.split('/').reverse().join('-');if(Date.parse(date)>Date.now() || Date.now()-Date.parse(date)>30*86400000) throw new Error('Official sanctions publication is stale or future-dated.');
  const entries=blocks.map(([_,x])=>({id:values(x,'UniqueID')[0],kind:values(x,'IndividualEntityShip')[0],names:[...x.matchAll(/<Name>([\s\S]*?)<\/Name>/g)].map(m=>[1,2,3,4,5,6].map(i=>values(m[1],'Name'+i)[0] || '').filter(Boolean).join(' ')),births:values(x,'DOB').map(d=>{const parts=d.split('/');return {birth_year:/^\d{4}$/.test(parts[2] || '') ? Number(parts[2]) : null,birth_month:/^\d{2}$/.test(parts[1] || '') ? Number(parts[1]) : null};}),registration_numbers:[...values(x,'BusinessRegistrationNumber'),...values(x,'RegistrationNumber')],nationalities:values(x,'Nationality'),countries:values(x,'AddressCountry'),material:values(x,'AssetFreeze')[0]==='true' || values(x,'DirectorDisqualificationSanction')[0]==='true'}));
  if(entries.some(e=>!e.id || !e.names.length || !['Individual','Entity','Ship'].includes(e.kind))) throw new Error('Incomplete sanctions identity fields; no clearance inferred.');return {entries,date};
}
export async function officialSanctions() {if(cache && cache.expires>Date.now()) return cache.data;const response=await fetch(sanctionsXMLURL,{redirect:'manual',signal:AbortSignal.timeout(20000)});const stored=await readSourceResponse(response,30000000);if(!response.ok) throw new Error('Official sanctions download failed ('+response.status+').');const data=parseUKSanctions(stored.text);data.sha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',stored.bytes))).map(v=>v.toString(16).padStart(2,'0')).join('');cache={data,expires:Date.now()+300000};return data;}
export function screenLeadershipSanctions(subject,data) {
  const matches=[];
  for(const entry of data.entries) {if(subject.entity ? entry.kind!=='Entity' : entry.kind!=='Individual') continue;for(const name of entry.names) {if(!possibleName(subject.name,name)) continue;const candidates=entry.births.length ? entry.births.map(b=>({name,...b})) : [{name}];let match=candidates.map(c=>compareLeadershipIdentity(subject,{...c,registration_number:entry.registration_numbers.find(n=>n===subject.registration_number)})).find(c=>c.status==='CONFIRMED MATCH');if(!match) match=candidates.map(c=>compareLeadershipIdentity(subject,c)).find(c=>c.status!=='NO MATCH');if(match) {matches.push({id:entry.id,evidence_key:'sanctions:'+entry.id,match_status:match.status,matching_confidence:match.confidence,matching_basis:match.basis,material:entry.material,evidence_reference:'https://search-uk-sanctions-list.service.gov.uk/',list_date:data.date,list_sha256:data.sha256});break;}}}
  const state=matches.some(m=>m.match_status==='CONFIRMED MATCH') ? 'CONFIRMED MATCH' : matches.length ? 'POTENTIAL MATCH' : 'CLEAR';
  return leadershipAudit(subject,'sanctions',state,state==='CLEAR' ? 'No relevant match identified in the downloaded official UK Sanctions List using available identity fields; this is a dated check, not a guarantee.' : 'Official-list candidate identified. Name-only or uncertain matches are never scored as adverse.',{matching_confidence:state==='CLEAR' || state==='CONFIRMED MATCH' ? 'High' : 'Low',evidence_reference:sanctionsXMLURL,list_date:data.date,list_sha256:data.sha256,candidates:matches.slice(0,20)});
}