import {normaliseCompanyNumber} from './companiesHouseData.ts';
import {publicLeadershipSubject} from './aseLeadershipIdentity.ts';
import {applyLeadershipReviews} from './aseLeadershipReviews.ts';
import {leadershipPersonScores,aggregateLeadershipSource} from './aseLeadershipScoring.ts';
import {v2UnavailableCheck} from './aseV2ExternalChecks.ts';
export async function leadershipAssessment(base44,account,configuration,collection) {
  const db=base44.entities,p=configuration.leadership,page=await db.ASELeadershipRun.filter({account_id:account.id,status:'completed'},{sort:'-completed_at',limit:1}),run=page.items[0],registry=collection.sources.registry;
  let number='';try{number=normaliseCompanyNumber(account.company_number);}catch{}
  const fresh=run && run.company_number===number && Date.now()-Date.parse(run.roster_at)<=p.freshness_days*86400000 && (!registry?.audit || registry.audit.refreshed_at<=run.roster_at),current=fresh ? run.subjects.filter(s=>s.current) : [],reviews=fresh ? await db.ASELeadershipReview.filter({account_id:account.id,reviewed_at:{$gte:new Date(Date.now()-p.manual_freshness_days*86400000).toISOString()}},{sort:'-reviewed_at',limit:200}) : {items:[]},audits=fresh ? leadershipPersonScores(applyLeadershipReviews(run.checks.filter(r=>current.some(s=>s.key===r.person_key)),reviews.has_more ? [] : reviews.items,p),p) : [];
  const full=fresh && run.roster_complete && run.psc_complete,warnings=fresh ? [...run.warnings,...(reviews.has_more ? ['Manual review evidence exceeds the safe page limit; no partial review decisions applied.'] : [])] : ['Leadership screening is missing, stale or predates the current registry refresh. Run Leadership & Control screening; previous leadership findings are not carried forward as current risks.'];
  const disq=aggregateLeadershipSource(audits,'disqualification','disqualification','Director disqualification',full,p),sanctions=aggregateLeadershipSource(audits,'sanctions','sanctions','Company / officer / PSC sanctions',full,p),personal=aggregateLeadershipSource(audits,'individual_insolvency','individual_insolvency','Officer / PSC personal insolvency',full,p),checks=[sanctions,disq,personal];
  if(disq.state==='ADVERSE' && p.disqualification_cap_enabled && audits.some(c=>c.source==='disqualification' && c.match_status==='ADVERSE')) disq.severe_event='current_director_disqualification';
  if(sanctions.state==='ADVERSE' && audits.some(c=>c.source==='sanctions' && c.candidates?.some(m=>m.match_status==='CONFIRMED MATCH' && m.material))) sanctions.severe_event='confirmed_material_sanctions';
  const histories=audits.filter(c=>c.source==='appointments'),material=histories.filter(c=>(c.failures || []).length>=p.material_failures),materialFacts=new Set(material.flatMap(c=>c.failures.map(f=>f.fact_key))),moderate=histories.filter(c=>c.failures?.filter(f=>!materialFacts.has(f.fact_key)).length>=p.repeated_failures);
  const build=(slot,label,score,reason,component='profile')=>{const c=v2UnavailableCheck(component,slot,label,'Companies House',reason);if(score!==null) Object.assign(c,{score,state:score>=p.profile_score ? 'POSITIVE' : 'ADVERSE',confidence:'High',verified:true,checked_at:run.roster_at,source_reference:'https://find-and-update.company-information.service.gov.uk/company/'+number});return c;};
  const appointment=build('appointment_history','Wider officer appointment history',material.length ? p.profile_score : moderate.length ? p.pattern_moderate_score : full && histories.length && histories.every(h=>h.complete) ? p.profile_score : null,material.length ? 'Repeated material company-failure pattern contributes only to Adverse Events; not penalised a second time here.' : moderate.length ? 'At least two distinct recent, dated insolvency events verified during an officer’s tenure. Single associations and dissolution alone are not penalised.' : 'Appointment-history completeness and objective associations only; no inference about intent or competence.');
  const events=build('leadership_events','Other verified leadership / control events',material.length ? p.pattern_material_score : full && histories.length && histories.every(h=>h.complete) ? p.stable_score : null,material.length ? `${material.length} current officer(s) linked by official officer ID to at least ${p.material_failures} distinct recent company insolvency events during their appointments. This factual pattern contributes once, not to both components.` : 'No material repeated failure pattern identified in complete retrieved appointment evidence.','adverse');events.fact_keys=[...materialFacts];appointment.fact_keys=moderate.flatMap(c=>c.failures.filter(f=>!materialFacts.has(f.fact_key)).map(f=>f.fact_key));checks.push(events,appointment);
  const unresolved=run?.psc_statements?.some(s=>!/no-individual-or-entity-with-signficant-control|no-individual-or-entity-with-significant-control/i.test(s)),ownership=build('ownership','Ownership / PSC stability',full && !unresolved ? p.stable_score-(run.change_counts?.pscs>=p.frequent_psc_changes ? p.change_penalty : 0) : null,full && !unresolved ? `${run.change_counts?.pscs || 0} recent PSC notification/cessation events. Frequent changes produce only a modest configured adjustment; a change is not automatically negative.` : 'Ownership is unresolved, protected, incomplete or not currently screened; confidence is reduced, not an adverse finding.');
  checks.push(ownership,build('officer_stability','Officer stability',full ? p.stable_score-(run.change_counts?.officers>=p.frequent_officer_changes ? p.change_penalty : 0) : null,`${run?.change_counts?.officers || 0} recent appointment/cessation events; no subjective assessment of competence.`),build('group_clarity','Corporate-group / ultimate-control clarity',full && !warnings.length && !unresolved ? p.profile_score : null,'Corporate PSCs and retrieved upstream controllers are recorded as control evidence, not as an assumed parent-company financial guarantee.'),build('company_context','Company age / identity context',registry?.audit?.summary?.date_of_creation ? p.profile_score : null,`Incorporation date: ${registry?.audit?.summary?.date_of_creation || 'unavailable'}. Legal-status adverse events are scored only in the Adverse Events component, not twice.`));
  const adverseKeys=['sanctions','disqualification','individual_insolvency','leadership_events'],profileKeys=['ownership','officer_stability','group_clarity','appointment_history'],integrityRows=checks.filter(c=>[...adverseKeys,...profileKeys].includes(c.slot) && c.score!==null),integrity=integrityRows.length ? integrityRows.reduce((sum,c)=>sum+c.score*configuration.slots[c.component][c.slot],0)/integrityRows.reduce((sum,c)=>sum+configuration.slots[c.component][c.slot],0) : null;
  for(const audit of audits) {const slot=audit.source==='appointments' ? material.some(m=>m.person_key===audit.person_key) ? events : appointment : audit.source==='sanctions' ? sanctions : audit.source==='disqualification' ? disq : personal;audit.score_impact={component:slot.component,slot:slot.slot,individual_score:audit.score,aggregate_score:slot.score,configured_subweight:configuration.slots[slot.component][slot.slot]};}
  const leadership={screening_at:fresh ? run.roster_at : null,run_id:fresh ? run.id : '',subjects:current.map(publicLeadershipSubject),former_officers:fresh ? run.former_officers.map(publicLeadershipSubject) : [],checks:audits,integrity_score:integrity,integrity_note:'Internal sub-score only; feeds Adverse Events & Corporate Stability and Trading & Corporate Profile. Not an eighth ASE component.',warnings,psc_statements:fresh ? run.psc_statements : [],explanation:checks.map(c=>`${c.label}: ${c.score===null ? 'unassessed' : c.score.toFixed(2)+'/5'}. ${c.reason}`).join(' ')};
  return {checks,leadership};
}