import {compareLeadershipIdentity} from './aseLeadershipIdentity.ts';
import {aggregateLeadershipSource,leadershipPersonScores} from './aseLeadershipScoring.ts';
import {aseV2Defaults} from './aseV2Config.ts';
import {calculateASEV2} from './aseV2Calculation.ts';
import {applyLeadershipReviews} from './aseLeadershipReviews.ts';
export function checkLeadershipRules() {
  const p=aseV2Defaults.leadership,subject={name:'Example Person',birth_year:1970,birth_month:2,postcode:'AB1 2CD'},sameName=compareLeadershipIdentity(subject,{name:'Example Person'}),strong=compareLeadershipIdentity(subject,{name:'Example Person',birth_year:1970,birth_month:2,postcode:'AB12CD'}),conflict=compareLeadershipIdentity(subject,{name:'Example Person',birth_year:1971,birth_month:2});
  const all=aseV2Defaults.components.flatMap(c=>Object.keys(aseV2Defaults.slots[c.key]).map(slot=>({key:`${c.key}:${slot}`,component:c.key,slot,label:slot,state:'CLEAR',score:5,confidence:'High'}))),cap=calculateASEV2(aseV2Defaults,all.map(c=>c.slot==='disqualification' ? {...c,state:'ADVERSE',score:1,verified:true,severe_event:'current_director_disqualification'} : c)),personal=calculateASEV2(aseV2Defaults,all.map(c=>c.slot==='individual_insolvency' ? {...c,state:'ADVERSE',score:1,verified:true,severe_event:'confirmed_material_sanctions'} : c)),missing=calculateASEV2(aseV2Defaults,all.map(c=>c.slot==='individual_insolvency' ? {...c,state:'UNAVAILABLE',score:null} : c));
  const uncertain=aggregateLeadershipSource([{source:'sanctions',match_status:'POTENTIAL MATCH',score:null}],'sanctions','sanctions','Sanctions',true,p),adverseIncomplete=aggregateLeadershipSource([{source:'disqualification',match_status:'ADVERSE',score:1,evidence_reference:'test',checked_at:new Date().toISOString()}],'disqualification','disqualification','Disqualification',false,p);
  const historic=leadershipPersonScores([{source:'disqualification',match_status:'HISTORIC',candidates:[{periods:[{end:'2000-01-01'}]}]}],p)[0],foreign=compareLeadershipIdentity({name:'Example Entity',entity:true,registration_number:'12345678',country:'United Kingdom'},{name:'Example Entity',registration_number:'12345678',registration_country:'Other jurisdiction'});
  const clear=applyLeadershipReviews([{source:'individual_insolvency',person_key:'current',match_status:'UNAVAILABLE'}],[{person_key:'former',source:'individual_insolvency',state:'ADVERSE',reviewed_at:new Date().toISOString(),verified:true}],p)[0];
  const checks={sameNameNeverConfirmed:sameName.status==='POTENTIAL MATCH',corroboratedIdentityConfirmed:strong.status==='CONFIRMED MATCH',conflictingBirthRejected:conflict.status==='NO MATCH',registrationNeedsJurisdiction:foreign.status!=='CONFIRMED MATCH',uncertainSanctionsUnscored:uncertain.score===null,currentDisqualificationCap:cap.final_score===2.5,personalInsolvencyNeverCaps:personal.caps.length===0,missingPersonalCheckNotUnassessed:missing.final_score!==null && missing.coverage<100,sevenComponentsUnchanged:cap.components.length===7,historicLowerImpact:historic.score>p.disqualification_current_score,verifiedAdverseSurvivesIncompleteRoster:adverseIncomplete.score===1,formerRoleNotCarriedForward:clear.match_status==='UNAVAILABLE'};
  return {checks,passed:Object.values(checks).every(Boolean)};
}