import {collectV2Sources,v2SourceFacts} from './aseV2Collect.ts';
import {externalV2Checks} from './aseV2ExternalChecks.ts';
import {allianceV2Checks} from './aseV2AllianceChecks.ts';
import {calculateASEV2,explainASEV2} from './aseV2Calculation.ts';
import {leadershipAssessment} from './aseLeadershipAssessment.ts';
export async function createASEV2Assessment(base44,account,user,policy,assertLease) {
  const collection=await collectV2Sources(base44,account,user,policy.configuration),facts={};
  for(const [key,source] of Object.entries(collection.sources)) facts[key]=await v2SourceFacts(base44.entities,account,source);
  const alliance=await allianceV2Checks(base44,account,policy.configuration),control=await leadershipAssessment(base44,account,policy.configuration,collection),checks=[...externalV2Checks(account,policy.configuration,collection,facts).filter(c=>!(c.component==='profile' && c.slot==='ownership') && !(c.component==='adverse' && c.slot==='sanctions')),...control.checks,...alliance.checks];
  const result=calculateASEV2(policy.configuration,checks),db=base44.entities;
  const [previousPage,legacy]=await Promise.all([db.ASEV2Current.filter({account_id:account.id},{limit:1}),db.ASECurrentRating.filter({account_id:account.id},{limit:1})]),previous=previousPage.items[0],previousAssessment=previous ? await db.ASEV2Assessment.get(previous.assessment_id) : null;
  const drivers=previousAssessment ? result.components.flatMap(c=>{const old=previousAssessment.components.find(r=>r.key===c.key);return old?.score!==c.score ? [`${c.label}: ${old?.score==null ? 'unavailable' : old.score.toFixed(2)} → ${c.score===null ? 'unavailable' : c.score.toFixed(2)}. Evidence: ${checks.filter(check=>check.component===c.key).map(check=>check.reason).join(' ').slice(0,500)}`] : [];}) : ['First ASE v2 assessment; legacy assessments are retained, not converted into v2 evidence.'];
  if(previousAssessment?.dependency?.percentage!==alliance.dependency.percentage && Number.isFinite(alliance.dependency.percentage)) drivers.push(`Alliance Dependency: ${previousAssessment?.dependency?.percentage ?? 'unavailable'}% → ${alliance.dependency.percentage.toFixed(1)}%.`);
  await assertLease();
  const assessment=await db.ASEV2Assessment.create({...result,account_id:account.id,methodology:'ASE v2',assessment_date:new Date().toISOString(),policy_version:policy.version,policy_snapshot:policy.configuration,checks,dependency:alliance.dependency,experience:alliance.experience,leadership:control.leadership,drivers:drivers.slice(0,12),explanation:(explainASEV2(result,checks)+' '+control.leadership.explanation).slice(0,10000),previous_assessment_id:previous?.assessment_id || '',legacy_assessment_id:legacy.items[0]?.assessment_id || '',assessed_by:user.id,assessment_note:'ASE v2 reassessment. Existing current sources reused only within configured freshness; expired sources recollected. Unconfigured providers are unavailable, never silently cleared.'});
  const current={account_id:account.id,assessment_id:assessment.id,methodology:'ASE v2',displayed_rating:assessment.final_score===null ? null : Number(assessment.final_score.toFixed(1)),precise_score:assessment.final_score,rating_label:assessment.classification,data_confidence:assessment.confidence,coverage:assessment.coverage,assessment_date:assessment.assessment_date,explanation:assessment.explanation,previous_rating:previous?.displayed_rating ?? null,change:Number.isFinite(previous?.displayed_rating) && Number.isFinite(assessment.final_score) ? assessment.final_score-previous.displayed_rating : null};
  await db.ASEV2Current.upsert([current],{key:'account_id'});
  return assessment;
}