import {normaliseCompanyNumber} from './companiesHouseData.ts';
const base=(component,slot,label,source,reason)=>({key:`${component}:${slot}`,component,slot,label,source,state:'UNAVAILABLE',score:null,confidence:'Low',reason,verified:false});
export const v2UnavailableCheck=base;
export function externalV2Checks(account,configuration,collection,facts) {
  const {model,sources}=collection,council=model==='english_local_authority',checks=[];
  const financialMap=council ? {strength:'reserves',trend:'reserves_trend',liquidity:'budget',debt:'borrowing'} : {strength:'financial_strength',trend:'financial_trend',liquidity:'liquidity',debt:'debt'};
  const financial=sources[council ? 'local_authority' : 'accounts'],financialFacts=facts[council ? 'local_authority' : 'accounts'] || [];
  for(const [slot,component] of Object.entries(financialMap)) {
    const check=base('financial',slot,council ? component.replaceAll('_',' ') : component.replaceAll('_',' '),council ? 'MHCLG / GOV.UK' : 'Companies House filed accounts',financial?.reason || 'No validated financial metric is available.'),row=financialFacts.filter(r=>r.component===component && r.automatic_eligible && /^-?(?:\d+\.?\d*|\.\d+)$/.test(r.value)).sort((a,b)=>b.reporting_period.localeCompare(a.reporting_period))[0];
    if(row) {const rule=council ? ({strength:{thresholds:[5,10,20,30]},trend:{thresholds:[-5,-2,0,2]},liquidity:{thresholds:[0,1,2,5],descending:true,strict:true},debt:{thresholds:[5,10,15,20],descending:true}})[slot] : configuration.financial_rules[slot],value=Number(row.value),crossed=rule.thresholds.filter(t=>rule.strict ? value>t : value>=t).length,score=rule.descending ? 5-crossed : 1+crossed;Object.assign(check,{state:score>=3 ? 'POSITIVE' : 'ADVERSE',score,confidence:row.confidence,verified:true,reason:`${row.title}: ${row.value}. Deterministic thresholds ${rule.thresholds.join(', ')} give ${score}/5. ${row.automatic_reason || row.notes || ''}`,source_reference:row.source_reference,checked_at:row.retrieval_date,evidence_date:row.reporting_period,evidence_id:row.id});}
    else if(financial?.audit) Object.assign(check,{state:'LIMITED',checked_at:financial.audit.refreshed_at,reason:'Source obtained, but this financial definition is not disclosed or could not be reliably assessed. No adverse result inferred.'});
    else if(financial?.state) check.state=financial.state;
    checks.push(check);
  }
  if(council) {
    for(const [slot,key] of [['registry','intervention'],['gazette','efs']]) {const source=sources[key==='efs' ? 'local_authority' : 'council_governance'],row=(facts[key==='efs' ? 'local_authority' : 'council_governance'] || []).filter(r=>r.component===key && r.automatic_eligible && /^[1-5]$/.test(r.value)).sort((a,b)=>b.reporting_period.localeCompare(a.reporting_period))[0],check=base('adverse',slot,key==='efs' ? 'Exceptional Financial Support' : 'Statutory intervention','MHCLG / GOV.UK',source?.reason || 'No sufficiently validated official council classification.');if(row) Object.assign(check,{score:Number(row.value),state:row.value==='5' ? 'CLEAR' : 'ADVERSE',confidence:row.confidence,verified:true,reason:row.automatic_reason || row.notes,source_reference:row.source_reference,checked_at:row.retrieval_date,evidence_id:row.id});else check.state=source?.state || (source?.audit ? 'LIMITED' : 'UNAVAILABLE');checks.push(check);}
    checks.push(base('profile','filings','Corporate filings','Companies House','Corporate filing checks are not applicable to an unincorporated local authority.'),base('profile','ownership','Corporate profile','Companies House','An unincorporated council is not a subsidiary company. No corporate support inferred.'));
  } else {
    const registry=sources.registry,summary=registry?.audit?.summary,number=account.company_number ? normaliseCompanyNumber(account.company_number) : '',reference=number ? `https://find-and-update.company-information.service.gov.uk/company/${number}` : '';
    const legal=base('adverse','registry','Corporate legal status','Companies House',registry?.reason || 'No current registry status.'),filings=base('profile','filings','Current filing behaviour','Companies House',registry?.reason || 'No current filing check.'),ownership=base('profile','ownership','Trading and corporate profile','Companies House',registry?.reason || 'No complete officer and controller collection.');
    for(const c of [legal,filings,ownership]) {c.state=registry?.state || 'LIMITED';c.source_reference=reference;c.checked_at=registry?.audit?.refreshed_at;}
    if(summary) {
      const status=summary.company_status,severe=status==='dissolved' ? 'dissolved' : ['liquidation','administration','receivership','administrative-receiver','insolvency-proceedings'].includes(status) ? 'active_insolvency' : null;
      if(severe) Object.assign(legal,{state:'ADVERSE',score:1,confidence:'High',verified:true,severe_event:severe,reason:`Verified Companies House legal status: ${status}.`});
      else if(status==='active') Object.assign(legal,{state:'CLEAR',score:5,confidence:'High',verified:true,reason:'Current legal status is active. No current insolvency legal status identified; this does not clear other adverse-event sources.'});
      const items=[summary.accounts?.next_accounts,summary.confirmation_statement],allKnown=items.every(i=>typeof i?.overdue==='boolean'),overdue=items.filter(i=>i?.overdue===true),due=overdue.map(i=>i.due_on || i.next_due),worst=due.length && due.every(d=>Number.isFinite(Date.parse(d))) ? Math.max(...due.map(d=>(Date.now()-Date.parse(d))/86400000)) : null;
      if(allKnown && !overdue.length) Object.assign(filings,{state:'POSITIVE',score:5,confidence:'High',verified:true,reason:'Accounts and confirmation statement are not marked overdue. Historical timeliness is not inferred.'});
      else if(worst>0) Object.assign(filings,{state:'ADVERSE',score:worst>90 ? 1 : worst>30 ? 2 : 3,confidence:'High',verified:true,reason:`Worst current filing ${Math.floor(worst)} days overdue.`});
      if(summary.collections?.officers?.complete && summary.collections?.['persons-with-significant-control']?.complete) Object.assign(ownership,{state:'POSITIVE',score:4,confidence:'Medium',verified:true,reason:`Complete officer and PSC collections support an assessable corporate profile. Incorporated ${summary.date_of_creation || 'date unavailable'}. Age alone, security charges or a strong parent do not imply financial strength or weakness.`,source_reference:reference+'/persons-with-significant-control'});
    }
    checks.push(legal,filings,ownership);
    const gazette=sources.gazette,check=base('adverse','gazette','The Gazette','The Gazette',gazette?.reason || 'Gazette was not checked.'),rows=facts.gazette || [];
    if(gazette?.audit) {check.checked_at=gazette.audit.refreshed_at;const clear=rows.find(r=>r.component==='adverse' && r.value==='5' && r.automatic_eligible);if(clear) Object.assign(check,{state:'CLEAR',score:5,confidence:'High',verified:true,source_reference:clear.source_reference,evidence_id:clear.id,reason:'No relevant adverse notices identified in the successfully completed company-number Gazette search. Positive contribution, limited to this check.'});else {const notices=rows.filter(r=>r.component==='adverse' && r.confidence==='High' && /Exact company number confirmed/.test(r.notes || '')),dated=notices.filter(r=>Number.isFinite(Date.parse(r.source_date)) && Date.parse(r.source_date)<=Date.now());if(dated.length && gazette.audit.summary?.complete) {const scores=dated.map(r=>(Date.now()-Date.parse(r.source_date))/86400000<730 ? 3 : 4);Object.assign(check,{state:'ADVERSE',score:scores.reduce((a,b)=>a+b,0)/scores.length,confidence:'Medium',verified:true,source_reference:dated[0].source_reference,reason:`${dated.length} exact-company-number notices assessed; recent notices contribute 3/5 and older notices 4/5. Current insolvency is not inferred from a notice; only a verified current registry status can apply that cap.`,records:dated.map(r=>({title:r.title,date:r.source_date,reference:r.source_reference}))});}else Object.assign(check,{state:'LIMITED',reason:'Search completed, but notice relevance, resolution or completeness could not be reliably classified; neither clean status nor active insolvency inferred.'});}}
    else check.state=gazette?.state || 'UNAVAILABLE';checks.push(check);
  }
  checks.push(base('adverse','sanctions','UK Sanctions List','Official UK Sanctions List','Awaiting approved entity-matching connector; no sanctions clearance or match is claimed.'),base('market','find_a_tender','Find a Tender','Find a Tender','Awaiting procurement connector. Missing award evidence is not proof of no external customers.'),base('market','contracts_finder','Contracts Finder','Contracts Finder','Awaiting procurement connector. Public awards will represent observed market activity, not total turnover.'),base('esg','environment_agency','Environment Agency','Environment Agency public registers','Awaiting regulatory connector. No environmental clearance or subjective ESG judgement is claimed.'));
  return checks;
}