const stages=['lead','qualified','scope_development','design_feasibility','proposal_preparation','proposal_submitted','negotiation','preferred_partner','on_hold','won','lost'];
const escape=v=>String(v).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
async function relatedIds(entity,query,field){const page=await entity.filter(query,{distinct:field,limit:1000});if(page.has_more) throw new Error('This activity selection is too broad. Narrow the date or ownership filters.');return page.items.filter(Boolean);}
export async function commercialWorkspace(db,user,input){
 const f=input.filters || {},now=new Date(),today=now.toISOString().slice(0,10),start=today.slice(0,7)+'-01',end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1)).toISOString().slice(0,10),recentDate=new Date(Date.now()-30*86400000).toISOString();
 const [overdue,recentA,recentC]=await Promise.all([relatedIds(db.CRMTask,{status:{$in:['open','in_progress']},due_date:{$regex:'\\S',$lt:today}},'opportunity_id'),relatedIds(db.CRMActivity,{occurred_at:{$gte:recentDate}},'opportunity_id'),relatedIds(db.Conversation,{occurred_at:{$gte:recentDate}},'opportunity_id')]);
 const recent=[...new Set([...recentA,...recentC])],q={};if(f.search?.trim())q.title={$regex:escape(f.search.trim()),$options:'i'};if(f.owner==='mine')q.owner_id=user.id;if(f.status)q.status=f.status;if(f.stage)q.stage=f.stage;
 if(f.focus==='overdue'){q.status='open';q.id={$in:overdue};}if(f.focus==='quiet'){q.status='open';q.id={$nin:recent};}if(f.focus==='closing'){q.status='open';q.expected_decision_date={$gte:start,$lt:end};}if(f.focus==='pipeline')q.status='open';if(f.focus==='missing'){q.status='open';const withActions=await relatedIds(db.CRMTask,{status:{$in:['open','in_progress']}},'opportunity_id');q.id={$nin:withActions};q.$or=[{next_action:{$exists:false}},{next_action:''},{next_action:null}];}
 const selectedStages=(input.stages || stages).filter(s=>stages.includes(s) && (!f.stage || f.stage===s));
 const stageQuery=s=>s==='lead' ? {...q,$and:[...(q.$and || []),{$or:[{stage:'lead'},{stage:{$exists:false}}]}]} : {...q,stage:s};
 const [pipeline,lateCount,quietCount,closingCount,totals,listing,board,forecast]=await Promise.all([db.Opportunity.aggregate({query:{status:'open'},sum:['budget','weighted_value']}),db.Opportunity.count({status:'open',id:{$in:overdue}}),db.Opportunity.count({status:'open',id:{$nin:recent}}),db.Opportunity.count({status:'open',expected_decision_date:{$gte:start,$lt:end}}),input.view==='board' ? db.Opportunity.aggregate({query:q,groupBy:'stage',sum:['budget','weighted_value']}) : Promise.resolve({rows:[]}),input.view==='list' ? db.Opportunity.filter(q,{sort:'expected_decision_date',limit:50,...(input.cursor ? {cursor:input.cursor} : {})}) : Promise.resolve({items:[]}),input.view==='board' ? Promise.all(selectedStages.map(async s=>({stage:s,...await db.Opportunity.filter(stageQuery(s),{sort:'expected_decision_date',limit:20,...(input.cursors?.[s] ? {cursor:input.cursors[s]} : {})})}))) : Promise.resolve([]),input.view==='forecast' ? db.Opportunity.aggregate({query:{...q,status:'open',expected_decision_date:{$regex:'^\\d{4}-\\d{2}-\\d{2}'}},dateBucket:{field:'expected_decision_date',unit:'month'},sum:['budget','weighted_value'],sort:'expected_decision_date'}) : Promise.resolve({rows:[]})]);
 const visible=[...listing.items,...board.flatMap(p=>p.items)],accountIds=[...new Set(visible.map(o=>o.account_id).filter(Boolean))],personIds=[...new Set(visible.map(o=>o.contact_id).filter(Boolean))],opportunityIds=visible.map(o=>o.id);
 const [accounts,people,tasks,taskSummary,lastActivities]=await Promise.all([accountIds.length ? db.Account.filter({id:{$in:accountIds}},{limit:250,fields:['name']}) : {items:[]},personIds.length ? db.Contact.filter({id:{$in:personIds}},{limit:250,fields:['full_name','job_title']}) : {items:[]},opportunityIds.length ? db.CRMTask.filter({opportunity_id:{$in:opportunityIds},status:{$in:['open','in_progress']}},{sort:'due_date',limit:250,fields:['opportunity_id','title','due_date','owner_name','owner_id']}) : {items:[]},opportunityIds.length ? db.CRMTask.aggregate({query:{opportunity_id:{$in:opportunityIds},status:{$in:['open','in_progress']}},groupBy:'opportunity_id',min:'due_date'}) : {rows:[]},opportunityIds.length ? db.CRMActivity.aggregate({query:{opportunity_id:{$in:opportunityIds}},groupBy:'opportunity_id',max:'occurred_at'}) : {rows:[]}]);
 const enrich=o=>{const summary=taskSummary.rows.find(t=>t.opportunity_id===o.id),task=tasks.items.find(t=>t.opportunity_id===o.id && (!summary?.min_due_date || t.due_date===summary.min_due_date));return {...o,organisation:accounts.items.find(a=>a.id===o.account_id),person:people.items.find(p=>p.id===o.contact_id),next:task || (summary?.count ? {title:'Open action, view opportunity',due_date:summary.min_due_date} : o.next_action ? {title:o.next_action} : null),noRecent:!recent.includes(o.id),overdue:overdue.includes(o.id),last:lastActivities.rows.find(a=>a.opportunity_id===o.id)?.max_occurred_at};};
 return {metrics:{overdue:lateCount,quiet:quietCount,closing:closingCount,value:pipeline.rows[0]?.sum_budget || 0},listing:{...listing,items:listing.items.map(enrich)},board:board.map(p=>({...p,items:p.items.map(enrich),total:totals.rows.find(t=>(t.stage || 'lead')===p.stage) || {count:0,sum_budget:0}})),forecast:forecast.rows,query:q};
}