const fields = (strings = '', dates = '', booleans = '', numbers = '', lookups = '') => Object.fromEntries([
  ...strings.split(' ').filter(Boolean).map(k => [k, 'String']), ...dates.split(' ').filter(Boolean).map(k => [k, 'DateTime']),
  ...booleans.split(' ').filter(Boolean).map(k => [k, 'Boolean']), ...numbers.split(' ').filter(Boolean).map(k => [k, 'Decimal']),
  ...lookups.split(' ').filter(Boolean).map(k => [k, 'Lookup'])
]);
const yesNo = ['no', 'yes', 'na', 'tbc', ''];
export const additionalFlowSpecs = {
  insurance: { entity: 'SupplierInsurance', label: 'Supplier insurance', sourceNames: ['bss_supplier', 'bss_suppliers', 'bss_supplierinsurance', 'bss_supplierinsurances', 'bss_insurance', 'bss_insurances'], required: 'name', matchFields: ['policy_number'], writeRoles: [], readOnly: true, fields: fields('name policy_number policy_type insurer certificate_url comments status', 'start_date expiry_date renewal_date', '', 'cover_amount excess', 'account_id'), enums: { status: ['active', 'inactive'] }, preservedFields: ['linked_user_id'], sourceNote: 'Map the policy name and supplier lookup to an account. Policies with missing or ambiguous account links stay in the review queue. Insurance is read-only in ALSight.' },
  users: { entity: 'User', label: 'System users', sourceNames: ['systemuser', 'systemusers'], required: 'dataverse_systemuser_id', identityField: 'dataverse_systemuser_id', labelField: 'full_name', matchFields: ['email'], writeRoles: ['admin'], fields: { dataverse_systemuser_id: 'Uniqueidentifier', staff_aad_id: 'Uniqueidentifier', phone: 'String' }, preservedFields: ['full_name', 'email', 'role', 'account_id', 'region', 'line_manager_id', 'delegate_of', 'delegate_of_name', 'delegate_region', 'company_number', 'contact_dataverse_id', 'profile_picture_uri', 'onboarding_step', 'onboarding_completed_at'], readOnly: false },
  dma: { entity: 'DMA', label: 'Development agreements', sourceNames: ['bss_dma', 'bss_dmas'], required: 'document_id', matchFields: ['document_id'], writeRoles: ['admin'], fields: fields('document_id executed approval_status approval_comments approvers_name comments link_to_file payment_terms payment_comments lads lad_comments pcg_bond pcg_comments retention retention_comments framework_support_fee fsf_comments pi_limit pi_comments schedule2 sch2_comments equipment equip_comments structural_insurance si_comments risk_register rr_comments pso_signoff riba3_completion riba4_completion conditions_precedent conditions_precedent_agreed status', 'approval_date drafted_date drafting_due_date date_of_execution sent_for_signing signing_target_date', 'dma_version shared_with_council is_bsm_document_owner', '', 'project_id client_account_id bdm_aad_id bsm_aad_id'), enums: { executed: ['no', 'yes'], status: ['active', 'inactive'], ...Object.fromEntries('payment_terms lads pcg_bond retention framework_support_fee pi_limit schedule2 equipment structural_insurance risk_register'.split(' ').map(k => [k, yesNo])), pso_signoff: ['no', 'yes', ''] } },
  jct: { entity: 'JCT', label: 'JCT contracts', sourceNames: ['bss_jct', 'bss_jcts'], required: 'document_id', matchFields: ['document_id'], writeRoles: ['admin'], fields: fields('document_id form_of_jct executed comments link_to_file contract_particulars cp_comments cps cps_comments ers er_comments pci pci_comments prelims prelim_comments soa soa_comments rr rr_comments valuation_schedule variation_comments status commercial_reference commercial_date_basis commercial_date_source commercial_programme_record_id commercial_effective_reference commercial_effective_date_basis commercial_effective_mode', 'drafted_date drafting_due_date date_of_execution sent_for_signing signing_target_date loi_expiry_date practical_completion commercial_start commercial_end commercial_reviewed_at commercial_effective_start commercial_effective_end', 'shared_with_contractor is_bsm_document_owner commercial_reviewed', 'commercial_value commercial_annual_value commercial_effective_value commercial_effective_annual_value', 'project_id client_account_id bdm_aad_id account_id contractor_id jct_lead_aad_id project_bsm_aad_id bsm_aad_id commercial_reviewed_by'), enums: { form_of_jct: ['design_and_build', 'intermediate_with_contractors_design', 'minor_works', ''], executed: ['no', 'yes'], status: ['active', 'inactive'], ...Object.fromEntries('contract_particulars cps ers pci prelims soa rr valuation_schedule'.split(' ').map(k => [k, yesNo])), commercial_date_basis: ['contract_dates', 'project_programme'], commercial_effective_date_basis: ['', 'contract_dates', 'project_programme'], commercial_effective_mode: ['unavailable', 'reviewed', 'pathway_proposal'] }, preservedFields: ['commercial_effective_source'] },
  warranties: { entity: 'Warranty', label: 'Warranties', sourceNames: ['bss_warranty', 'bss_warranties'], required: 'warranty_id', matchFields: ['warranty_id'], writeRoles: ['admin'], fields: fields('warranty_id services beneficiary category warranty_status format approval_status approval_comments approvers_name link_to_file comments status', 'jct_signed warranty_due practical_completion date_of_execution reminder_date drafted_date approval_date', 'submit_for_approval', '', 'project_id client_account_id bdm_aad_id account_id supplier_id project_bsm_aad_id warranty_lead_aad_id'), enums: { beneficiary: ['council', 'als', 'operator', 'trust', ''], category: ['contractor', 'consultant', 'other', ''], warranty_status: ['awaiting_jct', 'awaiting_appointment', 'in_review', 'sent_for_seal', 'drafted', 'sealed', 'executed', 'product_warranty', ''], format: ['deed', ''], status: ['active', 'inactive'] } },
  accounts: { entity: 'Account', label: 'Accounts', sourceNames: ['account', 'accounts'], required: 'name', matchFields: ['name', 'email', 'company_number'], writeRoles: ['admin'], fields: fields('name account_type organisation_type vat_number local_authority_code public_body_identifier relationship_summary company_number company_name company_status company_type address_line1 address_line2 address_city address_county address_postcode address_country sharepoint_folder region email phone website comments status', 'date_of_incorporation sqq_expiry', 'uklf_approved', '', 'assigned_bsm_aad_id account_manager_aad_id parent_account_id primary_contact_id'), enums: { account_type: ['client', 'supplier'], status: ['active', 'inactive'] }, preservedFields: ['linked_user_id', 'relationship_types', 'ase_score', 'ase_reason', 'ase_assessed_at', 'company_registered_office', 'ch_last_refreshed', 'ch_refresh_id', 'ch_company_number', 'ch_links_self', 'ch_links_officers', 'ch_links_filing_history', 'ch_links_psc'] }
};