const escape=value=>String(value || '').replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
async function ids(entity,query,field) {const page=await entity.filter(query,{distinct:field,limit:1000});if(page.has_more) throw new Error('Please narrow the filters; this relationship selection exceeds 1,000 linked records.');return page.items.filter(Boolean);}
export async function relationshipDirectory(db,input) {
  const f=input.filters || {},clauses=[],today=new Date().toISOString(),cutoff=new Date(Date.now()-60*86400000).toISOString();
  if(f.search?.trim()) clauses.push({$or:['full_name','job_title','company_name','email','officer_role','authority'].map(k=>({[k]:{$regex:escape(f.search.trim()),$options:'i'}}))});
  if(f.status) clauses.push({status:f.status});if(f.portal==='yes') clauses.push({aad_id:{$regex:'\\S'}});if(f.portal==='no') clauses.push({$or:[{aad_id:{$exists:false}},{aad_id:''},{aad_id:null}]});
  if(f.organisation) {const a=await db.Account.get(f.organisation);if(!a) throw new Error('Organisation unavailable.');const links=[a.company_number && {company_number:a.company_number},...new Set([a.company_name,a.name].filter(Boolean))].map(v=>typeof v==='string' ? {company_name:{$regex:'^'+escape(v)+'$',$options:'i'}} : v).filter(Boolean);if(a.primary_contact_id) links.push({dataverse_id:a.primary_contact_id});clauses.push({$or:links.length ? links : [{company_name:'__unlinked__'}]});}
  const profileQuery={};if(f.strength) profileQuery.relationship_strength=f.strength;if(f.owner) profileQuery.relationship_owner_contact_id=f.owner;if(f.strategic==='yes') profileQuery.contact_priority='strategic';if(f.key==='yes' || f.focus==='decision') profileQuery.key_decision_maker=true;
  let include=Object.keys(profileQuery).length ? await ids(db.ContactProfile,profileQuery,'contact_id') : null;
  const [live,recentA,recentC,late,marked]=await Promise.all([ids(db.Opportunity,{status:'open'},'contact_id'),ids(db.CRMActivity,{occurred_at:{$gte:cutoff}},'contact_id'),ids(db.Conversation,{occurred_at:{$gte:cutoff}},'contact_id'),ids(db.CRMContactTask,{status:'open',due_at:{$regex:'\\S',$lt:today}},'contact_id'),ids(db.ContactProfile,{key_decision_maker:true},'contact_id')]);
  const recent=[...new Set([...recentA,...recentC])],attention=[...new Set([...late,...[...live,...marked].filter(id=>!recent.includes(id))])];
  const selected=f.focus==='attention' ? attention : f.focus==='live' || f.live==='yes' ? live : null;if(selected) include=include===null ? selected : include.filter(id=>selected.includes(id));
  const query=clauses.length ? {$and:clauses} : {};if(include!==null) query.id={$in:include};
  const [page,total,decision,need,liveCount]=await Promise.all([db.Contact.filter(query,{sort:'full_name',limit:50,fields:['full_name','job_title','company_name','company_number','email','officer_role','authority','status','aad_id','dataverse_id'],...(input.cursor ? {cursor:input.cursor} : {})}),db.Contact.count({}),db.Contact.count({id:{$in:marked}}),db.Contact.count({id:{$in:attention}}),db.Contact.count({id:{$in:live}})]);
  const personIds=page.items.map(c=>c.id);if(!personIds.length) return {page:{has_more:page.has_more,next_cursor:page.next_cursor},rows:[],metrics:{total,decision,attention:need,live:liveCount}};
  const companyNumbers=page.items.map(c=>c.company_number).filter(Boolean),names=page.items.map(c=>c.company_name).filter(Boolean);
  const [profiles,accounts,activity,conversation,tasks,actions]=await Promise.all([db.ContactProfile.filter({contact_id:{$in:personIds}},{limit:100}),db.Account.filter({$or:[{company_number:{$in:companyNumbers}},{name:{$in:names}},{company_name:{$in:names}}]},{limit:150,fields:['name','company_name','company_number','primary_contact_id']}),db.CRMActivity.aggregate({query:{contact_id:{$in:personIds}},groupBy:'contact_id',max:'occurred_at'}),db.Conversation.aggregate({query:{contact_id:{$in:personIds}},groupBy:'contact_id',max:'occurred_at'}),db.CRMContactTask.aggregate({query:{contact_id:{$in:personIds},status:'open'},groupBy:'contact_id',min:'due_at'}),db.CRMContactTask.filter({contact_id:{$in:personIds},status:'open'},{sort:'due_at',limit:100,fields:['contact_id','title','due_at']})]);
  const owners=profiles.items.map(p=>p.relationship_owner_contact_id).filter(Boolean),staff=owners.length ? await db.Contact.filter({id:{$in:owners}},{limit:100,fields:['full_name']}) : {items:[]};
  const rows=page.items.map(person=>{const profile=profiles.items.find(p=>p.contact_id===person.id),org=accounts.items.find(a=>person.company_number && a.company_number===person.company_number || person.company_name && [a.name,a.company_name].includes(person.company_name)),last=[activity.rows.find(a=>a.contact_id===person.id)?.max_occurred_at,conversation.rows.find(a=>a.contact_id===person.id)?.max_occurred_at].filter(Boolean).sort().at(-1),task=tasks.rows.find(t=>t.contact_id===person.id),next=actions.items.find(t=>t.contact_id===person.id && (!task?.min_due_at || t.due_at===task.min_due_at));return {person,profile,organisation:org,last,next:next || (task?.count ? {title:'Open action, view person',due_at:task.min_due_at} : null),owner:staff.items.find(s=>s.id===profile?.relationship_owner_contact_id)?.full_name};});
  return {page:{has_more:page.has_more,next_cursor:page.next_cursor},rows,metrics:{total,decision,attention:need,live:liveCount}};
}