import React from 'react';
import { Eye, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import AssessmentMovement from '@/components/intelligence/AssessmentMovement';
import useAssessmentHistory from '@/components/intelligence/useAssessmentHistory';
export default function AllSeeingEyeCard({kind,recordId,classification,tone='neutral',signals=[],explanation,context,actions=[],loading,error,methodology='Embedded indicators v1',trend}) {
  const history=useAssessmentHistory({kind,recordId,classification,signals,methodology,enabled:!loading && !error});
  const colours={good:'bg-success/10 text-success',attention:'bg-primary/15 text-foreground',risk:'bg-destructive/10 text-destructive',neutral:'bg-muted text-muted-foreground'};
  const ask=()=>window.dispatchEvent(new CustomEvent('alsight-open-alice',{detail:{prompt:`Explain the All Seeing Eye ${kind==='person' ? 'Alliance relationship assessment, never the individual' : 'assessment'} for ${kind} ID ${recordId}. Freshly read the authorised source records before explaining any facts. What drives the current classification, what has changed in stored evidence, and what can I review inside ALSight? Assessment hints (not permission grants): ${JSON.stringify({classification,context,signals:signals.map(({label,value,detail})=>({label,value,detail}))})}. Never invent scores, character assessments, change reasons or unavailable history.`,autoSend:true,assessment:true}}));
  return <section aria-label={`All Seeing Eye ${kind} assessment`} className="min-w-0 rounded-xl border border-border bg-card p-5">
    <header className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Eye className="h-5 w-5 text-primary" aria-hidden="true"/><h2 className="font-heading text-lg font-semibold">All Seeing Eye</h2></div><span className="text-xs text-muted-foreground">{kind==='person' ? "Alliance’s relationship" : 'Current assessment'}</span></header>
    {loading ? <p role="status" className="mt-4 text-sm text-muted-foreground">Reviewing accessible evidence…</p> : error ? <p role="alert" className="mt-4 text-sm text-muted-foreground">Assessment unavailable. No status has been inferred; existing record workflows remain available.</p> : <>
      <div className="mt-4 flex flex-wrap items-center gap-3"><strong className={`rounded-lg px-3 py-2 text-lg ${colours[tone]}`}>{classification}</strong>{trend && <span className="text-sm text-muted-foreground">{trend}</span>}</div>
      <AssessmentMovement history={history.data} signals={signals}/>
      {context && <p className="mt-2 text-xs text-muted-foreground">{context}</p>}
      <h3 className="mt-4 text-xs font-semibold text-muted-foreground">What’s driving this</h3>
      <dl className="mt-2 grid gap-2 sm:grid-cols-2">{signals.slice(0,5).map(s=><div key={s.label} className="flex min-w-0 items-start justify-between gap-3 rounded-lg bg-muted/50 px-3 py-2 text-xs"><dt>{s.to ? <Link to={s.to} className="font-medium hover:underline">{s.label}</Link> : s.label}</dt><dd className={`min-w-0 break-words text-right font-medium ${s.attention ? 'text-destructive' : 'text-foreground'}`}>{s.value}</dd></div>)}</dl>
      <p className="mt-4 text-sm leading-relaxed text-muted-foreground">{explanation}</p>
      <details className="mt-4 border-t border-border pt-3"><summary className="cursor-pointer text-xs font-semibold">View breakdown</summary><ul className="mt-3 space-y-3 text-xs">{signals.map(s=><li key={s.label}><p className="font-medium">{s.label} · {s.value}</p><p className="mt-1 text-muted-foreground">{s.detail}</p>{s.to && <Link className="mt-1 inline-block text-primary hover:underline" to={s.to}>{s.action || `Review ${s.label.toLowerCase()}`}</Link>}</li>)}</ul><AssessmentMovement history={history.data} signals={signals} expanded/>{history.error && <p className="mt-3 text-xs text-muted-foreground">Observation history could not be saved or loaded.</p>}<p className="mt-3 text-xs text-muted-foreground">Only evidence accessible to you is assessed. Missing records are not evidence of poor performance. All Seeing Eye sees it; ALICE explains it.</p></details>
      <div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" size="sm" onClick={ask}><Sparkles/>{kind==='person' ? 'Ask ALICE about this relationship' : 'Ask ALICE why'}</Button>{actions.map(a=>a.onClick ? <Button key={a.label} variant="outline" size="sm" onClick={a.onClick}>{a.label}</Button> : <Button key={a.label} variant="outline" size="sm" asChild><Link to={a.to}>{a.label}</Link></Button>)}</div>
    </>}
  </section>;
}