import React from 'react';
import AllSeeingEyeCard from '@/components/intelligence/AllSeeingEyeCard';
import useOpportunitySignals from '@/components/intelligence/useOpportunitySignals';
import {isoToday,stageLabel} from '@/components/crm/crm';
export default function OpportunityAllSeeingEye({item,user,canEdit,onAction}) {
  const data=useOpportunitySignals(item,user),base=`/opportunities/${item.id}`,open=item.status==='open',next=data.tasks?.next;
  const days=data.activity?.last ? Math.max(0,Math.floor((Date.now()-Date.parse(data.activity.last))/86400000)) : null;
  const age=item.stage_entered_at ? Math.max(0,Math.floor((Date.now()-Date.parse(item.stage_entered_at))/86400000)) : null;
  const reasons=[!item.owner_id && 'No owner assigned',!item.contact_id && 'No primary contact',!item.expected_decision_date && 'No decision date',open && item.expected_decision_date && item.expected_decision_date<isoToday() && 'Expected decision overdue',open && data.tasks?.overdue>0 && `${data.tasks.overdue} overdue action(s)`,open && !next && !item.next_action && 'No next action recorded',open && days>=21 && `No interaction recorded for ${days} days`,open && ['sent','accepted'].includes(item.fee_status) && ['lead','qualified','scope_development','design_feasibility','proposal_preparation'].includes(item.stage) && 'Fee status and stage need review'].filter(Boolean);
  const classification=!open ? `Closed · ${item.status==='won' ? 'Won' : 'Lost'}` : reasons.length ? 'Needs attention' : 'Recorded context complete';
  const signals=[
    {label:'Next Action',value:data.tasks?.overdue ? `${data.tasks.overdue} overdue` : next?.due_date || (item.next_action ? 'Recorded' : 'Not recorded'),attention:open && data.tasks?.overdue>0,detail:next ? `${next.title} · ${next.owner_name || 'Owner not recorded'} · due ${next.due_date || 'not recorded'}. Human-created action, not an ALICE recommendation.` : item.next_action ? `Recorded next action: ${item.next_action}` : 'No accessible open action is recorded.',to:`${base}?tab=overview#opportunity-actions`,action:'Review actions'},
    {label:'Momentum',value:`${stageLabel(item.stage)}${age===null ? '' : ` · ${age} days`}`,detail:'Stage age comes from stage_entered_at. No arbitrary stage-age threshold or numeric momentum score is applied.',to:`${base}?tab=history`,action:'Review history'},
    {label:'Engagement',value:days===null ? 'Not recorded' : `${days} days since interaction`,attention:open && days>=21,detail:'Existing follow-up indicator: 21 or more days since the latest accessible interaction. This is record recency, not sentiment.',to:`${base}?tab=activity`,action:'Review activity'},
    {label:'Decision readiness',value:item.contact_id ? 'Primary person linked' : 'Primary person not linked',detail:`Owner: ${item.owner_name || 'Not recorded'}. Primary-person linkage does not establish decision-making authority.`,to:`${base}?tab=people`,action:'Open People'},
    {label:'Expected decision',value:item.expected_decision_date || 'Not recorded',attention:open && item.expected_decision_date<isoToday(),detail:'A passed date requires reviewing the recorded date, not assuming a client decision. Changes are shown only when captured in comparable observations.',to:`${base}?tab=overview`,action:'Review opportunity'},
    {label:'Commercial readiness',value:item.fee_status || 'Not recorded',detail:'Existing fee-proposal status only; no numerical readiness score is inferred.',to:`${base}?tab=fees`,action:'Review commercial'},
    ...(data.activity?.change ? [{label:'Latest recorded change',value:`${data.activity.change.type.replaceAll('_',' ')} · ${new Date(data.activity.change.occurred_at).toLocaleDateString('en-GB')}`,detail:'A recorded activity event, not proof of a change in health or close date.',to:`${base}?tab=history`,action:'Review history'}] : [])
  ];
  return <AllSeeingEyeCard kind="opportunity" recordId={item.id} classification={classification} tone={open && reasons.length ? 'attention' : 'neutral'} signals={signals} loading={data.loading} error={data.error} context="Existing recorded-context and follow-up rules. No overall numerical health score exists." explanation={!open ? 'This opportunity is closed. Open-opportunity follow-up flags are not applied.' : reasons.length ? `${reasons.join('; ')}. Review the relevant ALSight records.` : 'The recorded context and accessible follow-up indicators have no active flags; this does not predict the outcome.'} actions={[...(canEdit && open ? [{label:'Update Next Action',onClick:onAction}] : []),{label:'Review Activity',to:`${base}?tab=activity`},{label:'Open People',to:`${base}?tab=people`}]} />;
}