import React, { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { RELATIONSHIPS } from '@/components/accounts/accountPresentation';
import CompanyNumberInput from '@/components/accounts/CompanyNumberInput';
export default function AccountClassification({ account,user,onSaved }) {
  const cache = useQueryClient();
  const [open,setOpen] = useState(false), [busy,setBusy] = useState(false), [error,setError] = useState('');
  const [draft,setDraft] = useState({ relationship_types: [...new Set([account.account_type,...(account.relationship_types || [])])],organisation_type: account.organisation_type || '',vat_number: account.vat_number || '',local_authority_code: account.local_authority_code || '',public_body_identifier: account.public_body_identifier || '',relationship_summary: account.relationship_summary || '',...(user?.role === 'admin' ? {company_number: account.company_number || ''} : {}) });
  if (user?.role !== 'admin' && account.linked_user_id !== user?.id) return null;
  const save = async event => { event.preventDefault(); setBusy(true); setError(''); try {
    const updated = await base44.entities.Account.update(account.id,draft); onSaved(updated); cache.setQueryData(['accounts-revision'],Date.now()); cache.invalidateQueries({ queryKey: ['accounts-view'] }); cache.invalidateQueries({ queryKey: ['account-filter-options'] }); setOpen(false);
  } catch (e) { setError(e.message || 'Unable to update the account.'); } finally { setBusy(false); } };
  return <><Button variant="outline" onClick={() => { if(user?.role === 'admin') setDraft(old => ({...old,company_number:account.company_number || ''})); setOpen(true); }}>Edit organisation details</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>Organisation classification</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-4"><fieldset><legend className="mb-3 text-sm font-semibold">Relationship types</legend><div className="grid grid-cols-2 gap-3">{RELATIONSHIPS.map(([value,label]) => <label className="flex items-center gap-2 text-sm" key={value}><input type="checkbox" checked={draft.relationship_types.includes(value)} disabled={value === account.account_type} onChange={event => setDraft(old => ({ ...old,relationship_types: event.target.checked ? [...old.relationship_types,value] : old.relationship_types.filter(type => type !== value) }))} />{label}</label>)}</div><p className="mt-2 text-xs text-muted-foreground">The existing primary organisation type is retained to preserve linked records.</p></fieldset>{user?.role === 'admin' && <CompanyNumberInput value={draft.company_number || ''} onChange={value => setDraft(old => ({...old,company_number:value}))} />}{[['organisation_type','Organisation type'],['vat_number','VAT number'],['local_authority_code','Local-authority code'],['public_body_identifier','Public-body identifier']].map(([key,label]) => <label className="block text-sm" key={key}>{label}<input maxLength={120} className="mt-1 w-full rounded-lg border border-input p-2" value={draft[key]} onChange={event => setDraft(old => ({ ...old,[key]:event.target.value }))} /></label>)}<label className="block text-sm">Relationship summary<textarea maxLength={3000} className="mt-1 w-full rounded-lg border border-input p-2" value={draft.relationship_summary} onChange={event => setDraft(old => ({ ...old,relationship_summary:event.target.value }))} /></label>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save organisation details'}</Button></form></DialogContent></Dialog></>;
}