import React, {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import useAccountInsurance from '@/components/accounts/useAccountInsurance';
import InsurancePolicyCard from '@/components/accounts/InsurancePolicyCard.jsx';
const labels={all:'All policies',expired:'Expired',expiring:'Expiring in 28 days',current:'Current beyond 28 days',missing:'Expiry not recorded'};
export default function AccountInsurance({account}) {
 const [filter,setFilter]=useState('all'),[search,setSearch]=useState('');
 const {policies,metrics,refresh}=useAccountInsurance(account,filter,search),rows=policies.data?.pages.flatMap(page=>page.items) || [];
 return <section className="space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-heading text-xl font-semibold">Insurance</h2><p className="mt-1 text-sm text-muted-foreground">Policies linked to {account.name}, including active and inactive records. Expiry is assessed by UK calendar date.</p></div><Button variant="outline" onClick={refresh} disabled={policies.isFetching || metrics.isFetching}>Refresh</Button></div>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['all','expired','expiring','missing'].map(key=><button key={key} type="button" onClick={()=>setFilter(key)} className={`rounded-panel border bg-card p-4 text-left ${filter===key ? 'border-primary' : 'border-border'}`}><span className="block text-xs text-muted-foreground">{labels[key]}</span><span className={`mt-2 block text-2xl font-semibold ${key==='expired' ? 'text-destructive' : 'text-foreground'}`}>{metrics.isPending ? '…' : metrics.isError ? '—' : metrics.data[key]}</span></button>)}</div>
  {metrics.isError && <p role="alert" className="text-sm text-destructive">Unable to load insurance totals. Use Refresh to retry.</p>}
  <div className="flex flex-wrap gap-3"><select aria-label="Insurance expiry filter" className="h-9 rounded-md border border-input bg-card px-3 text-sm" value={filter} onChange={e=>setFilter(e.target.value)}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><Input className="max-w-md" aria-label="Search insurance policies" placeholder="Search policy, number or insurer…" value={search} onChange={e=>setSearch(e.target.value)}/></div>
  {policies.isPending ? <p role="status" className="py-8 text-sm text-muted-foreground">Loading insurance policies…</p> : policies.isError ? <div role="alert" className="rounded-panel border border-border bg-card p-5"><p className="text-sm text-destructive">Unable to load policies.</p><Button variant="outline" className="mt-3" onClick={()=>policies.refetch()}>Try again</Button></div> : rows.length ? <div className="space-y-3">{rows.map(policy=><InsurancePolicyCard key={policy.id} policy={policy}/>)}</div> : <div className="rounded-panel border border-dashed border-border bg-card p-8 text-center text-sm text-muted-foreground">{filter==='all' && !search ? 'No insurance policies have been synced for this account yet.' : 'No policies match this filter.'}</div>}
  {policies.hasNextPage && <Button variant="outline" disabled={policies.isFetchingNextPage} onClick={()=>policies.fetchNextPage()}>{policies.isFetchingNextPage ? 'Loading…' : 'Load more policies'}</Button>}
 </section>;
}