import React from 'react';
import { formatDate, formatDateTime, regionName } from '@/lib/portal';
import { hasCompanyRegistry, hasSupplierQualification } from '@/components/accounts/accountSections';
import InlineDataverseField from '@/components/dataverse/InlineDataverseField';
export default function AccountKeyInformation({ account, showRegistryDetails = true }) {
  const registry = showRegistryDetails && hasCompanyRegistry(account);
  const normaliseNumber = value => { const text=String(value || '').trim().toUpperCase(),match=text.match(/^([A-Z]{2})(\d{1,6})$/);return /^\d{1,8}$/.test(text) ? text.padStart(8,'0') : match ? match[1]+match[2].padStart(6,'0') : text; };
  const mismatchedSource = registry && account.ch_company_number && normaliseNumber(account.ch_company_number)!==normaliseNumber(account.company_number);
  const facts = [...(registry && !mismatchedSource ? [['Registered company name',account.company_name],['Company status',account.company_status],['Incorporated',account.date_of_incorporation ? formatDate(account.date_of_incorporation) : null]] : []),['Primary location',[account.address_line1,account.address_line2,account.address_city,account.address_county,account.address_postcode,account.address_country].filter(Boolean).join(', ')],['Region',account.region ? regionName(account.region) : null],['Email',account.email],['Phone',account.phone],['SQQ expiry',hasSupplierQualification(account) && account.sqq_expiry ? formatDate(account.sqq_expiry) : null]].filter(([,value]) => value);
  const links = registry && !mismatchedSource ? [['Companies House',account.ch_links_self],['Officers',account.ch_links_officers],['Filings',account.ch_links_filing_history],['Ownership / PSC',account.ch_links_psc]].filter(([,url]) => url) : [];
  if (!facts.length && !links.length && !mismatchedSource) return null;
  return <section className="account-panel"><h2>Key Information</h2>{mismatchedSource && <p role="alert" className="mb-3 text-sm text-destructive">Saved registry information refers to Company Number {account.ch_company_number}. Refresh Companies House for the new identifier before relying on these details.</p>}{registry && !mismatchedSource && account.ch_last_refreshed && <p className="mb-3 text-xs text-muted-foreground">Registered company information · Source: Companies House · Last refreshed: {formatDateTime(account.ch_last_refreshed)}</p>}<dl className="account-key-info">{facts.map(([label,value]) => <div key={label}><dt>{label}</dt><dd><InlineDataverseField label={label}>{value || 'Not recorded'}</InlineDataverseField></dd></div>)}</dl><div className="mt-4 flex flex-wrap gap-3 text-xs font-semibold">{links.filter(([,url]) => url).map(([label,url]) => <a key={label} href={url} target="_blank" rel="noreferrer" className="underline underline-offset-4">{label} ↗</a>)}</div></section>;
}