import React from 'react';
import { useQuery,useMutation,useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { useAuth } from '@/lib/AuthContext';
import { Button } from '@/components/ui/button';
import { formatDateTime } from '@/lib/portal';
import { aseRoles,aseError,invalidateASE } from '@/components/ase/aseClient';
import CompaniesHouseProfile from '@/components/accounts/CompaniesHouseProfile';
import CompaniesHouseRecords from '@/components/accounts/CompaniesHouseRecords';
import { hasCompanyRegistry } from '@/components/accounts/accountSections';
import CompaniesHouseLinks from '@/components/accounts/CompaniesHouseLinks';
export default function CompaniesHousePanel({account,onUpdated}) {
  const {user}=useAuth(),cache=useQueryClient(),allowed=aseRoles.includes(user?.role) && hasCompanyRegistry(account);
  const key=['companies-house',account.id,user?.id,account.company_number];
  const query=useQuery({queryKey:key,enabled:allowed && !!account.company_number,queryFn:async()=>(await base44.functions.invoke('manageCompaniesHouse',{action:'read',accountId:account.id})).data});
  const refresh=useMutation({mutationFn:async()=>(await base44.functions.invoke('manageCompaniesHouse',{action:'refresh',accountId:account.id})).data,onSuccess:data=>{onUpdated?.(data.accountPatch);cache.invalidateQueries({queryKey:['companies-house',account.id]});cache.invalidateQueries({queryKey:['accounts-view']});invalidateASE(cache);}});
  const download=useMutation({mutationFn:async()=>{const {signed_url}=await base44.integrations.Core.CreateFileSignedUrl({file_uri:query.data.audit.raw_file_uri});window.open(signed_url,'_blank','noopener,noreferrer');}});
  if(!allowed) return null;
  const audit=query.data?.audit, lastAttempt=query.data?.lastAttempt;
  return <section className="account-panel account-overview-wide"><div className="flex flex-wrap items-center justify-between gap-3"><h2>Companies House · Risk & Compliance</h2><Button variant="outline" disabled={!account.company_number || refresh.isPending} onClick={()=>refresh.mutate()}>{refresh.isPending ? 'Refreshing Companies House…' : 'Refresh Companies House'}</Button></div><p className="mb-4 text-xs text-muted-foreground">Source: Companies House · Last refreshed: {audit ? formatDateTime(audit.refreshed_at) : 'Not refreshed'}</p>{!account.company_number ? <p className="text-sm text-muted-foreground">An administrator must record the Company Number in Account details before refreshing. Matching is by Company Number, never by name.</p> : query.isPending ? <p role="status">Loading stored Companies House information…</p> : !audit && <p className="text-sm text-muted-foreground">{query.data?.mismatch ? 'The Company Number has changed; refresh before using the old registry information.' : 'No saved Companies House refresh. Opening this page does not call the external registry.'}</p>}{lastAttempt?.status==='failed' && <p role="alert" className="my-3 text-sm text-destructive">Last attempt ({formatDateTime(lastAttempt.refreshed_at)}) failed: {lastAttempt.error}. Any previously saved successful refresh remains unchanged.</p>}{(refresh.error || query.error || download.error) && <p role="alert" className="my-3 text-sm text-destructive">{aseError(refresh.error || query.error || download.error)}</p>}{refresh.isSuccess && <p className="mb-3 text-sm text-success">Existing Account enriched; {refresh.data.evidenceCount} ASE source facts updated. Calculate a new ASE assessment to apply eligible evidence.</p>}{audit?.summary && <div className="space-y-4"><CompaniesHouseProfile summary={audit.summary}/><CompaniesHouseLinks account={account}/>{audit.warnings?.map(warning=><p key={warning} className="text-sm text-destructive">{warning}</p>)}<p className="text-xs text-muted-foreground">Charges alone do not indicate financial distress. Historical insolvency records and officer changes require context. No favourable ASE score or absence of all adverse events is inferred from this source alone.</p><div className="grid gap-3 lg:grid-cols-2">{['officers','persons-with-significant-control','filing-history','charges','insolvency'].map(kind=><CompaniesHouseRecords key={audit.id+kind} accountId={account.id} audit={audit} kind={kind}/>)}</div><div className="flex flex-wrap items-center gap-3"><Button variant="outline" disabled={download.isPending} onClick={()=>download.mutate()}>{download.isPending ? 'Preparing audit download…' : 'Download raw audit snapshot'}</Button><span className="break-all text-xs text-muted-foreground">SHA-256: {audit.raw_sha256}</span></div></div>}</section>;
}