import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { aseError } from '@/components/ase/aseClient';
const names={officers:'Officers','persons-with-significant-control':'Persons with Significant Control','filing-history':'Filing history',charges:'Charges',insolvency:'Insolvency information'};
export default function CompaniesHouseRecords({accountId,audit,kind}) {
  const [open,setOpen]=useState(false),[offset,setOffset]=useState(0);
  const query=useQuery({queryKey:['companies-house-records',accountId,audit.id,kind,offset],enabled:open,queryFn:async()=>(await base44.functions.invoke('manageCompaniesHouse',{action:'records',accountId,kind,offset})).data});
  const collection=audit.summary.collections[kind];
  return <section className="rounded-lg border border-border p-3"><button type="button" className="flex w-full items-center justify-between gap-3 text-left text-sm font-semibold" aria-expanded={open} onClick={()=>setOpen(value=>!value)}><span>{names[kind]}</span><span className="text-xs text-muted-foreground">{collection.no_record ? 'No record returned' : `${collection.retrieved || 0} retrieved${collection.total!=null ? ` / ${collection.total}` : ''}`} · {open ? 'Hide' : 'View'}</span></button>{open && <div className="mt-3 space-y-3">{query.isPending ? <p role="status">Loading stored records…</p> : query.error ? <p role="alert" className="text-sm text-destructive">{aseError(query.error)}</p> : <>{!query.data.items.length && <p className="text-sm text-muted-foreground">{collection.complete ? 'No records returned by this Companies House endpoint.' : 'This collection was not fully retrieved; no absence is inferred.'}</p>}{query.data.items.map((row,i)=><article key={row.transaction_id || row.charge_code || i} className="border-b border-border pb-2 text-sm"><p className="font-medium">{row.name || row.description?.replaceAll('-',' ') || row.type?.replaceAll('-',' ') || `Record ${offset+i+1}`}</p><p className="text-xs text-muted-foreground">{[row.officer_role?.replaceAll('-',' '),row.category,row.date,row.appointed_on && `Appointed ${row.appointed_on}`,row.resigned_on && `Resigned ${row.resigned_on}`,row.created_on && `Created ${row.created_on}`,row.status,row.delivered_on && `Delivered ${row.delivered_on}`].filter(Boolean).join(' · ')}</p>{row.natures_of_control && <p className="text-xs">{row.natures_of_control.map(value=>value.replaceAll('-',' ')).join(', ')}</p>}{row.description_values && <p className="text-xs">{Object.entries(row.description_values).map(([k,v])=>`${k.replaceAll('_',' ')}: ${String(v)}`).join(' · ')}</p>}{row.persons && <p className="text-xs">{row.persons.map(p=>p.name).join(', ')}</p>}{row.dates && <p className="text-xs">{row.dates.map(d=>`${d.type}: ${d.date}`).join(' · ')}</p>}</article>)}{(offset>0 || query.data.has_more) && <div className="flex gap-2"><Button variant="outline" disabled={!offset} onClick={()=>setOffset(n=>n-50)}>Previous</Button><Button variant="outline" disabled={!query.data.has_more} onClick={()=>setOffset(query.data.next_offset)}>More records</Button></div>}</>}{!collection.complete && <p className="text-xs text-destructive">Collection incomplete. Consult the source register before drawing conclusions.</p>}<a target="_blank" rel="noreferrer" className="text-xs underline" href={`https://find-and-update.company-information.service.gov.uk/company/${audit.company_number}/${kind}`}>View Companies House source</a></div>}</section>;
}