import React from 'react';
import FlowChoiceMapping from '@/components/dataverse/FlowChoiceMapping';
import FlowLookupTarget from '@/components/dataverse/FlowLookupTarget';
export default function FlowColumnRow({ prefix, local, type, mapping, source, compatible, suggested, mode, disabled, loaded, readOnly, required, choices, onChoose, onUpdate, onPlan }) {
  const status = mode === 'base44_only' ? 'Base44 only' : mode === 'needs_dataverse' ? 'Dataverse column needed' : mapping ? (mapping.origin === 'automatic' || (!mapping.origin && suggested === mapping.source) ? 'Auto-mapped' : mapping.origin === 'manual' ? 'Manually mapped' : 'Saved mapping') : 'Not mapped';
  return <div className="space-y-2 rounded-lg border border-border bg-card p-3">
    <div className="grid gap-3 lg:grid-cols-[1fr_2fr_1fr] lg:items-center">
      <label htmlFor={`flow-map-${prefix}-${local}`} className="text-sm font-medium"><span className="capitalize">{local.replaceAll('_', ' ')}</span><span className="mt-1 block text-xs font-normal text-muted-foreground">{type || 'Base44-managed'}{source?.type ? ` (Dataverse: ${source.type})` : ''} · {status}{required ? ' · Required' : ''}</span></label>
      <div><select id={`flow-map-${prefix}-${local}`} className="h-9 w-full min-w-0 rounded-md border border-input bg-card px-2 text-sm" disabled={disabled || !loaded || !type} value={mapping?.source || ''} onChange={e => onChoose(e.target.value)}><option value="">{loaded ? 'Choose a Dataverse column (or leave unmapped)' : 'Load Dataverse columns to select'}</option>{mapping && !compatible.some(f => f.name === mapping.source) && <option value={mapping.source}>{mapping.source}</option>}{compatible.map(f => <option key={f.name} value={f.name}>{f.label} · {f.name} · {f.type}{f.writable ? '' : ' (read-only)'}</option>)}</select>{type && !loaded && <p className="mt-1 text-xs text-muted-foreground">Use “Load / reload column options” above to enable selection.</p>}{loaded && type && !mapping && compatible.length > 0 && <p className="mt-1 text-xs text-muted-foreground">Select from {compatible.length} unassigned Dataverse columns. The sync type follows your selection.</p>}{loaded && type && !mapping && !compatible.length && <p className="mt-1 text-xs text-muted-foreground">No unassigned readable Dataverse columns remain. Remove an existing mapping to reuse its column.</p>}{!type && <p className="mt-1 text-xs text-muted-foreground">App-managed or structured data; no direct sync mapping available.</p>}</div>
      <div className="space-y-2 text-xs"><label className="flex items-center gap-2"><input type="checkbox" disabled={disabled || required} checked={mode === 'base44_only'} onChange={e => onPlan(e.target.checked ? 'base44_only' : '')} />Exclusively in Base44</label><label className="flex items-center gap-2"><input type="checkbox" disabled={disabled || required} checked={mode === 'needs_dataverse'} onChange={e => onPlan(e.target.checked ? 'needs_dataverse' : '')} />Needs a Dataverse column</label>{type && <label className="flex items-center gap-2"><input type="checkbox" disabled={disabled || readOnly || !mapping || !source?.writable || (source.type === 'Lookup' && source.lookupTargets?.length !== 1 && !mapping?.lookupTarget)} checked={Boolean(mapping?.write)} onChange={e => onUpdate({ write: e.target.checked })} />Allow write-back</label>}</div>
    </div>
    {mode === 'needs_dataverse' && <p className="text-xs text-muted-foreground">Ask IT to add a compatible column to this Dataverse table, then reload column options and map it here. This flag does not create a column.</p>}
    {mapping && source && !source.writable && <p className="text-xs text-muted-foreground">Dataverse marks this column as read-only; write-back is unavailable.</p>}
    <FlowLookupTarget source={source} mapping={mapping} disabled={disabled} onUpdate={onUpdate} />
    <FlowChoiceMapping source={source} choices={choices} values={mapping?.values} onChange={values => onUpdate({ values, origin: 'manual' })} disabled={disabled} />
  </div>;
}