import React, { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import useFlowOperation from '@/components/dataverse/useFlowOperation';
import FlowReviewDetail from '@/components/dataverse/FlowReviewDetail';
const filters = [['pending', 'Pending'], ['unmatched', 'No match'], ['error', 'Errors'], ['applied', 'Applied'], ['rejected', 'Rejected'], ['', 'All reviews']];
export default function FlowReviewQueue({ table, refreshKey }) {
  const { run, busy, error } = useFlowOperation(), [status, setStatus] = useState('pending'), [page, setPage] = useState(null), [items, setItems] = useState([]), [selected, setSelected] = useState(null), [notice, setNotice] = useState('');
  const load = async cursor => { const result = await run('reviews', { table, status, ...(cursor ? { cursor } : {}) }); if (result) { setPage(result); setItems(old => cursor ? [...old, ...result.items] : result.items); } };
  useEffect(() => { setPage(null); setItems([]); setSelected(null); load(); }, [table, refreshKey, status]);
  const decided = message => { setNotice(message); setSelected(null); load(); };
  return <div className="space-y-3 border-t border-border pt-4"><header><h4 className="font-semibold">Placeholder matching review</h4><p className="text-xs text-muted-foreground">Linked records refresh during sync. Unlinked records wait here for approval; rejected placeholders stay untouched.</p></header><div className="flex flex-wrap gap-2">{filters.map(([key, label]) => <Button key={key} size="sm" variant={status === key ? 'default' : 'outline'} disabled={Boolean(busy)} onClick={() => setStatus(key)}>{label}{key && page ? ` (${page.counts?.[key] || 0})` : ''}</Button>)}<Button size="sm" variant="outline" disabled={Boolean(busy)} onClick={() => load()}>Refresh reviews</Button></div>{page && !items.length && <p className="text-xs text-muted-foreground">No records in this view. Scan the mapped table to populate reviews.</p>}{items.length > 0 && <div className="max-h-72 space-y-2 overflow-auto">{items.map(review => <button key={review.id} type="button" disabled={Boolean(busy)} onClick={() => setSelected(review)} className={`flex w-full flex-wrap items-center justify-between gap-2 rounded-md border p-3 text-left text-sm ${selected?.id === review.id ? 'border-primary bg-primary/10' : 'border-border bg-card'}`}><span>{review.source_label || review.source_id}{review.source_email && <span className="ml-2 text-xs text-muted-foreground">{review.source_email}</span>}</span><span className="text-xs capitalize text-muted-foreground">{review.status} · {review.candidates?.length || 0} candidates</span></button>)}</div>}{page?.has_more && <Button variant="outline" disabled={Boolean(busy)} onClick={() => load(page.next_cursor)}>More reviews</Button>}{selected && <FlowReviewDetail key={selected.id} table={table} review={selected} onDecided={decided} />}{busy && <p role="status" className="text-xs">Loading reviews…</p>}{error && <p role="alert" className="text-xs text-destructive">{error}</p>}{notice && <p role="status" className="text-xs text-success">{notice}</p>}</div>;
}