import React, { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { useQueryClient } from '@tanstack/react-query';
import useFlowOperation from '@/components/dataverse/useFlowOperation';
import FlowReviewTargetPicker from '@/components/dataverse/FlowReviewTargetPicker';
import FlowReviewComparison from '@/components/dataverse/FlowReviewComparison';
export default function FlowReviewDetail({ table, review, onDecided }) {
  const { run, busy, error } = useFlowOperation(), [targetId, setTargetId] = useState(review.target_id || (review.candidates?.length === 1 ? review.candidates[0].id : '')), [data, setData] = useState(null);
  const client = useQueryClient(), editable = ['pending', 'unmatched', 'error', 'approved'].includes(review.status);
  useEffect(() => { let active = true; setData(null); run('reviewDetails', { table, reviewId: review.id, targetId }).then(result => { if (active && result) setData(result); }); return () => { active = false; }; }, [table, review.id, targetId]);
  const decide = async decision => { const result = await run('decideReview', { table, reviewId: review.id, decision, targetId, etag: data?.etag, localUpdatedAt: data?.localUpdatedAt }); if (result) { client.invalidateQueries(); onDecided(result.notice); } };
  return <section className="space-y-3 rounded-lg border border-border bg-muted p-4"><header><h4 className="font-semibold">{review.source_label || review.source_id}</h4><p className="break-all text-xs text-muted-foreground">{review.source_id}{review.source_email && ` · ${review.source_email}`}</p></header>{review.error && <p className="text-xs text-destructive">{review.error}</p>}{editable && <FlowReviewTargetPicker table={table} review={review} selected={targetId} onSelect={id => { setData(null); setTargetId(id); }} />}{data && <FlowReviewComparison data={data} />}<div className="flex flex-wrap gap-2">{editable && <><Button disabled={Boolean(busy) || !targetId || !data?.local || !data?.etag} onClick={() => decide('approve')}>Approve match and refresh</Button><Button variant="outline" disabled={Boolean(busy)} onClick={() => decide('reject')}>Reject · keep placeholder</Button></>}{review.status === 'rejected' && <Button variant="outline" disabled={Boolean(busy)} onClick={() => decide('reopen')}>Reopen review</Button>}{editable && <Button variant="outline" disabled={Boolean(busy)} onClick={async () => { setData(null); const result = await run('reviewDetails', { table, reviewId: review.id, targetId }); if (result) setData(result); }}>Reload comparison</Button>}</div>{busy && <p role="status" className="text-xs">{busy === 'decideReview' ? 'Applying review decision…' : 'Loading live comparison…'}</p>}{error && <p role="alert" className="text-xs text-destructive">{error}</p>}</section>;
}