import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { useAuth } from '@/lib/AuthContext';
import { Button } from '@/components/ui/button';
import { formatCurrency } from '@/lib/portal';
import { STAGES, stageLabel, chance, weighted, createCRMOpportunity } from '@/components/crm/crm';
import ClientSelect from '@/components/crm/ClientSelect';
import SearchableSelect from '@/components/forms/SearchableSelect';
export default function CRMOpportunities() {
  const { user } = useAuth();
  const [rows, setRows] = useState([]), [accounts, setAccounts] = useState([]), [cursor, setCursor] = useState(null), [more, setMore] = useState(false), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState('');
  const [filters, setFilters] = useState({ view: 'all', search: '', stage: '', sort: '-created_date' });
  const [open, setOpen] = useState(false), [form, setForm] = useState({ title: '', account_id: '', location: '', budget: '', expected_decision_date: '', stage: 'lead' });
  const canEdit = ['admin','director','bdm','bsm'].includes(user?.role);
  const load = async (next = null) => { setLoading(true); setError(''); try {
    const now = new Date(), today = now.toISOString().slice(0,10), ninety = new Date(Date.now() + 90 * 86400000).toISOString().slice(0,10), month = new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().slice(0,10);
    const q = {}; if (filters.view === 'mine') q.owner_id = user.id; if (filters.view === 'open') q.status = 'open'; if (filters.view === 'won' || filters.view === 'lost') q.status = filters.view;
    if (filters.view === 'closing_month') { q.status = 'open'; q.expected_decision_date = { $gte: today, $lte: month }; }
    if (filters.view === 'closing_90') { q.status = 'open'; q.expected_decision_date = { $gte: today, $lte: ninety }; }
    if (filters.view === 'proposal') { q.status = 'open'; q.stage = 'proposal_submitted'; }
    if (filters.stage) q.stage = filters.stage;
    if (filters.search.trim()) q.title = { $regex: filters.search.trim().replace(/[.*+?^${}()|[\]\\]/g,'\\$&'), $options: 'i' };
    const page = await base44.entities.Opportunity.filter(q, { sort: filters.sort, limit: 50, ...(next ? { cursor: next } : {}) });
    setRows(old => next ? [...old, ...page.items] : page.items); setCursor(page.next_cursor); setMore(page.has_more);
    const ids = [...new Set(page.items.map(o => o.account_id).filter(Boolean))];
    if (ids.length) { const accountPage = await base44.entities.Account.filter({ id: { $in: ids } }, { limit: 50, fields: ['name'] }); setAccounts(old => next ? [...old, ...accountPage.items] : accountPage.items); }
    else if (!next) setAccounts([]);
  } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { if (user?.id) load(); }, [user?.id, filters.view, filters.stage, filters.sort, filters.search]);
  const create = async e => { e.preventDefault(); setSaving(true); setError(''); try { const item = await createCRMOpportunity({ account_id: form.account_id, title: form.title, location: form.location, stage: form.stage, ...(form.budget ? { budget: Number(form.budget) } : {}), expected_decision_date: form.expected_decision_date }, user); setOpen(false); setForm({ title: '', account_id: '', location: '', budget: '', expected_decision_date: '', stage: 'lead' }); await load(); window.location.href = `/opportunities/${item.id}`; } catch (e) { setError(e.message); } finally { setSaving(false); } };
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><h1 className="font-heading text-2xl font-semibold">Opportunities</h1>{canEdit && <Button onClick={() => setOpen(v => !v)}>{open ? 'Close form' : '+ New opportunity'}</Button>}</div>
    {open && <form onSubmit={create} className="grid gap-3 rounded-xl border border-border bg-card p-5 sm:grid-cols-3"><input required maxLength={200} aria-label="Opportunity name" placeholder="Opportunity name" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className="rounded-lg border border-input p-2 text-sm" /><ClientSelect value={form.account_id} onChange={account_id => setForm({ ...form, account_id })} /><input aria-label="Location" placeholder="Location" value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} className="rounded-lg border border-input p-2 text-sm" /><input aria-label="Estimated project value" type="number" min="0" placeholder="Estimated value (£)" value={form.budget} onChange={e => setForm({ ...form, budget: e.target.value })} className="rounded-lg border border-input p-2 text-sm" /><select aria-label="Stage" value={form.stage} onChange={e => setForm({ ...form, stage: e.target.value })} className="rounded-lg border border-input p-2 text-sm">{STAGES.slice(0,8).map(s => <option key={s.value} value={s.value}>{s.label}</option>)}</select><input aria-label="Expected decision date" type="date" value={form.expected_decision_date} onChange={e => setForm({ ...form, expected_decision_date: e.target.value })} className="rounded-lg border border-input p-2 text-sm" /><Button disabled={saving || !form.title.trim() || !form.account_id}>{saving ? 'Creating…' : 'Create opportunity'}</Button></form>}
    <div className="flex flex-wrap gap-2"><select aria-label="View" value={filters.view} onChange={e => setFilters({ ...filters, view: e.target.value })} className="rounded-lg border border-input p-2 text-sm">{[['all','All opportunities'],['mine','My opportunities'],['open','All open'],['closing_month','Closing this month'],['closing_90','Closing next 90 days'],['proposal','Proposal submitted'],['won','Won'],['lost','Lost']].map(([v,label]) => <option key={v} value={v}>{label}</option>)}</select><SearchableSelect aria-label="Filter by stage" value={filters.stage} onChange={e => setFilters({ ...filters, stage: e.target.value })} className="rounded-lg border border-input p-2 text-sm"><option value="">All stages</option>{STAGES.map(s => <option key={s.value} value={s.value}>{s.label}</option>)}</SearchableSelect><input aria-label="Search opportunities" placeholder="Search opportunities" value={filters.search} onChange={e => setFilters({ ...filters, search: e.target.value })} className="min-w-44 rounded-lg border border-input p-2 text-sm" /><select aria-label="Sort opportunities" value={filters.sort} onChange={e => setFilters({ ...filters, sort: e.target.value })} className="rounded-lg border border-input p-2 text-sm"><option value="-created_date">Newest first</option><option value="created_date">Oldest first</option><option value="-budget">Highest value</option><option value="expected_decision_date">Decision date</option></select></div>
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}{loading && !rows.length ? <p className="text-muted-foreground">Loading opportunities…</p> : !rows.length ? <p className="text-muted-foreground">No opportunities match this view.</p> : <div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-muted text-xs text-muted-foreground"><tr>{['Opportunity','Client','Location','Owner','Stage','Project value','Alliance fee','Probability','Weighted value','Decision','Age','Status'].map(h => <th key={h} className="px-3 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{rows.map(o => <tr key={o.id}><td className="px-3 py-3 font-medium"><Link to={`/opportunities/${o.id}`} className="text-primary hover:underline">{o.title}</Link></td><td className="px-3 py-3">{accounts.find(a => a.id === o.account_id)?.name || '—'}</td><td className="px-3 py-3">{o.location || o.site_postcode || '—'}</td><td className="px-3 py-3">{o.owner_name || 'Unassigned'}</td><td className="px-3 py-3">{stageLabel(o.stage)}</td><td className="px-3 py-3">{formatCurrency(o.budget)}</td><td className="px-3 py-3">{formatCurrency(o.alliance_fee)}</td><td className="px-3 py-3">{chance(o)}%</td><td className="px-3 py-3">{formatCurrency(weighted(o))}</td><td className="px-3 py-3">{o.expected_decision_date || '—'}</td><td className="px-3 py-3">{o.created_date ? Math.floor((Date.now() - new Date(o.created_date).getTime()) / 86400000) + 'd' : '—'}</td><td className="px-3 py-3 capitalize">{o.status}</td></tr>)}</tbody></table></div>}
    {more && <Button variant="outline" disabled={loading} onClick={() => load(cursor)}>{loading ? 'Loading…' : 'Load more'}</Button>}
  </div>;
}