import React from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { useAuth } from '@/lib/AuthContext';
import FinanceDashboardContent from '@/components/finance/FinanceDashboardContent';
import FinanceForecast from '@/components/finance/FinanceForecast.jsx';
import { financeCall } from '@/components/finance/financeClient';
import '@/components/finance/finance-briefing.css';
export default function FinanceDashboard(){
 const {user}=useAuth(),q=useQuery({queryKey:['finance-status'],queryFn:()=>financeCall({action:'status'}),refetchInterval:query=>query.state.data?.sync?.status==='running'?5000:false});
 return <div className="finance-briefing"><div className="finance-briefing-header"><div><h1 className="font-heading text-2xl font-semibold">Finance dashboard</h1><p className="mt-1 text-sm text-muted-foreground">Dataverse purchase-order commitments, line-item costs and sales-invoice records.</p></div><div className="finance-header-actions">{q.data?.report?.url&&<a href={q.data.report.url} target="_blank" rel="noopener noreferrer" className="finance-button finance-button-primary">Open Power BI report</a>}{user?.role==='admin'&&<Link to="/admin/finance" className="finance-button finance-button-accent">Reporting setup & project links</Link>}</div></div>{q.isPending&&<p role="status">Checking reporting connection…</p>}{q.error&&<p role="alert" className="text-destructive">{q.error.message}</p>}{q.data&&!q.data.confirmed&&<section className="finance-card finance-accent"><h2 className="font-heading text-lg font-semibold">Finance data is syncing</h2><p className="mt-2 text-sm text-muted-foreground">{q.data.sync?.status==='error'?`Sync paused: ${q.data.sync.error}`:q.data.sync?'All finance tables must finish before the first snapshot is published.':'An administrator can start the Dataverse finance sync in Reporting setup.'} No provisional or invented figures are displayed.</p></section>}{q.data?.confirmed&&<><p className="finance-small mb-4">Confirmed source: {q.data.report.name}. Finance data and mappings are restricted to administrators, finance staff and directors.</p><FinanceDashboardContent snapshot={q.data.sync?.active_generation}/></>}{!q.data?.confirmed&&<FinanceForecast/>}</div>;
}