import React from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { useAuth } from '@/lib/AuthContext';
import FinanceDashboardContent from '@/components/finance/FinanceDashboardContent';
import FinanceForecast from '@/components/finance/FinanceForecast.jsx';
import { financeCall } from '@/components/finance/financeClient';
export default function FinanceDashboard(){
 const {user}=useAuth(),q=useQuery({queryKey:['finance-status'],queryFn:()=>financeCall({action:'status'}),refetchInterval:query=>query.state.data?.sync?.status==='running'?5000:false});
 return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="font-heading text-2xl font-semibold">Finance dashboard</h1><p className="mt-1 text-sm text-muted-foreground">Dataverse purchase-order commitments, line-item costs and sales-invoice records.</p></div><div className="flex flex-wrap gap-3">{q.data?.report?.url&&<a href={q.data.report.url} target="_blank" rel="noopener noreferrer" className="rounded-md border border-border bg-card px-4 py-2 text-sm font-semibold">Open Power BI report</a>}{user?.role==='admin'&&<Link to="/admin/finance" className="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Reporting setup & project links</Link>}</div></div>{q.isPending&&<p role="status">Checking reporting connection…</p>}{q.error&&<p role="alert" className="text-destructive">{q.error.message}</p>}{q.data&&!q.data.confirmed&&<section className="rounded-panel border border-border bg-card p-8"><h2 className="font-heading text-lg font-semibold">Finance data is syncing</h2><p className="mt-2 text-sm text-muted-foreground">{q.data.sync?.status==='error'?`Sync paused: ${q.data.sync.error}`:q.data.sync?'All finance tables must finish before the first snapshot is published.':'An administrator can start the Dataverse finance sync in Reporting setup.'} No provisional or invented figures are displayed.</p></section>}{q.data?.confirmed&&<><p className="text-sm text-muted-foreground">Confirmed source: {q.data.report.name}. Finance data and mappings are restricted to administrators, finance staff and directors.</p><FinanceDashboardContent snapshot={q.data.sync?.active_generation}/></>}<FinanceForecast/></div>;
}