import React,{useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Users,Star,Flag,BriefcaseBusiness,Search,List,LayoutGrid,Plus} from 'lucide-react';
import {base44} from '@/api/base44Client';
import {useAuth} from '@/lib/AuthContext';
import {Button} from '@/components/ui/button';
import WorkspaceMetrics from '@/components/relationships/WorkspaceMetrics';
import PeopleFilters from '@/components/relationships/PeopleFilters';
import PeopleResults from '@/components/relationships/PeopleResults';
import AddPersonDialog from '@/components/relationships/AddPersonDialog';
import WorkspacePageHeader from '@/components/layout/WorkspacePageHeader';
export default function People() {
  const {user}=useAuth(),[filters,setFilters]=useState({}),[search,setSearch]=useState(''),[cursor,setCursor]=useState(null),[trail,setTrail]=useState([]),[open,setOpen]=useState(false),[view,setView]=useState(()=>localStorage.getItem('alsight-people-view') || 'list');
  useEffect(()=>{const timer=setTimeout(()=>setFilters(f=>(f.search || '')===search ? f : {...f,search}),400);return()=>clearTimeout(timer);},[search]);
  useEffect(()=>{setCursor(null);setTrail([]);},[JSON.stringify(filters)]);
  const query=useQuery({queryKey:['people-workspace','organisation-contact-links',user?.id,user?.role,filters,cursor],enabled:!!user?.id,queryFn:async()=>{const {data}=await base44.functions.invoke('getRelationshipWorkspace',{filters,cursor}).catch(error=>{throw new Error(error.response?.data?.error || error.message || 'Unable to load People.');});if(data.error) throw new Error(data.error);return data;},staleTime:60000,retry:false,refetchOnMount:true,refetchOnWindowFocus:false});
  const m=query.data?.metrics || {},items=[{key:'',label:'Total people',value:m.total,icon:Users},{key:'decision',label:'Key Decision-Makers',value:m.decision,icon:Star},{key:'attention',label:'Need Attention',value:m.attention,icon:Flag,tone:'bg-primary/10 text-primary'},{key:'live',label:'Linked to live opportunities',value:m.live,icon:BriefcaseBusiness,tone:'bg-success/10 text-success'}];
  const changeView=v=>{setView(v);localStorage.setItem('alsight-people-view',v);};
  return <div className="space-y-5"><WorkspacePageHeader title="People" eyebrow="Relations 360" description="The people we know. The relationships we build. What happens next." image="https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1800&q=85" imageAlt="People collaborating around a table" actions={user?.role==='admin' && <Button onClick={()=>setOpen(true)}><Plus/>Add person</Button>} /><WorkspaceMetrics items={items} selected={filters.focus || ''} onSelect={focus=>setFilters(f=>({...f,focus}))}/><section className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><label className="relative w-full sm:max-w-lg"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input aria-label="Search people" className="h-10 w-full rounded-lg border border-input bg-card pl-10 pr-3 text-sm" placeholder="Search name, job title, organisation, email or role…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="flex rounded-lg border border-border bg-card p-1">{[['list',List,'List'],['cards',LayoutGrid,'Cards']].map(([v,Icon,label])=><Button key={v} variant={view===v ? 'default' : 'ghost'} size="sm" aria-pressed={view===v} onClick={()=>changeView(v)}><Icon/>{label}</Button>)}</div></div><PeopleFilters filters={filters} onChange={f=>{if(!Object.keys(f).length)setSearch('');setFilters(f);}}/></section>{query.isPending ? <p className="py-16 text-center text-sm text-muted-foreground" role="status">Loading your relationship workspace…</p> : query.error ? <p role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card p-5 text-sm text-destructive"><span>{query.error.message}</span><Button type="button" size="sm" variant="outline" disabled={query.isFetching} onClick={()=>query.refetch()}>{query.isFetching ? 'Retrying…' : 'Try again'}</Button></p> : <PeopleResults rows={query.data.rows} view={view}/>}<div className="flex items-center justify-between text-xs text-muted-foreground"><span>Only people and relationship context you are authorised to view.</span><div className="flex gap-2">{trail.length>0 && <Button size="sm" variant="outline" onClick={()=>{setCursor(trail.at(-1));setTrail(t=>t.slice(0,-1));}}>Previous</Button>}{query.data?.page.has_more && <Button size="sm" variant="outline" onClick={()=>{setTrail(t=>[...t,cursor]);setCursor(query.data.page.next_cursor);}}>Next people</Button>}</div></div><AddPersonDialog open={open} onOpenChange={setOpen}/></div>;
}