import React from 'react';
import { Download, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import HandoverApplicability from '@/components/handover/HandoverApplicability';

export default function HandoverPackHeader({ pack, authorised, editable, busy, onAction, onRefresh, onDownload }) {
  return <div className="space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-3xl font-semibold">{pack.percentage}% <span className="text-sm font-normal text-muted-foreground">dataset complete · {pack.completed} of {pack.required}</span></p><p className="mt-1 text-xs text-muted-foreground">Started by {pack.startedBy} · {new Date(pack.startedAt).toLocaleString('en-GB')}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={onRefresh}><RefreshCw />Recheck</Button><Button variant="outline" disabled={busy} onClick={() => onDownload('pdf')}><Download />PDF report</Button><Button variant="outline" disabled={busy} onClick={() => onDownload('zip')}><Download />Document bundle (ZIP)</Button></div></div>
    <Progress value={pack.percentage} aria-label="Handover dataset completeness" />
    <div className="space-y-2 rounded-lg border border-border p-3"><p className={`text-sm font-semibold ${pack.ready ? 'text-foreground' : 'text-destructive'}`}>{pack.ready ? 'Handover gateway ready — recorded evidence' : 'Handover gateway not ready'}</p><p className="text-xs text-destructive">{pack.statutoryOutstanding} statutory / applicability requirements outstanding</p><p className="text-xs text-als-navy-light">{pack.contractualOutstanding} contractual requirements outstanding</p><p className="text-xs text-muted-foreground">{pack.projectOutstanding} project close-out requirements outstanding · {pack.notApplicable} assessed not applicable</p><p className="text-xs text-muted-foreground">No proceed-with-exception override for statutory duties. Contractual PC and lawful occupation require separate competent assessment.</p>{pack.applicability === 'applies' && <p className="text-xs text-destructive">Higher-risk-building regime applies: a separate full BSR / golden-thread review is required. This baseline cannot clear that gateway.</p>}</div>
    <p className="text-xs text-muted-foreground">Checked {new Date(pack.checkedAt).toLocaleString('en-GB')}. ZIP includes current private documents, the report and a manifest with file integrity hashes; external document links remain references, not copied files. Limits: 10 MB per document, 20 MB per bundle.</p>
    <HandoverApplicability itemKey="golden_thread" title="England higher-risk-building / golden-thread regime" decision={pack.goldenThreadDecision} authorised={authorised} busy={busy} onAction={onAction} />
    <p className="text-xs text-muted-foreground">{pack.disclaimer} <a href={pack.guidance} target="_blank" rel="noreferrer" className="underline">BSR guidance</a></p>
  </div>;
}