import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {Button} from '@/components/ui/button';
import AlliancePanel from '@/components/alliance/AlliancePanel';
import PulseForm from '@/components/alliance/PulseForm';
import allianceRequest,{allianceError} from '@/components/alliance/allianceClient';
export default function AlliancePulse({data,user,onRefresh,onMore,loadingMore,hasMore}) {
  const [adding,setAdding]=useState(false),[error,setError]=useState(''),[removing,setRemoving]=useState(false);
  const remove=async item=>{if(!window.confirm('Remove this Alliance update from Pulse and Stories?')) return;setRemoving(true);setError('');try{await allianceRequest('remove',{kind:'pulse',id:item.id});onRefresh();}catch(e){setError(allianceError(e));}finally{setRemoving(false);}};
  const events=[...(data.pulse || []),...(data.milestones || []).map(p=>({id:`completion-${p.id}`,type:'Completion',title:`${p.name} · practical completion recorded`,summary:'The recorded practical completion date has been reached.',created_date:p.practical_completion_date,href:`/projects/${p.id}?tab=general`,system:true})),...(data.lessons || []).map(l=>({id:`knowledge-${l.id}`,type:'Knowledge',title:`Learning from ${l.project_name}`,summary:l.what_happened,created_date:l.created_date,href:l.href,author_name:l.author_name,system:true}))].sort((a,b)=>new Date(b.created_date)-new Date(a.created_date));
  return <AlliancePanel title="Alliance Pulse" eyebrow="People & moments" action={<Button size="sm" variant="outline" onClick={()=>setAdding(true)}>Add update</Button>}><div className={removing ? 'pointer-events-none space-y-5 opacity-60' : 'space-y-5'}>{events.map(item=><article key={item.id} className="min-w-0 border-b border-border pb-4 last:border-b-0"><p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">{item.type}</p><h3 className="mt-1 break-words text-sm font-bold">{item.title}</h3><p className="mt-2 whitespace-pre-line break-words text-sm leading-relaxed text-muted-foreground">{item.summary}</p><p className="mt-2 text-[11px] text-muted-foreground">{item.author_name ? `${item.author_name} · ` : ''}{new Date(item.created_date).toLocaleDateString('en-GB')}</p><div className="mt-2 flex flex-wrap justify-between gap-2">{item.href && <Link className="text-xs font-semibold underline underline-offset-4" to={item.href}>{item.related_entity_type==='person' ? 'View person' : item.related_entity_type==='lesson' || item.type==='Knowledge' ? 'View lesson' : item.type==='Impact' ? 'View project impact' : 'View project'}</Link>}{!item.system && (user.id===item.author_id || ['admin','director'].includes(user.role)) && <button className="text-xs text-muted-foreground underline" onClick={()=>remove(item)}>Remove update</button>}</div></article>)}{!events.length && <p className="text-sm text-muted-foreground">No Alliance moments have been shared yet. Add a real project milestone, team update or recognition.</p>}</div>{hasMore && <Button size="sm" variant="ghost" className="mt-4" disabled={loadingMore} onClick={onMore}>{loadingMore ? 'Loading…' : 'More updates'}</Button>}{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}{adding && <PulseForm onClose={()=>setAdding(false)} onSaved={()=>{setAdding(false);onRefresh();}}/>}</AlliancePanel>;
}