import React,{useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Textarea} from '@/components/ui/textarea';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {JOURNEY_STAGES} from '@/components/delivery/deliveryJourneyProgress';
import {LESSON_PROMPTS,IMPACT_THEMES} from '@/components/alliance/allianceOptions';
import {regionName} from '@/lib/portal';
import allianceRequest,{allianceError} from '@/components/alliance/allianceClient';
export default function LessonForm({project,stage='',onClose,onSaved}) {
  const [value,setValue]=useState({pathway_stage:stage,riba_stage:'',project_type:'',theme:'',...Object.fromEntries(LESSON_PROMPTS.map(([key])=>[key,'']))}),[saving,setSaving]=useState(false),[error,setError]=useState('');
  const set=(key,text)=>setValue(current=>({...current,[key]:text}));
  const submit=async event=>{event.preventDefault();setSaving(true);setError('');try{await allianceRequest('lessonAdd',{projectId:project.id,lesson:value});onSaved();}catch(e){setError(allianceError(e));}finally{setSaving(false);}};
  return <Dialog open onOpenChange={open=>{if(!open && !saving) onClose();}}><DialogContent className="max-h-[90dvh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>Add lesson</DialogTitle><DialogDescription>{project.name} · {regionName(project.department_id) || 'Region not recorded'}. A few sentences are enough; only “What happened” is required.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Project Pathway stage<select className="mt-1 w-full rounded-md border border-input bg-card p-2 text-sm" value={value.pathway_stage} onChange={e=>set('pathway_stage',e.target.value)}><option value="">Not specified</option>{JOURNEY_STAGES.map(s=><option key={s.id}>{s.label}</option>)}</select></label><label className="text-xs font-semibold">RIBA stage<select className="mt-1 w-full rounded-md border border-input bg-card p-2 text-sm" value={value.riba_stage} onChange={e=>set('riba_stage',e.target.value)}><option value="">Not specified</option>{Array.from({length:8},(_,i)=><option key={i}>RIBA {i}</option>)}</select></label><label className="text-xs font-semibold">Project type<Input className="mt-1" value={value.project_type} maxLength={100} placeholder="e.g. Pool refurbishment" onChange={e=>set('project_type',e.target.value)}/></label><label className="text-xs font-semibold">Theme<Input className="mt-1" list="alliance-lesson-themes" value={value.theme} maxLength={100} placeholder="e.g. Stakeholder engagement" onChange={e=>set('theme',e.target.value)}/><datalist id="alliance-lesson-themes">{IMPACT_THEMES.map(t=><option key={t} value={t}/>)}</datalist></label></div>{LESSON_PROMPTS.map(([key,label],i)=><label key={key} className="block text-xs font-semibold">{label}{i===0 ? ' *' : ' (optional)'}<Textarea className="mt-1 min-h-16" maxLength={2000} required={i===0} value={value[key]} onChange={e=>set(key,e.target.value)}/></label>)}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="ghost" disabled={saving} onClick={onClose}>Cancel</Button><Button disabled={saving}>{saving ? 'Saving…' : 'Save lesson'}</Button></div></form></DialogContent></Dialog>;
}