import React,{useState} from 'react';
import {useInfiniteQuery,useQueryClient} from '@tanstack/react-query';
import {useAuth} from '@/lib/AuthContext';
import {INTERNAL_ROLES} from '@/lib/portal';
import {Button} from '@/components/ui/button';
import AlliancePanel from '@/components/alliance/AlliancePanel';
import LessonForm from '@/components/alliance/LessonForm';
import LessonEntry from '@/components/alliance/LessonEntry';
import allianceRequest,{allianceError,refreshAlliance} from '@/components/alliance/allianceClient';
export default function ProjectLessons({project,stage=''}) {
  const {user}=useAuth(),cache=useQueryClient(),[adding,setAdding]=useState(false),[related,setRelated]=useState(false),[error,setError]=useState(''),[removing,setRemoving]=useState(false);
  const query=useInfiniteQuery({queryKey:['alliance-layer','lessons',user?.id,user?.role,project.id,related],enabled:INTERNAL_ROLES.includes(user?.role),initialPageParam:null,queryFn:({pageParam})=>allianceRequest('lessons',{projectId:project.id,related,cursor:pageParam}),getNextPageParam:page=>page.has_more ? page.next_cursor : undefined,staleTime:60000});
  if(!INTERNAL_ROLES.includes(user?.role)) return null;
  const remove=async lesson=>{if(!window.confirm('Remove this recorded lesson?')) return;setRemoving(true);setError('');try{await allianceRequest('remove',{kind:'lesson',id:lesson.id});refreshAlliance(cache);}catch(e){setError(allianceError(e));}finally{setRemoving(false);}};
  return <AlliancePanel id={stage ? undefined : 'project-lessons'} title="WHAT WE’VE LEARNED" eyebrow={stage ? `Project Pathway · ${stage}` : 'Alliance knowledge, built together'} action={<Button size="sm" variant="outline" onClick={()=>setAdding(true)}>Add lesson</Button>}><p className="mb-4 text-sm text-muted-foreground">Real experience, shared for human judgement. {related ? 'Similar projects are matched by recorded region or purpose themes.' : 'Capture what happened and what the team learned.'}</p><div className="mb-4 flex flex-wrap gap-2"><Button size="sm" variant={!related ? 'secondary' : 'ghost'} onClick={()=>setRelated(false)}>This project{query.data && !related ? ` (${query.data.pages[0].total})` : ''}</Button><Button size="sm" variant={related ? 'secondary' : 'ghost'} onClick={()=>setRelated(true)}>Lessons from similar projects</Button></div>{query.isPending ? <p role="status" className="text-sm text-muted-foreground">Loading lessons…</p> : query.error ? <p role="alert" className="text-sm text-destructive">{allianceError(query.error)} <button className="underline" onClick={()=>query.refetch()}>Try again</button></p> : <div className={removing ? 'pointer-events-none space-y-3 opacity-60' : 'space-y-3'}>{query.data.pages.flatMap(page=>page.items).map(lesson=><LessonEntry key={lesson.id} lesson={lesson} user={user} onRemove={remove}/>)}{!query.data.pages.some(page=>page.items.length>0) && <p className="text-sm text-muted-foreground">{related ? 'No accessible lessons match this project’s recorded region or purpose themes yet.' : 'No lessons have been captured for this project yet.'}</p>}{query.hasNextPage && <Button variant="ghost" size="sm" disabled={query.isFetchingNextPage} onClick={()=>query.fetchNextPage()}>{query.isFetchingNextPage ? 'Loading…' : 'View more lessons'}</Button>}</div>}{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}{adding && <LessonForm project={project} stage={stage} onClose={()=>setAdding(false)} onSaved={()=>{refreshAlliance(cache);setAdding(false);}}/>}</AlliancePanel>;
}