import React,{useState} from 'react';
import {useInfiniteQuery,useQueryClient} from '@tanstack/react-query';
import {Lock,Plus,Users} from 'lucide-react';
import {Button} from '@/components/ui/button';
import PulseGroupCreate from '@/components/alliance/PulseGroupCreate';
import allianceRequest,{allianceError,refreshAlliance} from '@/components/alliance/allianceClient';
export default function PulseGroupNav({user,groupId,onSelect}) {
  const cache=useQueryClient(),[creating,setCreating]=useState(false);
  const query=useInfiniteQuery({queryKey:['alliance-layer','groups',user.id],initialPageParam:null,queryFn:({pageParam})=>allianceRequest('groups',{cursor:pageParam}),getNextPageParam:page=>page.has_more ? page.next_cursor : undefined,staleTime:30000,refetchOnWindowFocus:true});
  const canCreate=['admin','director','regional_director'].includes(user.role);
  return <aside aria-label="Pulse groups" className="min-w-0 space-y-4 rounded-panel border border-border bg-card p-4"><h2 className="flex items-center gap-2 text-sm font-bold"><Users className="h-4 w-4"/>Alliance & groups</h2><button type="button" aria-pressed={!groupId} onClick={()=>onSelect('')} className={`w-full rounded-lg px-3 py-2 text-left text-sm font-semibold ${!groupId ? 'bg-primary/15' : 'hover:bg-muted'}`}>All Alliance</button><div className="space-y-1">{query.isPending ? <p role="status" className="text-xs text-muted-foreground">Loading your groups…</p> : query.error ? <p role="alert" className="text-xs text-destructive">{allianceError(query.error)} <button type="button" onClick={()=>query.refetch()} className="underline">Try again</button></p> : query.data.pages.flatMap(page=>page.items).map(group=><button key={group.id} type="button" aria-pressed={groupId===group.id} onClick={()=>onSelect(group.id)} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm ${groupId===group.id ? 'bg-primary/15 font-bold' : 'hover:bg-muted'}`}><Lock className="h-3.5 w-3.5 shrink-0"/><span className="break-words">{group.name}</span></button>)}{query.data && !query.data.pages[0].items.length && <p className="px-3 py-2 text-xs text-muted-foreground">You haven’t been invited to any groups yet.</p>}</div>{query.hasNextPage && <Button type="button" variant="ghost" size="sm" disabled={query.isFetchingNextPage} onClick={()=>query.fetchNextPage()}>{query.isFetchingNextPage ? 'Loading…' : 'More groups'}</Button>}{canCreate && (creating ? <PulseGroupCreate onCancel={()=>setCreating(false)} onCreated={group=>{setCreating(false);refreshAlliance(cache);onSelect(group.id);}}/> : <Button type="button" size="sm" variant="outline" className="w-full" onClick={()=>setCreating(true)}><Plus/>Create group</Button>)}<p className="border-t border-border pt-3 text-xs leading-relaxed text-muted-foreground">Groups are invite-only. Departmental messages stay in their group, not the Alliance-wide feed.</p></aside>;
}