import React,{useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {PULSE_TYPES} from '@/components/alliance/allianceOptions';
import PulseRecordPicker from '@/components/alliance/PulseRecordPicker';
import PulseImageUpload from '@/components/alliance/PulseImageUpload';
import allianceRequest,{allianceError} from '@/components/alliance/allianceClient';
export default function PulseForm({onClose,onSaved}) {
  const [value,setValue]=useState({type:'Team news',title:'',summary:'',images:[],related_entity_type:'none',related_entity_id:'',is_story:false}),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');
  const set=(key,text)=>setValue(current=>({...current,[key]:text}));
  const submit=async e=>{e.preventDefault();if(uploading || saving) return;setSaving(true);setError('');try{await allianceRequest('pulseAdd',{item:value});onSaved();}catch(e){setError(allianceError(e));}finally{setSaving(false);}};
  return <Dialog open onOpenChange={open=>{if(!open && !saving && !uploading) onClose();}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Add Alliance update</DialogTitle><DialogDescription>A real moment, shared internally. Keep it factual and link to the source record where appropriate.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><label className="block text-xs font-semibold">Update type<select className="mt-1 w-full rounded-md border border-input bg-card p-2 text-sm" value={value.type} onChange={e=>set('type',e.target.value)}>{PULSE_TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label className="block text-xs font-semibold">Title<Input className="mt-1" value={value.title} required maxLength={200} onChange={e=>set('title',e.target.value)}/></label><label className="block text-xs font-semibold">What happened<Textarea className="mt-1 min-h-28" value={value.summary} required maxLength={1500} onChange={e=>set('summary',e.target.value)} placeholder="Share what happened. Add hashtags such as #Community or #TeamNews."/></label><p className="text-xs text-muted-foreground">Include #hashtags in your title or update to connect related posts.</p><PulseImageUpload images={value.images} onChange={images=>set('images',images)} onBusyChange={setUploading} disabled={saving}/><label className="block text-xs font-semibold">Link to<select className="mt-1 w-full rounded-md border border-input bg-card p-2 text-sm" value={value.related_entity_type} onChange={e=>setValue(current=>({...current,related_entity_type:e.target.value,related_entity_id:''}))}><option value="none">General team update</option><option value="project">Project / project impact</option><option value="person">Person</option><option value="lesson">Lesson</option></select></label>{value.related_entity_type!=='none' && <PulseRecordPicker key={value.related_entity_type} kind={value.related_entity_type} value={value.related_entity_id} onChange={id=>set('related_entity_id',id)}/>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.is_story} onChange={e=>set('is_story',e.target.checked)}/>Feature in Alliance Stories</label><p className="text-xs text-muted-foreground">Stories must link to an existing ALSight record. Visibility follows its access permissions.</p>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" disabled={saving || uploading} variant="ghost" onClick={onClose}>Cancel</Button><Button disabled={saving || uploading}>{saving ? 'Publishing…' : uploading ? 'Uploading images…' : 'Publish update'}</Button></div></form></DialogContent></Dialog>;
}