import React,{useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {IMPACT_THEMES} from '@/components/alliance/allianceOptions';
import allianceRequest,{allianceError} from '@/components/alliance/allianceClient';
import PurposeResearch from '@/components/alliance/PurposeResearch';
export default function PurposeForm({project,onClose,onSaved,startResearch=false}) {
  const [purpose,setPurpose]=useState(project.why_this_matters || ''),[themes,setThemes]=useState(project.impact_themes || []),[saving,setSaving]=useState(false),[researching,setResearching]=useState(false),[error,setError]=useState('');
  const submit=async event=>{event.preventDefault();if(researching || saving) return;setSaving(true);setError('');try {const result=await allianceRequest('purposeSave',{projectId:project.id,purpose:{why_this_matters:purpose,impact_themes:themes}});onSaved(result.project);}catch(e){setError(allianceError(e));}finally{setSaving(false);}};
  return <Dialog open onOpenChange={open=>{if(!open && !saving && !researching) onClose();}}><DialogContent className="max-h-[85dvh] overflow-y-auto"><DialogHeader><DialogTitle>Why this matters</DialogTitle><DialogDescription>Write your own purpose, or review an ALICE research draft. Check its sources and wording before saving; contextual statistics are not delivered project outcomes.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><fieldset disabled={saving} className="min-w-0 space-y-4"><PurposeResearch projectId={project.id} autoStart={startResearch} onBusyChange={setResearching} onApply={draft=>{if(purpose.trim() && !window.confirm('Replace the current purpose draft with ALICE’s researched draft? Nothing is saved until you choose Save purpose.')) return false;setPurpose(draft);return true;}}/><label className="block text-sm font-semibold">Project purpose<Textarea className="mt-2 min-h-32" value={purpose} maxLength={4000} onChange={e=>setPurpose(e.target.value)}/></label>{project.description && <details className="rounded-lg bg-muted p-3 text-sm"><summary className="cursor-pointer font-semibold">Existing project brief</summary><p className="mt-2 whitespace-pre-line break-words text-muted-foreground">{project.description}</p><Button type="button" size="sm" variant="outline" className="mt-3" onClick={()=>setPurpose(project.description.slice(0,4000))}>Use brief as a starting point</Button></details>}<fieldset><legend className="mb-2 text-sm font-semibold">Supporting themes</legend><div className="flex flex-wrap gap-3">{IMPACT_THEMES.map(theme=><label key={theme} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={themes.includes(theme)} onChange={e=>setThemes(current=>e.target.checked ? [...current,theme] : current.filter(t=>t!==theme))}/>{theme}</label>)}</div></fieldset>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="ghost" disabled={saving || researching} onClick={onClose}>Cancel</Button><Button disabled={saving || researching}>{saving ? 'Saving…' : 'Save purpose'}</Button></div></fieldset></form></DialogContent></Dialog>;
}