import React from 'react';
import {Link} from 'react-router-dom';
import ApprovalDataverseFields from '@/components/approvals/ApprovalDataverseFields.jsx';
const steps=[
 ['Confirmed document scope','Include Legal Documents, DMA agreements and Warranties. Create a separate Dataverse trigger flow for each table. In Administration → Dataverse, identify the actual table name, row GUID column, drafted-date column and result columns. Use Dataverse logical column names, not ALSight labels.'],
 ['Give the approver access','Open People → the person → Portal Account and tick Approval access. The permission can be prepared for an invited person, but they must sign in with that email to use it. Only administrators can grant or revoke it.'],
 ['Confirm the approval rules','Approver selection has been deferred and no default approver will be assigned. When ready, confirm where the approver comes from, whether one or several people must approve, what counts as a new draft, and which fixed document version they review. These are needed before connecting the receiver.'],
 ['Prepare secure connections','Your Microsoft administrator should confirm Power Automate licensing, Dataverse permissions and organisation policies for HTTP actions. Agree authentication for both directions; store ALSight credentials in Secrets and protect HTTP inputs/outputs in flow run history. Never paste secrets into document links or browser code.'],
 ['Create the outbound automated cloud flow','In Power Automate, create an Automated cloud flow. Choose Microsoft Dataverse → When a row is added, modified or deleted. Set Change type to Modified, choose the document table and select the scope your service account is authorised to monitor. Use Organisation only if that is intended and permitted.'],
 ['Filter the drafted-date trigger','In Select columns, enter bss_drafteddate. In Filter rows, enter bss_drafteddate ne null if cleared dates should not trigger approval. Do not include $filter=. This trigger also fires when the same value is submitted, so filtering alone is not change detection.'],
 ['Add genuine-change and duplicate checks','Compare the drafted date with a durable last-submitted value for that row. Stop if it is unchanged. Keep a stable request key across retries. Do not use a fresh random ID on every retry or modifiedon alone as proof that the drafted date changed. Decide how date clearing and re-drafting are handled before enabling this step.'],
 ['Read and send the approval context','Use Get a row by ID and resolve the assigned approver. Then add an HTTP POST to the authenticated ALSight receiver once it is built. Send the table identifier, row GUID, draft timestamp, source version, stable request key, document title, fixed-version document reference and approver email. The receiver URL and exact payload will be supplied when implemented; no live receiver exists yet. Only advance last-submitted tracking after successful receipt.'],
 ['Create the return flow','Create a separate flow using When an HTTP request is received. Restrict and authenticate its callers. Receive the correlated request ID, table, row GUID, draft/version, decision, approver, decision time and comments. Match its authentication to what ALSight can actually send; do not assume an anonymous URL is sufficient or that ALSight already has an Entra token.'],
 ['Validate and write the result','Use Get a row by ID to verify the request still belongs to the current draft/document version. Ignore duplicate decisions and reject stale ones. Use Update a row to set bss_approvalstatus to the agreed approval-result text, bss_approversname to the approver name, bss_approvaldate to the decision date and bss_approvalcomments to the comments. Do not change the drafted-date field. Return confirmation only after the update succeeds.'],
 ['Connect ALSight to the return flow','After the return flow exists, supply its address securely and configure ALSight decision delivery and bounded retries. ALSight must show a decision as awaiting write-back until Dataverse confirms it; approval access never grants general Dataverse editing permissions. This delivery and the decision controls are the next implementation stage.'],
 ['Publish and check the round trip','Publish the ALSight receiver before enabling the outbound flow. Use a permitted test document and confirm: one request for a new draft, assigned-person visibility, approved/rejected result write-back, safe duplicate retries, outdated-draft rejection and revoked-access denial. Use the Testing Agent for the ALSight portal checks and Power Automate run history for the Microsoft side.']
];
export default function PowerAutomateSetupGuide() {
 return <section className="space-y-5 rounded-panel border border-border bg-card p-6">
  <div><h2 className="font-heading text-xl font-semibold">Power Automate approval setup</h2><p className="mt-2 text-sm text-muted-foreground">Access controls and the assigned approval inbox are built. The authenticated receiver, decision controls and Dataverse result delivery are not connected yet. Prepare the flows below, but leave them disabled until those parts are ready.</p></div>
  <ApprovalDataverseFields/>
  <ol className="space-y-5">{steps.map(([title,description],index)=><li key={title} className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-secondary text-sm font-semibold">{index+1}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{description}</p></div></li>)}</ol>
  <div className="flex flex-wrap gap-4 text-sm"><Link to="/people" className="font-semibold underline">Manage approval access</Link><a href="https://learn.microsoft.com/en-us/power-automate/dataverse/create-update-delete-trigger" target="_blank" rel="noopener noreferrer" className="underline">Microsoft trigger reference</a></div>
 </section>;
}