import React from 'react';
import {Link} from 'react-router-dom';
import ApprovalDataverseFields from '@/components/approvals/ApprovalDataverseFields.jsx';
const steps=[
 ['Confirmed document scope','Include Legal Documents, DMA agreements and Warranties. Create a separate Dataverse trigger flow for each table. In Administration → Dataverse, identify the actual table name, row GUID column, drafted-date column and result columns. Use Dataverse logical column names, not ALSight labels.'],
 ['Give the approver access','Open People → the person → Portal Account and tick Approval access. The permission can be prepared for an invited person, but they must sign in with that email to use it. Only administrators can grant or revoke it.'],
 ['Configure table routing','Use Approval process mapping above to choose named people or linked project contacts for each supported table, then save the rule. Check recipients against a document before applying it. Automatic sync and the authenticated receiver both use these saved rules. Repeated roles resolving to the same person create one request per draft. The first confirmed response completes the source document; this is not a unanimous multi-signature process.'],
 ['Prepare secure connections','Your Microsoft administrator should confirm Power Automate licensing, Dataverse permissions and organisation policies for HTTP actions. Agree authentication for both directions; store ALSight credentials in Secrets and protect HTTP inputs/outputs in flow run history. Never paste secrets into document links or browser code.'],
 ['Create the outbound automated cloud flow','In Power Automate, create an Automated cloud flow. Choose Microsoft Dataverse → When a row is added, modified or deleted. Set Change type to Modified, choose the document table and select the scope your service account is authorised to monitor. Use Organisation only if that is intended and permitted.'],
 ['Filter the drafted-date trigger','In Select columns, enter bss_drafteddate. In Filter rows, enter bss_drafteddate ne null if cleared dates should not trigger approval. Do not include $filter=. This trigger also fires when the same value is submitted, so filtering alone is not change detection.'],
 ['Add genuine-change and duplicate checks','Compare the drafted date with a durable last-submitted value for that row. Stop if it is unchanged. Keep a stable request key across retries. Do not use a fresh random ID on every retry or modifiedon alone as proof that the drafted date changed. Decide how date clearing and re-drafting are handled before enabling this step.'],
 ['Read and send the approval context','Use Get a row by ID. The saved table rule selects eligible approvers. POST to https://alsight.base44.app/functions/manageApprovalCentre with action = receive, table = documents / dma / warranties, sourceId = the document row GUID, version = the exact Dataverse @odata.etag, requestedAt, reason, requesterName, requesterRole and requesterEmail. Optional approverEmail must match a recipient resolved by the saved table rule. Calls must authenticate as an ALSight administrator; an anonymous HTTP request is rejected. The receiver verifies the source version, resolves the existing project/document and deduplicates repeated delivery. Only advance last-submitted tracking after successful receipt.'],
 ['Choose the decision return route','ALSight currently supports immediate direct Dataverse API write-back through the approver’s own connected Microsoft account. This requires an internal approver with Dataverse permissions. If your approvals need an application identity or Power Automate return flow for external approvers, leave live routing disabled until that separate connection is configured.'],
 ['Confirm document result mappings','Agree source result text before enabling live approvals. The direct API sends Approve, Approved - Subject to Comments or Further Review Required. In the existing Dataverse mappings, explicitly enable write-back for approval_status, approval_date, approval_comments and approvers_name after confirming these values and permissions. ALSight checks the original row version, writes only these four fields and reads the result back before showing success. It does not change the drafted date.'],
 ['Connect the approver’s Dataverse account','The internal approver connects Dataverse in Account Settings. Demo requests remain local-only. For live requests, failed write-back keeps the recorded decision and comment, shows that the source system has not confirmed it and offers Retry saved decision. Approval access does not grant Dataverse editing rights; Microsoft permissions are still enforced.'],
 ['Publish and check the round trip','Publish the ALSight receiver before enabling the outbound flow. Use a permitted test document and confirm: one request for a new draft, assigned-person visibility, approved/further-review result write-back, safe duplicate retries, outdated-draft rejection and revoked-access denial. Use the Testing Agent for the ALSight portal checks and Power Automate run history for the Microsoft side.']
];
export default function PowerAutomateSetupGuide() {
 return <section className="space-y-5 rounded-panel border border-border bg-card p-6">
  <div><h2 className="font-heading text-xl font-semibold">Power Automate approval setup</h2><p className="mt-2 text-sm text-muted-foreground">The document Approval Centre, authenticated request receiver, decision controls, audit history and guarded direct Dataverse write-back are implemented. Table-based approver routing is configured above and is used by automatic document sync and the request receiver. External Power Automate triggers and approval write-back mapping switches still need confirmation; demo requests remain clearly labelled.</p></div>
  <ApprovalDataverseFields/>
  <ol className="space-y-5">{steps.map(([title,description],index)=><li key={title} className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-secondary text-sm font-semibold">{index+1}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{description}</p></div></li>)}</ol>
  <div className="flex flex-wrap gap-4 text-sm"><Link to="/people" className="font-semibold underline">Manage approval access</Link><a href="https://learn.microsoft.com/en-us/power-automate/dataverse/create-update-delete-trigger" target="_blank" rel="noopener noreferrer" className="underline">Microsoft trigger reference</a></div>
 </section>;
}