import React,{useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {base44} from '@/api/base44Client';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
export default function FrameworkLinkDialog({row,onClose}) {
 const [term,setTerm]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),cache=useQueryClient();
 const query=useQuery({queryKey:['framework-link-projects',row.id,search],enabled:search.length>=2,queryFn:()=>base44.entities.Project.filter({procurement_route:{$ne:false},$or:['name','project_number'].map(field=>({[field]:{$regex:search.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),$options:'i'}}))},{sort:'name',limit:20,fields:['name','project_number']}),retry:false});
 const link=useMutation({mutationFn:async()=>{const {data}=await base44.functions.invoke('getStakeholderFrameworkReport',{workspaceAction:'link',reportId:row.id,projectId:selected.id});if(data.error)throw new Error(data.error);},onSuccess:()=>{cache.invalidateQueries({queryKey:['framework-workspace']});onClose();}});
 return <Dialog open onOpenChange={value=>{if(!value && !link.isPending)onClose();}}><DialogContent><DialogHeader><DialogTitle>Link to ALSight</DialogTitle><DialogDescription>{row.site || row.framework_ref} · Associate an existing accessible project. No new project will be created.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();setSelected(null);setSearch(term.trim());}} className="flex gap-2"><input aria-label="Find an ALSight project" className="min-w-0 flex-1 rounded-md border border-input bg-background p-2 text-sm" value={term} onChange={e=>setTerm(e.target.value)} placeholder="Project name or PROJ reference"/><Button disabled={term.trim().length<2}>Search</Button></form>{query.isFetching && <p role="status" className="text-sm">Finding accessible projects…</p>}{query.error && <p role="alert" className="text-sm text-destructive">{query.error.message}</p>}{query.data && <div className="max-h-64 space-y-2 overflow-y-auto">{!query.data.items.length && <p className="text-sm text-muted-foreground">No accessible projects match.</p>}{query.data.items.map(project=><button key={project.id} onClick={()=>setSelected(project)} aria-pressed={selected?.id===project.id} className={`block w-full rounded-lg border p-3 text-left text-sm ${selected?.id===project.id ? 'border-primary bg-primary/10' : 'border-border hover:bg-muted'}`}><strong>{project.project_number || 'No reference'}</strong><p>{project.name}</p></button>)}</div>}{selected && <p className="text-sm">Confirm linking this Framework record to <strong>{selected.project_number} · {selected.name}</strong>?</p>}{link.error && <p role="alert" className="text-sm text-destructive">{link.error.response?.data?.error || link.error.message}</p>}<div className="flex justify-end gap-2"><Button variant="outline" disabled={link.isPending} onClick={onClose}>Cancel</Button><Button disabled={!selected || link.isPending} onClick={()=>link.mutate()}>{link.isPending ? 'Linking…' : 'Confirm link'}</Button></div></DialogContent></Dialog>;
}