import React,{useState,useEffect} from 'react';
import {useQuery} from '@tanstack/react-query';
import {base44} from '@/api/base44Client';
export default function FrameworkWorkspaceFilters({filters,onChange,search,onSearch,user}) {
 const [clientSearch,setClientSearch]=useState(''),[clientTerm,setClientTerm]=useState('');
 useEffect(()=>{const timer=setTimeout(()=>setClientTerm(clientSearch.trim()),400);return()=>clearTimeout(timer);},[clientSearch]);
 const clients=useQuery({queryKey:['framework-clients',user?.id,user?.role,clientTerm],queryFn:async()=>{const {data}=await base44.functions.invoke('getStakeholderFrameworkReport',{workspaceAction:'clients',term:clientTerm});return data;},retry:false,staleTime:60000});
 const field=(key,label,choices)=><label className="flex flex-col gap-1 text-[10px] text-muted-foreground">{label}<select aria-label={label} value={filters[key] || ''} onChange={e=>onChange({...filters,[key]:e.target.value})} className="h-9 max-w-48 rounded-md border border-input bg-card px-2 text-xs text-foreground">{choices.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>;
 return <div className="flex flex-wrap items-end gap-3 px-5 pb-5"><label className="min-w-56 flex-1 text-[10px] text-muted-foreground">Find a Framework project<input aria-label="Search Framework projects" placeholder="Search site, client or project reference..." className="mt-1 h-9 w-full rounded-md border border-input bg-card px-3 text-xs text-foreground" value={search} onChange={e=>onSearch(e.target.value)}/></label>{field('stage','Milestone',[['','Any Milestone'],['pq_date','Questionnaire'],['aa_signed','Agreement'],['calloff_date','Call-Off'],['outcome','Delivery Outcome']])}{field('linked','Linked to ALSight',[['','All'],['linked','Linked'],['unlinked','Not Linked']])}<div className="flex flex-col gap-1"><label className="text-[10px] text-muted-foreground">Find client<input aria-label="Find client filter" className="ml-2 w-24 rounded border border-input bg-card px-1 text-xs text-foreground" value={clientSearch} onChange={e=>setClientSearch(e.target.value)} placeholder="Name..."/></label>{field('client','Client',[['','All clients'],...(clients.data?.items || []).filter(Boolean).map(value=>[value,value]),...(filters.client && !clients.data?.items?.includes(filters.client) ? [[filters.client,filters.client]] : [])])}{clients.error && <span role="alert" className="text-[10px] text-destructive">Client choices unavailable</span>}</div>{field('outcome','Outcome Status',[['','All'],['on_time','On Time'],['delayed','Delayed'],['to_budget','To Budget'],['missing','Outcome Missing'],['recorded','Outcome Recorded'],['review','Needs Review']])}{Object.values(filters).some(Boolean) && <button className="h-9 px-2 text-xs text-primary underline" onClick={()=>onChange({})}>Clear filters</button>}{filters.attention && <span className="rounded-full bg-primary/10 px-3 py-2 text-[10px]">{filters.attention==='agreements' ? 'Missing agreements' : 'Outstanding outcomes'}</span>}</div>;
}