import React,{useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {List,Map,Download} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {base44} from '@/api/base44Client';
import FrameworkWorkspaceFilters from '@/components/framework/FrameworkWorkspaceFilters';
import FrameworkWorkspaceTable from '@/components/framework/FrameworkWorkspaceTable';
import FrameworkWorkspaceMap from '@/components/framework/FrameworkWorkspaceMap';
import FrameworkLinkDialog from '@/components/framework/FrameworkLinkDialog';
import frameworkExport from '@/components/framework/frameworkExport';
import organisationQueryPolicy from '@/components/data/organisationQueryPolicy';
export default function FrameworkWorkspaceExplorer({filters,onFilter,search,onSearch,term,user}) {
 const [paging,setPaging]=useState({key:'',cursor:null,trail:[]}),[view,setView]=useState('list'),[selected,setSelected]=useState(null),[link,setLink]=useState(null),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState('');
 const key=JSON.stringify([filters,term]),current=paging.key===key ? paging : {key,cursor:null,trail:[]};
 const query=useQuery({queryKey:['framework-workspace','list',user?.id,user?.role,filters,term,current.cursor],queryFn:async()=>{const {data}=await base44.functions.invoke('getStakeholderFrameworkReport',{workspaceAction:'list',filters,term,...(current.cursor ? {cursor:current.cursor} : {})});if(data.error)throw new Error(data.error);return data;},enabled:!!user?.id,...organisationQueryPolicy,staleTime:60000});
 const rows=query.data?.rows || [];
 const download=async()=>{setExporting(true);setExportError('');try{await frameworkExport(filters,term);}catch(error){setExportError(error.response?.data?.error || error.message);}finally{setExporting(false);}};
 return <section id="framework-projects" className="scroll-mt-20 overflow-hidden rounded-panel border border-border bg-card shadow-sm"><header className="flex flex-wrap items-center justify-between gap-3 p-5"><h2 className="text-lg font-semibold">Framework Projects</h2><div className="flex items-center gap-3"><div className="flex rounded-md border border-border p-1">{[['list','List',List],['map','Map',Map]].map(([key,label,Icon])=><Button key={key} size="sm" variant={view===key ? 'default' : 'ghost'} aria-pressed={view===key} onClick={()=>{setView(key);setSelected(null);}}><Icon/>{label}</Button>)}</div><span className="text-xs text-muted-foreground">{rows.length} shown · {query.data?.count ?? '—'} matching</span><Button size="sm" variant="outline" disabled={exporting || query.isPending} onClick={download}><Download/>{exporting ? 'Exporting…' : 'Export'}</Button></div></header><FrameworkWorkspaceFilters filters={filters} onChange={onFilter} search={search} onSearch={onSearch} user={user}/>{exportError && <p role="alert" className="px-5 pb-3 text-sm text-destructive">{exportError}</p>}{query.isPending ? <p role="status" className="p-12 text-center text-sm text-muted-foreground">Loading Framework projects…</p> : query.error ? <p role="alert" className="p-5 text-sm text-destructive">{query.error.response?.data?.error || query.error.message} <button className="underline" onClick={()=>query.refetch()}>Try again</button></p> : !rows.length ? <p className="p-12 text-center text-sm text-muted-foreground">No Framework projects match these filters.</p> : view==='map' ? <FrameworkWorkspaceMap rows={rows} selected={selected}/> : <FrameworkWorkspaceTable rows={rows} canLink={user?.role==='admin'} onLink={setLink} onMap={id=>{setSelected(id);setView('map');}}/>}{!query.error && <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-border p-4"><p className="text-[10px] text-muted-foreground">Framework records only. Linked project details and locations respect your ALSight access.</p><div className="flex gap-2">{current.trail.length>0 && <Button size="sm" variant="outline" onClick={()=>setPaging({key,cursor:current.trail.at(-1),trail:current.trail.slice(0,-1)})}>Previous</Button>}{query.data?.has_more && <Button size="sm" variant="outline" onClick={()=>setPaging({key,cursor:query.data.next_cursor,trail:[...current.trail,current.cursor]})}>Next projects</Button>}</div></footer>}{link && <FrameworkLinkDialog row={link} onClose={()=>setLink(null)}/>}</section>;
}