import React,{useState} from 'react';
import {useMutation,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {aseV2Request} from '@/components/ase/v2/aseV2Client';
import {aseError} from '@/components/ase/aseClient';
export default function ASEV2Inputs({accountId}) {
  const cache=useQueryClient(),[type,setType]=useState('turnover'),[form,setForm]=useState({turnover_value:'',period_end:'',obtained_at:'',evidence_origin:'declared',evidence_reference:'',outcome:'satisfactory',event_date:'',verification_note:'',confirmed:false}),update=(key,value)=>setForm(f=>({...f,[key]:value}));
  const save=useMutation({mutationFn:()=>aseV2Request('saveInput',{accountId,input_type:type,...form,turnover_value:Number(form.turnover_value),annual_company_gbp:form.confirmed}),onSuccess:()=>cache.invalidateQueries({queryKey:['ase','v2']})});
  const field=(label,key,inputType='text')=><label className="text-xs">{label}<input type={inputType} required className="mt-1 w-full rounded-md border border-input bg-background p-2" value={form[key]} maxLength={500} onChange={e=>update(key,e.target.value)}/></label>;
  return <form onSubmit={e=>{e.preventDefault();save.mutate();}} className="rounded-lg border border-border p-4"><h3 className="font-semibold">Record verified Alliance evidence</h3><label className="mt-3 block text-xs">Evidence type<select className="mt-1 w-full rounded-md border border-input bg-background p-2" value={type} onChange={e=>{setType(e.target.value);save.reset();update('confirmed',false);}}><option value="turnover">Annual company turnover</option><option value="experience">Structured Alliance outcome</option></select></label>
    <div className="mt-3 grid gap-3 sm:grid-cols-2">{type==='turnover' ? <>{field('Annual company-only turnover, GBP','turnover_value','number')}{field('Accounts period end','period_end','date')}{field('Date obtained','obtained_at','date')}<label className="text-xs">Evidence origin<select className="mt-1 w-full rounded-md border border-input bg-background p-2" value={form.evidence_origin} onChange={e=>update('evidence_origin',e.target.value)}><option value="declared">Declared by organisation</option><option value="internal">Reviewed internal record</option><option value="external">Reviewed external document</option></select></label></> : <><label className="text-xs">Documented outcome<select className="mt-1 w-full rounded-md border border-input bg-background p-2" value={form.outcome} onChange={e=>update('outcome',e.target.value)}><option value="excellent">Formal excellent outcome</option><option value="satisfactory">Formal satisfactory outcome</option><option value="resolved_issue">Documented resolved issue</option><option value="unresolved_material">Material unresolved issue</option><option value="serious_unresolved">Serious unresolved issue</option></select></label>{field('Outcome date','event_date','date')}</>}{field('Document / ALSight evidence reference','evidence_reference')}{field('Verification note','verification_note')}</div>
    <label className="mt-3 flex items-start gap-2 text-xs"><input type="checkbox" checked={form.confirmed} onChange={e=>update('confirmed',e.target.checked)}/><span>{type==='turnover' ? 'I verified this is annual company-only GBP turnover, not group turnover or an estimate.' : 'I verified the structured source record. This is not a sentiment interpretation of casual notes.'}</span></label><Button className="mt-3" size="sm" disabled={!form.confirmed || save.isPending}>{save.isPending ? 'Saving evidence…' : 'Record evidence'}</Button>{save.error && <p role="alert" className="mt-2 text-xs text-destructive">{aseError(save.error)}</p>}{save.data && <p className="mt-2 text-xs text-success">Recorded: {save.data.saved.evidence_reference}. Re-run All Seeing Eye to incorporate it; published history is unchanged.</p>}
  </form>;
}