import React,{useState} from 'react';
import {useMutation,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {aseV2Request} from '@/components/ase/v2/aseV2Client';
import {aseError} from '@/components/ase/aseClient';
export default function ASEV2PolicyEditor({policy}) {
  const cache=useQueryClient(),[config,setConfig]=useState(policy.configuration),[confirmed,setConfirmed]=useState(false);
  const save=useMutation({mutationFn:()=>aseV2Request('saveConfiguration',{configuration:config,confirmed}),onSuccess:()=>cache.invalidateQueries({queryKey:['ase']})});
  const input=(label,value,onChange,min=0,max=100)=><label className="text-xs">{label}<input type="number" step="any" min={min} max={max} required value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-1 w-full rounded-md border border-input bg-background p-2"/></label>;
  const group=(key,labels,min,max)=><div className="grid gap-3 sm:grid-cols-3">{Object.entries(config[key]).map(([name,value])=>input(labels?.[name] || name.replaceAll('_',' '),value,next=>setConfig(c=>({...c,[key]:{...c[key],[name]:next}})),min,max))}</div>;
  return <details className="rounded-lg border border-border p-4"><summary className="cursor-pointer font-semibold">Configure ASE v2 methodology</summary><form className="mt-4 space-y-4" onSubmit={e=>{e.preventDefault();save.mutate();}}><p className="text-xs text-muted-foreground">Changes affect future assessments only. Each published assessment retains its original complete configuration.</p><div className="grid gap-3 sm:grid-cols-2">{config.components.map((row,index)=>input(`${row.label} weight %`,row.weight,value=>setConfig(c=>({...c,components:c.components.map((r,i)=>i===index ? {...r,weight:value} : r)}))))}</div><p className="text-xs">Total weighting: {config.components.reduce((s,c)=>s+c.weight,0)}%</p>
    <h4 className="text-sm font-semibold">Confidence / reliable coverage thresholds %</h4>{group('confidence',{minimum:'Minimum to assess',medium:'Medium confidence',high:'High confidence'},1,100)}<h4 className="text-sm font-semibold">Verified severe-event caps</h4>{group('caps',{active_insolvency:'Active insolvency',dissolved:'Dissolved company',confirmed_material_sanctions:'Confirmed material sanctions'},1,5)}
    <h4 className="text-sm font-semibold">Evidence freshness, days</h4>{group('freshness_days',null,1,3650)}<h4 className="text-sm font-semibold">Non-linear dependency scoring curve</h4><div className="space-y-2">{config.dependency_curve.map((r,index)=><div key={index} className="grid grid-cols-2 gap-3">{input('Alliance dependency %',r.percentage,v=>setConfig(c=>({...c,dependency_curve:c.dependency_curve.map((p,i)=>i===index ? {...p,percentage:v} : p)})),0,1000)}{input('Component score',r.score,v=>setConfig(c=>({...c,dependency_curve:c.dependency_curve.map((p,i)=>i===index ? {...p,score:v} : p)})),1,5)}</div>)}</div>{input('High Alliance Dependency flag %',config.dependency_flag,v=>setConfig(c=>({...c,dependency_flag:v})),50,100)}
    <label className="flex gap-2 text-xs"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Approve this central methodology for future assessments</label><Button size="sm" disabled={!confirmed || save.isPending}>{save.isPending ? 'Saving methodology…' : 'Save methodology'}</Button>{save.error && <p role="alert" className="text-xs text-destructive">{aseError(save.error)}</p>}{save.isSuccess && <p className="text-xs text-success">Methodology version saved. Reassess to apply it.</p>}
  </form></details>;
}