import React,{useState} from 'react';
import {useMutation,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {aseV2Request} from '@/components/ase/v2/aseV2Client';
import {aseError} from '@/components/ase/aseClient';
export default function LeadershipManualReview({accountId,run}) {
  const cache=useQueryClient(),[form,setForm]=useState({personKey:run.subjects[0]?.key || '',source:'individual_insolvency',state:'MANUAL REVIEW',evidenceKey:'',reference:'',note:'',identifiers:[],start:'',end:'',confirmed:false}),change=(key,value)=>setForm(f=>({...f,[key]:value}));
  const candidates=run.checks.filter(c=>c.person_key===form.personKey && c.source===form.source).flatMap(c=>c.candidates || []),states=form.source==='sanctions' ? ['MANUAL REVIEW','CLEAR','CONFIRMED MATCH'] : ['MANUAL REVIEW','CLEAR','ADVERSE','HISTORIC'];
  const save=useMutation({mutationFn:()=>aseV2Request('leadershipReview',{accountId,...form}),onSuccess:()=>{cache.invalidateQueries({queryKey:['ase']});change('confirmed',false);}});
  const select=(label,key,options)=><label className="text-xs">{label}<select className="mt-1 w-full rounded-md border border-input bg-background p-2" value={form[key]} onChange={e=>change(key,e.target.value)}>{options.map(([value,text])=><option value={value} key={value}>{text}</option>)}</select></label>;
  return <details className="mt-4 rounded-md border border-border p-3"><summary className="cursor-pointer text-sm font-semibold">Record an identity / individual-insolvency review</summary><form onSubmit={e=>{e.preventDefault();save.mutate();}} className="mt-3 space-y-3"><p className="text-xs text-muted-foreground">No automated Individual Insolvency Register scraping. Record only necessary official-source evidence, not personal balances, addresses or full birth dates. This will affect a new All Seeing Eye assessment, never edit published history.</p><div className="grid gap-3 sm:grid-cols-2">{select('Current person / entity','personKey',run.subjects.map(s=>[s.key,s.name+' · '+s.roles.join(', ')]))}{select('Evidence source','source',[['individual_insolvency','Individual Insolvency Register, manual'],['disqualification','Companies House disqualification candidate'],['sanctions','Official UK Sanctions List candidate']])}{select('Review decision','state',states.map(s=>[s,s]))}{form.source!=='individual_insolvency' && select('Actual official candidate','evidenceKey',[['','Select a retrieved candidate'],...candidates.map(c=>[c.evidence_key,c.id || c.evidence_key.split('/').at(-1)])])}<label className="text-xs">Official evidence / case reference<input required maxLength={500} value={form.reference} onChange={e=>change('reference',e.target.value)} className="mt-1 w-full rounded-md border border-input bg-background p-2"/></label><label className="text-xs">Factual matching / relevance note<input required minLength={10} maxLength={600} value={form.note} onChange={e=>change('note',e.target.value)} className="mt-1 w-full rounded-md border border-input bg-background p-2"/></label>{form.source==='individual_insolvency' && <><label className="text-xs">Event started<input type="date" value={form.start} onChange={e=>change('start',e.target.value)} className="mt-1 w-full rounded-md border border-input bg-background p-2"/></label><label className="text-xs">Event ended, if resolved<input type="date" value={form.end} onChange={e=>change('end',e.target.value)} className="mt-1 w-full rounded-md border border-input bg-background p-2"/></label></>}</div>
    <fieldset><legend className="text-xs font-semibold">Corroborating identifiers checked, names alone are insufficient</legend><div className="mt-2 grid gap-2 text-xs sm:grid-cols-2">{[['birth_date','Birth data'],['address','Address / country evidence'],['nationality','Nationality'],['registration_number','Corporate registration number'],['person_number','Official person number'],['company_relationship','Company relationships']].map(([key,label])=><label key={key} className="flex gap-2"><input type="checkbox" checked={form.identifiers.includes(key)} onChange={e=>change('identifiers',e.target.checked ? [...form.identifiers,key] : form.identifiers.filter(k=>k!==key))}/>{label}</label>)}</div></fieldset><label className="flex gap-2 text-xs"><input type="checkbox" checked={form.confirmed} onChange={e=>change('confirmed',e.target.checked)}/>I verified identity, current role, source evidence and relevance. No judgement about character or competence is being recorded.</label><Button size="sm" disabled={!form.confirmed || save.isPending}>{save.isPending ? 'Recording review…' : 'Record reviewed evidence'}</Button>{save.error && <p role="alert" className="text-xs text-destructive">{aseError(save.error)}</p>}{save.isSuccess && <p className="text-xs text-success">Review recorded. Re-run All Seeing Eye to publish its scoring impact.</p>}</form></details>;
}