import React from 'react';
import {formatDateTime} from '@/lib/portal';
export default function LeadershipEvidenceRecords({subjects=[],checks=[],former=[]}) {
  return <div className="mt-3 space-y-3">{subjects.map(person=><details className="rounded-md border border-border p-3 text-xs" key={person.key}><summary className="cursor-pointer font-semibold">{person.name} · {person.roles.join(', ')}</summary><dl className="mt-3 grid gap-2 sm:grid-cols-2"><div><dt className="text-muted-foreground">Control / officer category</dt><dd>{person.category || person.roles.join(', ')}</dd></div><div><dt className="text-muted-foreground">Current status</dt><dd>{person.current ? 'Current at screening' : 'Former'}</dd></div><div><dt className="text-muted-foreground">Nationality / country, where available</dt><dd>{[person.nationality,person.country].filter(Boolean).join(' · ') || 'Not provided'}</dd></div><div><dt className="text-muted-foreground">Appointed / notified</dt><dd>{person.appointed_on || 'Not provided'}</dd></div></dl>{person.nature_of_control?.length>0 && <p className="mt-2">Nature of control: {person.nature_of_control.map(n=>n.replaceAll('-',' ')).join('; ')}</p>}
    {checks.filter(c=>c.person_key===person.key).map((check,index)=><details className="mt-3 border-t border-border pt-2" key={index}><summary className="cursor-pointer">{check.source.replaceAll('_',' ')} · <strong>{check.match_status}</strong></summary><p className="mt-2">{check.reason}</p><p className="mt-2">Searched {formatDateTime(check.checked_at)} · Matching confidence: {check.matching_confidence} · Human review: {check.human_review ? 'Yes' : 'No'}</p><p className="mt-2">Score impact: {check.score_impact?.aggregate_score!=null ? `${check.score_impact.component}, ${check.score_impact.slot.replaceAll('_',' ')} sub-score ${check.score_impact.aggregate_score.toFixed(2)}/5 at ${check.score_impact.configured_subweight}% component weight. This evidence is not scored twice.` : 'Unscored / coverage limitation; no adverse inference.'}</p>{check.evidence_reference && <a className="mt-2 inline-block underline" href={/^https:\/\//.test(check.evidence_reference) ? check.evidence_reference : undefined} target="_blank" rel="noreferrer">{/^https:\/\//.test(check.evidence_reference) ? 'View official evidence' : check.evidence_reference}</a>}
      {check.candidates?.map(candidate=><p key={candidate.evidence_key} className="mt-2">Official record {candidate.id || candidate.evidence_key.split('/').at(-1)} · {candidate.match_status} · {candidate.matching_basis?.join('; ')}{candidate.permission_review && ' · Permission-to-act needs relevance review'}</p>)}
      {check.companies?.length>0 && <details className="mt-2"><summary className="cursor-pointer">Appointment history: {check.current_appointments} current, {check.previous_appointments} previous</summary>{check.companies.map((c,i)=><p key={i} className="mt-2"><a className="underline" href={c.reference} target="_blank" rel="noreferrer">{c.name || c.number}</a> · {c.status || 'Status unavailable'} · {c.appointed_on || 'Date unavailable'}{c.resigned_on && ` to ${c.resigned_on}`}</p>)}{check.company_records_truncated && <p className="mt-2">Display limited; view the official appointment source for all records.</p>}</details>}
    </details>)}
  </details>)}{former.length>0 && <details className="rounded-md border border-border p-3 text-xs"><summary className="cursor-pointer">Former officers, retained as historical context</summary>{former.map(s=><p key={s.key} className="mt-2">{s.name} · {s.roles.join(', ')} · Left {s.ceased_on}. Not treated as a current control risk.</p>)}</details>}</div>;
}