import React, { useEffect, useState } from 'react';
import AliceLookup from '@/components/alice/AliceLookup';
import { GUIDES } from '@/components/alice/aliceGuides';
import AliceTaskField from '@/components/alice/AliceTaskField';
import AliceValuationProjectInput from '@/components/alice/AliceValuationProjectInput';

export default function AliceGuideInput({ guide, onNext, onBack, onConfirm, onCancel }) {
  const field = GUIDES[guide.type].steps[guide.step];
  const [value, setValue] = useState('');
  useEffect(() => { setValue(field ? guide.answers[field.key] || '' : ''); }, [guide.type, guide.step]);
  if (guide.result) return <div className="border-t border-border p-4 text-sm"><a href={guide.result.path} className="font-semibold text-assistant hover:underline">{guide.result.link} →</a><button type="button" onClick={onCancel} className="ml-4 text-muted-foreground hover:text-foreground">Done</button></div>;
  if (!field) return <div className="space-y-3 border-t border-border p-4 text-sm"><div className="max-h-28 overflow-y-auto rounded-lg bg-muted p-3">{GUIDES[guide.type].steps.map(s => <p key={s.key} className="mb-1 break-words"><span className="font-semibold">{s.question}</span> {typeof guide.answers[s.key] === 'object' ? guide.answers[s.key]?.name || '—' : guide.answers[s.key] || '—'}</p>)}</div><div className="flex gap-2"><button type="button" onClick={onConfirm} disabled={guide.saving} className="rounded-lg bg-assistant px-3 py-2 font-semibold text-white disabled:opacity-50">{guide.saving ? 'Saving…' : 'Yes, save it'}</button><button type="button" onClick={onBack} disabled={guide.saving} className="rounded-lg border border-border px-3 py-2">Back</button></div>{guide.error && <p role="alert" className="text-destructive">{guide.error}</p>}</div>;
  return <form onSubmit={e => { e.preventDefault(); onNext(value); }} className="space-y-2 border-t border-border p-4">
    {field.type === 'valuation_project' ? <AliceValuationProjectInput value={value} onChange={setValue} /> : ['owner', 'choice', 'date', 'signed_number'].includes(field.type) ? <AliceTaskField field={field} value={value} onChange={setValue} /> : ['client','project'].includes(field.type) ? <AliceLookup type={field.type} value={value} onChange={setValue} /> : field.type === 'level' ? <select aria-label={field.question} value={value} onChange={e => setValue(e.target.value)} className="w-full rounded-lg border border-input bg-background px-3 py-2 text-sm"><option value="">Choose a level</option>{['low','medium','high'].map(level => <option key={level} value={level}>{level[0].toUpperCase() + level.slice(1)}</option>)}</select> : ['project_details','description','mitigation','comment','action','comments','decision','financial_impact','programme_impact'].includes(field.key) ? <textarea autoFocus aria-label={field.question} rows={3} maxLength={1500} value={value} onChange={e => setValue(e.target.value)} placeholder="Your answer…" className="w-full resize-none rounded-lg border border-input bg-background px-3 py-2 text-sm" /> : <input autoFocus aria-label={field.question} type={field.type === 'number' ? 'number' : 'text'} min={field.type === 'number' ? '0' : undefined} maxLength={field.type === 'number' ? undefined : 200} value={value} onChange={e => setValue(e.target.value)} placeholder="Your answer…" className="w-full rounded-lg border border-input bg-background px-3 py-2 text-sm" />}
    {guide.error && <p role="alert" className="text-xs text-destructive">{guide.error}</p>}
    <div className="flex items-center gap-2 text-xs"><button type="submit" disabled={!field.optional && !value} className="rounded-lg bg-assistant px-3 py-2 font-semibold text-white disabled:opacity-50">Continue</button>{field.optional && <button type="button" onClick={() => onNext('')} className="px-2 py-2 text-muted-foreground hover:text-foreground">Skip</button>}{guide.step > 0 && <button type="button" onClick={onBack} className="px-2 py-2 text-muted-foreground hover:text-foreground">Back</button>}<button type="button" onClick={onCancel} className="ml-auto px-2 py-2 text-muted-foreground hover:text-foreground">Cancel</button></div>
  </form>;
}