import React from 'react';
import DashboardPanel from '@/components/dashboard/DashboardPanel';
import { formatCurrency } from '@/lib/portal';
const labels = {lead:'Lead',qualified:'Qualified',scope_development:'Scope development',design_feasibility:'Design / feasibility',proposal_preparation:'Proposal preparation',proposal_submitted:'Proposal submitted',negotiation:'Negotiation',preferred_partner:'Preferred partner'};
export default function OverviewCommercial({ rows = [], poNet }) {
  const total = rows.reduce((n,r) => n + (r.sum_budget || 0),0);
  const count = rows.reduce((n,r) => n + r.count,0);
  const ordered = Object.keys(labels).map(stage => rows.find(r => r.stage === stage)).filter(Boolean);
  return <DashboardPanel title="Commercial pipeline" link="/crm/pipeline" linkLabel="View pipeline"><p className="text-lg font-extrabold">{formatCurrency(total)} <span className="text-xs font-normal">open opportunities</span></p><p className="mt-1 text-[10px] text-muted-foreground">Accessible CRM pipeline, independent of project filters</p>{!count ? <p className="py-5 text-xs text-muted-foreground">No open opportunities in your accessible pipeline.</p> : <div className="mt-3 grid grid-cols-2 items-center gap-4"><div>{ordered.map((r,i) => <div key={r.stage} className="overview-funnel bg-primary" style={{width:`${100 - i * 8}%`,opacity:1 - i * .07}} />)}</div><ul className="space-y-3">{ordered.map(r => <li key={r.stage} className="text-[10px]"><strong>{formatCurrency(r.sum_budget)}</strong><span className="ml-2 text-muted-foreground">{labels[r.stage]} ({r.count})</span></li>)}</ul></div>}<div className="mt-4 grid grid-cols-3 gap-2 rounded-lg bg-chart-4/10 p-3"><div><strong className="block text-sm">{count}</strong><span className="text-[9px] text-muted-foreground">Opportunities</span></div><div><strong className="block text-sm">{count ? formatCurrency(total / count) : '—'}</strong><span className="text-[9px] text-muted-foreground">Average opportunity</span></div><div><strong className="block text-sm">{formatCurrency(rows.reduce((n,r) => n+(r.sum_alliance_fee || 0),0))}</strong><span className="text-[9px] text-muted-foreground">Recorded Alliance fees</span></div></div><p className="mt-3 text-[10px] text-muted-foreground">Linked purchase orders (net): <strong className="text-foreground">{formatCurrency(poNet)}</strong></p></DashboardPanel>;
}