import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, Building2, ChevronRight } from 'lucide-react';
import useAssignedTasks from '@/components/tasks/useAssignedTasks';
import DashboardPanel from '@/components/dashboard/DashboardPanel';
import HomeAttention from '@/components/dashboard/HomeAttention';
import { projectStage } from '@/components/dashboard/pipelineStage';
export default function OverviewAttention({ portfolio, user }) {
  const [mine, setMine] = useState(false);
  const tasks = useAssignedTasks(user,true);
  return <div id="overview-attention"><div className="mb-2 flex gap-2 text-[10px]"><button onClick={() => setMine(false)} aria-pressed={!mine} className={`rounded-full px-3 py-1 ${!mine ? 'bg-als-navy text-sidebar-foreground' : 'bg-card'}`}>All portfolio ({portfolio.metrics.atRisk})</button><button onClick={() => setMine(true)} aria-pressed={mine} className={`rounded-full px-3 py-1 ${mine ? 'bg-als-navy text-sidebar-foreground' : 'bg-card'}`}>Mine ({tasks.total})</button></div>{mine ? <HomeAttention tasks={tasks} /> : <DashboardPanel title="Needs attention" link="/projects">{!portfolio.atRisk.length ? <p className="py-8 text-xs text-muted-foreground">No recorded action or completion-date flags.</p> : <ul className="divide-y divide-border/60">{portfolio.atRisk.slice(0,5).map(({project:p,reasons,level}) => <li key={p.id}><Link to={`/projects/${p.id}?tab=delivery`} className="flex items-center gap-3 py-3 hover:bg-muted/40"><AlertTriangle className={`h-4 w-4 shrink-0 ${level === 'high' ? 'text-destructive' : 'text-primary'}`} /><Building2 className="h-7 w-7 shrink-0 text-chart-2" /><div className="min-w-0 flex-1"><strong className="block truncate text-xs">{p.name}</strong><p className="mt-1 truncate text-[10px] text-muted-foreground" title={reasons.join(' · ')}>{reasons[0]}</p></div><span className="text-[9px] text-muted-foreground">{projectStage(p)}</span><span className={`rounded-full px-2 py-1 text-[9px] ${level === 'high' ? 'bg-destructive/10 text-destructive' : 'bg-primary/10 text-primary'}`}>{level === 'high' ? 'At risk' : 'Watch'}</span><ChevronRight className="h-3 w-3" /></Link></li>)}</ul>}</DashboardPanel>}</div>;
}