import React, { useState } from 'react';
import RecordUpdatedAt from '@/components/RecordUpdatedAt';
import { formatCurrency, formatDate } from '@/lib/portal';
import { PAYMENT, StatusPill, valuationTotals } from './valuationUtils';

export default function ValuationRegister({ valuations, onOpen }) {
  const [status, setStatus] = useState(''); const [payment, setPayment] = useState(''); const [search, setSearch] = useState(''); const [sort, setSort] = useState('newest');
  const [period, setPeriod] = useState(''); const [submitted, setSubmitted] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const rows = valuations.filter(v => (!status || v.status === status) && (!payment || v.payment_status === payment) && (!period || (v.period_start || '').startsWith(period)) && (!submitted || (v.submitted_by_name || '').toLowerCase().includes(submitted.toLowerCase())) && (!from || (v.submitted_at || '') >= from) && (!to || (v.submitted_at || '') <= to + 'T23:59:59') && (!search || (`${v.number} ${v.notes || ''} ${v.submitted_by_name || ''}`).toLowerCase().includes(search.toLowerCase()))).sort((a,b) => sort === 'oldest' ? a.number - b.number : sort === 'amount' ? valuationTotals(b).due - valuationTotals(a).due : b.number - a.number);
  const control = 'h-9 rounded-lg border border-border bg-card px-3 text-sm text-foreground';
  return <section className="rounded-2xl border border-border bg-card"><div className="border-b border-border p-5"><h3 className="font-heading font-semibold text-als-navy">Valuation register</h3><div className="mt-4 flex flex-wrap gap-2">
    <input className={control} placeholder="Search valuations" value={search} onChange={e => setSearch(e.target.value)} aria-label="Search valuations" />
    <select className={control} value={status} onChange={e => setStatus(e.target.value)} aria-label="Status"><option value="">All statuses</option>{['draft','submitted','under_review','returned','approved','rejected','paid'].map(s => <option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select>
    <input className={control} type="month" value={period} onChange={e => setPeriod(e.target.value)} aria-label="Valuation period" />
    <input className={control} placeholder="Submitted by" value={submitted} onChange={e => setSubmitted(e.target.value)} aria-label="Submitted by" />
    <select className={control} value={payment} onChange={e => setPayment(e.target.value)} aria-label="Payment status"><option value="">All payments</option>{Object.entries(PAYMENT).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select>
    <input className={control} type="date" value={from} onChange={e => setFrom(e.target.value)} aria-label="Submitted from" /><input className={control} type="date" value={to} onChange={e => setTo(e.target.value)} aria-label="Submitted to" />
    <select className={control} value={sort} onChange={e => setSort(e.target.value)} aria-label="Sort"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="amount">Amount due</option></select>
  </div></div><div className="overflow-x-auto"><table className="min-w-[1250px] w-full text-left text-xs"><thead className="bg-secondary text-muted-foreground"><tr>{['Valuation','Period','Submitted','Submitted by','Gross','Retention','Previous certified','Amount due','Status','Reviewer','Approved amount','Approval date','Payment','Payment date','Action'].map(h => <th key={h} className="whitespace-nowrap px-3 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{rows.map(v => { const previous = Math.max(0, ...valuations.filter(x => x.number < v.number && ['approved','paid'].includes(x.status)).map(x => Number(x.approved_gross) || 0)); const t = valuationTotals(v, previous); return <tr key={v.id} className="hover:bg-secondary/60"><td className="px-3 py-3 font-semibold">{v.number}<RecordUpdatedAt record={v} className="mt-1" /></td><td className="px-3">{formatDate(v.period_start)} – {formatDate(v.period_end)}</td><td className="px-3">{formatDate(v.submitted_at)}</td><td className="px-3">{v.submitted_by_name || '—'}</td><td className="px-3">{formatCurrency(t.gross)}</td><td className="px-3">{formatCurrency(v.approved_retention ?? t.retention)}</td><td className="px-3">{formatCurrency(previous)}</td><td className="px-3 font-semibold">{formatCurrency(v.approved_net ?? t.due)}</td><td className="px-3"><StatusPill status={v.status} /></td><td className="px-3">{v.reviewer_name || '—'}</td><td className="px-3">{formatCurrency(v.approved_gross)}</td><td className="px-3">{formatDate(v.approved_at)}</td><td className="px-3">{PAYMENT[v.payment_status] || '—'}</td><td className="px-3">{formatDate(v.payment_date)}</td><td className="px-3"><button className="font-semibold text-als-navy-light underline" onClick={() => onOpen(v)}>Open</button></td></tr>; })}</tbody></table>{rows.length === 0 && <p className="p-8 text-center text-sm text-muted-foreground">No valuations match these filters.</p>}</div></section>;
}