import React, { useState } from 'react';
import { PAYMENT, valuationTotals } from './valuationUtils';
import { formatCurrency } from '@/lib/portal';
export default function ValuationActions({ value, role, editable, onAction, busy, previousCertified }) {
  const [comment, setComment] = useState(''); const [gross, setGross] = useState(''); const [retention, setRetention] = useState(''); const [deductions, setDeductions] = useState('');
  const [payment, setPayment] = useState({ payment_status: value.payment_status || 'awaiting_invoice', payment_due_date: value.payment_due_date || '', payment_reference: value.payment_reference || '', invoice_number: value.invoice_number || '', invoice_date: value.invoice_date || '', payment_date: value.payment_date || '', amount_paid: value.amount_paid || 0, payment_notes: value.payment_notes || '' });
  const reviewer = ['admin','director','bsm','bdm'].includes(role);
  const finance = ['admin','finance'].includes(role);
  const reviewable = ['submitted','under_review'].includes(value.status);
  const totals = valuationTotals(value, previousCertified);
  const act = async action => { await onAction(action, { comment, ...(action === 'approve' ? { approved_gross: gross === '' ? null : gross, approved_retention: retention === '' ? null : retention, approved_deductions: deductions === '' ? null : deductions } : {}) }); setComment(''); };
  const input = 'rounded-lg border border-border bg-card p-2 text-sm';
  return <section className="rounded-2xl border border-border bg-card p-5"><h3 className="font-heading font-semibold text-als-navy">Next step</h3>
    {editable && <div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} onClick={() => onAction('save')} className="rounded-lg border border-border px-4 py-2 text-sm font-medium">{busy ? 'Saving…' : 'Save draft'}</button><button disabled={busy} onClick={() => onAction('submit')} className="rounded-lg bg-als-navy px-4 py-2 text-sm font-medium text-white">Submit to Alliance</button></div>}
    {reviewer && reviewable && <div className="mt-3 space-y-3"><p className="text-sm text-muted-foreground">Submitted gross: {formatCurrency(totals.gross)} · Previously certified: {formatCurrency(previousCertified)}</p><textarea className={`w-full ${input}`} placeholder="Review comments / reason for return or rejection" value={comment} onChange={e => setComment(e.target.value)} /><div className="flex flex-wrap gap-2">{[['gross',gross,setGross,totals.gross],['retention',retention,setRetention,totals.retention],['deductions',deductions,setDeductions,totals.deductions]].map(([label,val,set,defaultValue]) => <label key={label} className="text-xs capitalize">Approved {label}<input type="number" min="0" step="0.01" className={`block w-40 ${input}`} placeholder={String(defaultValue)} value={val} onChange={e => set(e.target.value)} /></label>)}</div><div className="flex flex-wrap gap-2">{value.status === 'submitted' && <button disabled={busy} onClick={() => act('review')} className="rounded-lg border border-border px-3 py-2 text-sm">Start review</button>}<button disabled={busy} onClick={() => act('approve')} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm text-white">Approve</button><button disabled={busy || !comment.trim()} onClick={() => act('return')} className="rounded-lg bg-orange-600 px-3 py-2 text-sm text-white">Return for Amendment</button><button disabled={busy || !comment.trim()} onClick={() => act('reject')} className="rounded-lg bg-red-700 px-3 py-2 text-sm text-white">Reject</button></div></div>}
    {['approved','paid'].includes(value.status) && <p className="mt-3 text-sm">Approved gross {formatCurrency(value.approved_gross)} · Retention {formatCurrency(value.approved_retention)} · Deductions {formatCurrency(value.approved_deductions)} · <strong>Net {formatCurrency(value.approved_net)}</strong></p>}
    {finance && ['approved','paid'].includes(value.status) && <div className="mt-4 space-y-3 border-t border-border pt-4"><h4 className="text-sm font-semibold">Payment tracking</h4><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs">Status<select className={`block w-full ${input}`} value={payment.payment_status} onChange={e => setPayment({ ...payment, payment_status: e.target.value })}>{Object.entries(PAYMENT).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select></label>{[['payment_due_date','Due date','date'],['payment_reference','Payment reference','text'],['invoice_number','Invoice number','text'],['invoice_date','Invoice date','date'],['payment_date','Payment date','date'],['amount_paid','Amount paid','number'],['payment_notes','Payment notes','text']].map(([key,label,type]) => <label key={key} className="text-xs">{label}<input className={`block w-full ${input}`} type={type} min={type === 'number' ? '0' : undefined} step={type === 'number' ? '0.01' : undefined} value={payment[key]} onChange={e => setPayment({ ...payment, [key]: e.target.value })} /></label>)}</div><button disabled={busy} onClick={() => onAction('payment', payment)} className="rounded-lg bg-als-navy px-4 py-2 text-sm text-white">Save payment</button></div>}
    {!editable && !reviewable && !['approved','paid'].includes(value.status) && <p className="mt-3 text-sm text-muted-foreground">This valuation is read-only.</p>}
  </section>;
}