import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { createContactAction } from './contactActions';
const TYPES = ['call','email','meeting','teams_meeting','lunch','event','site_visit','project_meeting','proposal_sent','note'];
const localNow = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0,16);
export default function ContactActivity({ contact, account, user, canEdit, mode, onClose, onLogged, opportunities = [] }) {
  const [events, setEvents] = useState([]), [conversations, setConversations] = useState([]), [cursors, setCursors] = useState({}), [hasMore, setHasMore] = useState({}), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [form, setForm] = useState({ type: 'call', occurred_at: localNow(), subject: '', description: '', participants: '', sentiment: '', opportunity_id: '', next_action: '', due_at: '' });
  useEffect(() => { if (mode === 'note' || mode === 'log') setForm(f => ({ ...f, type: mode === 'note' ? 'note' : 'call' })); }, [mode]);
  const load = async (more = false) => { setLoading(true); try {
    const [a,c] = await Promise.all([!more || hasMore.activity ? base44.entities.CRMActivity.filter({ contact_id: contact.id }, { sort: '-occurred_at', limit: 20, ...(more && cursors.activity ? { cursor: cursors.activity } : {}) }) : null, !more || hasMore.conversation ? base44.entities.Conversation.filter({ contact_id: contact.id }, { sort: '-occurred_at', limit: 20, ...(more && cursors.conversation ? { cursor: cursors.conversation } : {}) }) : null]);
    if (a) { setEvents(old => more ? [...old,...a.items] : a.items); setCursors(old => ({ ...old, activity: a.next_cursor })); setHasMore(old => ({ ...old, activity: a.has_more })); }
    if (c) { setConversations(old => more ? [...old,...c.items] : c.items); setCursors(old => ({ ...old, conversation: c.next_cursor })); setHasMore(old => ({ ...old, conversation: c.has_more })); }
  } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [contact.id]);
  const save = async e => { e.preventDefault(); setBusy(true); setError(''); try {
    await base44.entities.CRMActivity.create({ contact_id: contact.id, ...(account?.id ? { account_id: account.id } : {}), ...(form.opportunity_id ? { opportunity_id: form.opportunity_id } : {}), owner_id: user.id, line_manager_id: user.line_manager_id || user.data?.line_manager_id || '', author_id: user.id, author_name: user.full_name || user.email, type: form.type, occurred_at: new Date(form.occurred_at).toISOString(), subject: form.subject.trim(), description: form.description.trim(), participants: form.participants.trim(), sentiment: form.sentiment, next_action: form.next_action.trim(), ...(form.due_at ? { follow_up_date: new Date(form.due_at).toISOString() } : {}) });
    setForm({ type: 'call', occurred_at: localNow(), subject: '', description: '', participants: '', sentiment: '', opportunity_id: '', next_action: '', due_at: '' }); onClose?.(); await load(); onLogged?.();
    if (form.next_action.trim()) { try { const { warning } = await createContactAction({ contact_id: contact.id, ...(account?.id ? { account_id: account.id } : {}), ...(form.opportunity_id ? { opportunity_id: form.opportunity_id } : {}), title: form.next_action.trim(), ...(form.due_at ? { due_at: new Date(form.due_at).toISOString() } : {}), owner_id: user.id, line_manager_id: user.line_manager_id || user.data?.line_manager_id || '', status: 'open' }, user, contact); onLogged?.(); if (warning) setError(warning); } catch (err) { setError(`Interaction saved, but follow-up task failed: ${err.message}`); } }
  } catch (e) { setError(e.message || 'Unable to log interaction.'); } finally { setBusy(false); } };
  const rows = [...events.map(a => ({ ...a, source: 'activity' })),...conversations.map(c => ({ ...c, source: 'conversation', type: c.channel, subject: c.summary, description: c.next_step ? `Next: ${c.next_step}` : '' }))].sort((a,b) => new Date(b.occurred_at) - new Date(a.occurred_at));
  return <section className="rounded-xl border border-border bg-card p-5"><h2 className="font-semibold">Activity</h2>{canEdit && ['log','note'].includes(mode) && <form onSubmit={save} className="mt-4 grid gap-3 rounded-lg bg-secondary p-4 sm:grid-cols-2"><label className="text-sm">Type<select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })} className="mt-1 w-full rounded-lg border border-input bg-background p-2">{TYPES.map(t => <option key={t} value={t}>{t.replaceAll('_',' ')}</option>)}</select></label><label className="text-sm">Date &amp; time<input type="datetime-local" required value={form.occurred_at} onChange={e => setForm({ ...form, occurred_at: e.target.value })} className="mt-1 w-full rounded-lg border border-input bg-background p-2" /></label><label className="text-sm sm:col-span-2">Subject<input required maxLength={200} value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} className="mt-1 w-full rounded-lg border border-input bg-background p-2" /></label><label className="text-sm sm:col-span-2">Summary<textarea maxLength={5000} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="mt-1 w-full rounded-lg border border-input bg-background p-2" /></label><label className="text-sm">Attendees<input maxLength={500} value={form.participants} onChange={e => setForm({ ...form, participants: e.target.value })} className="mt-1 w-full rounded-lg border border-input bg-background p-2" /></label><label className="text-sm">Sentiment<select value={form.sentiment} onChange={e => setForm({ ...form, sentiment: e.target.value })} className="mt-1 w-full rounded-lg border border-input bg-background p-2"><option value="">Not set</option>{['positive','neutral','concern'].map(s => <option key={s} value={s}>{s}</option>)}</select></label><label className="text-sm">Related opportunity<select value={form.opportunity_id} onChange={e => setForm({ ...form, opportunity_id: e.target.value })} className="mt-1 w-full rounded-lg border border-input bg-background p-2"><option value="">None</option>{opportunities.map(o => <option key={o.id} value={o.id}>{o.title}</option>)}</select></label><label className="text-sm">Next action<input maxLength={200} value={form.next_action} onChange={e => setForm({ ...form, next_action: e.target.value })} className="mt-1 w-full rounded-lg border border-input bg-background p-2" /></label><label className="text-sm">Follow-up due<input type="datetime-local" value={form.due_at} onChange={e => setForm({ ...form, due_at: e.target.value })} className="mt-1 w-full rounded-lg border border-input bg-background p-2" /></label><div className="flex items-end gap-2"><Button disabled={busy}>{busy ? 'Saving…' : 'Save interaction'}</Button><Button type="button" variant="outline" onClick={onClose}>Cancel</Button></div></form>}
    {error && <p role="alert" className="mt-2 text-sm text-destructive">{error}</p>}{loading && !rows.length ? <p className="mt-3 text-sm text-muted-foreground">Loading activity…</p> : !rows.length ? <p className="mt-3 text-sm text-muted-foreground">No interactions recorded yet.</p> : <ol className="mt-3 divide-y divide-border">{rows.map(row => <li key={`${row.source}-${row.id}`} className="py-3 text-sm"><p className="font-medium">{row.subject}</p><p className="text-xs capitalize text-muted-foreground">{row.type?.replaceAll('_',' ')} · {new Date(row.occurred_at).toLocaleString('en-GB')} · {row.author_name || 'Team member'}{row.sentiment ? ` · ${row.sentiment}` : ''}</p>{row.description && <p className="mt-1 whitespace-pre-wrap break-words">{row.description}</p>}{row.next_action && <p className="mt-1 text-muted-foreground">Next: {row.next_action}</p>}{row.opportunity_id && <Link to={`/opportunities/${row.opportunity_id}`} className="text-xs text-primary hover:underline">View opportunity</Link>}</li>)}</ol>}{(hasMore.activity || hasMore.conversation) && <Button type="button" size="sm" variant="outline" disabled={loading} onClick={() => load(true)}>Load more activity</Button>}</section>;
}