import React, { useEffect, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
export default function ContactConnections({ contactId, staff, ownerId, canEdit, user }) {
  const [rows, setRows] = useState([]), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState('');
  const [form, setForm] = useState({ staff_contact_id: '', relationship_type: '', strength: 'developing' });
  const load = async () => { try { const page = await base44.entities.CRMContactRelationship.filter({ contact_id: contactId }, { limit: 50 }); setRows(page.items); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [contactId]);
  const save = async e => { e.preventDefault(); setSaving(true); setError(''); try { const person = staff.find(s => s.id === form.staff_contact_id); if (!person) throw new Error('Select a colleague.'); const existing = await base44.entities.CRMContactRelationship.filter({ contact_id: contactId, staff_contact_id: person.id }, { limit: 1 }); if (existing.items.length) throw new Error('This colleague is already connected.'); await base44.entities.CRMContactRelationship.create({ ...form, contact_id: contactId, staff_name: person.full_name }); setForm({ staff_contact_id: '', relationship_type: '', strength: 'developing' }); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const remove = async row => { setSaving(true); setError(''); try { await base44.entities.CRMContactRelationship.delete(row.id); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  return <section className="rounded-xl border border-border bg-card p-5"><h2 className="font-semibold">Who knows this contact?</h2>{error && <p role="alert" className="mt-2 text-sm text-destructive">{error}</p>}{loading ? <p className="mt-3 text-sm text-muted-foreground">Loading connections…</p> : !rows.length ? <p className="mt-3 text-sm text-muted-foreground">No additional Alliance connections recorded.</p> : <ul className="mt-3 space-y-2">{rows.map(row => <li key={row.id} className="text-sm"><strong>{row.staff_name}</strong>{row.staff_contact_id === ownerId ? ' · Primary owner' : ''}<p className="text-xs capitalize text-muted-foreground">{row.relationship_type || 'Alliance colleague'} · {row.strength}</p>{canEdit && (row.created_by_id === user?.id || user?.role === 'admin') && <button type="button" disabled={saving} onClick={() => remove(row)} className="text-xs text-destructive hover:underline">Remove</button>}</li>)}</ul>}
    {canEdit && <form onSubmit={save} className="mt-3 grid gap-2"><select required aria-label="Alliance colleague" value={form.staff_contact_id} onChange={e => setForm({ ...form, staff_contact_id: e.target.value })} className="rounded-lg border border-input bg-background p-2 text-sm"><option value="">Add colleague</option>{staff.map(s => <option key={s.id} value={s.id}>{s.full_name}</option>)}</select><input aria-label="Connection type" maxLength={100} placeholder="Relationship type (e.g. executive relationship)" value={form.relationship_type} onChange={e => setForm({ ...form, relationship_type: e.target.value })} className="rounded-lg border border-input bg-background p-2 text-sm" /><select aria-label="Connection strength" value={form.strength} onChange={e => setForm({ ...form, strength: e.target.value })} className="rounded-lg border border-input bg-background p-2 text-sm">{['new','developing','established','strong'].map(v => <option key={v}>{v}</option>)}</select><Button size="sm" disabled={saving || !form.staff_contact_id}>{saving ? 'Saving…' : 'Add connection'}</Button></form>}
  </section>;
}