import React from 'react';
import RecordUpdatedAt from '@/components/RecordUpdatedAt';
import { Button } from '@/components/ui/button';
import {Link} from 'react-router-dom';
import RelationshipStrength from '@/components/relationships/RelationshipStrength';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';

export default function ContactHeader({ contact, profile, owner, last, next, health, onAction, canEdit, account }) {
  const actions = [['log','Log Interaction'],['note','Add Note'],['task','Set Next Action']];
  return <header className="rounded-xl border border-border bg-card p-5 sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><h1 className="font-heading text-3xl font-semibold">{profile?.preferred_name || contact.full_name}</h1><p className="mt-1 text-sm text-muted-foreground">{[contact.job_title, account?.name || contact.company_name].filter(Boolean).join(' · ')}</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-sm">{contact.email && <a href={`mailto:${contact.email}`} className="text-primary hover:underline">{contact.email}</a>}{contact.phone && <a href={`tel:${contact.phone}`}>{contact.phone}</a>}{contact.mobile_phone && <a href={`tel:${contact.mobile_phone}`}>{contact.mobile_phone}</a>}{profile?.linkedin_url && <a href={profile.linkedin_url} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">LinkedIn</a>}</div></div><div className="flex flex-wrap gap-2"><RelationshipStrength profile={profile} last={last}/>{profile?.key_decision_maker && <span className="rounded-full bg-muted px-3 py-1 text-xs">Key decision-maker</span>}{profile?.contact_priority==='strategic' && <span className="rounded-full bg-muted px-3 py-1 text-xs">Strategic relationship</span>}{profile?.tags?.map(t=><span key={t} className="rounded-full bg-muted px-3 py-1 text-xs">{t}</span>)}</div></div>
    <RecordUpdatedAt record={contact} className="mt-3" />
    <dl className="mt-5 grid gap-3 border-t border-border pt-4 text-sm sm:grid-cols-4">{[['Relationship owner',owner || 'Not assigned'],['Relationship strength',profile?.relationship_strength || 'Not set'],['Last interaction',last ? new Date(last).toLocaleDateString('en-GB') : 'Not logged'],['Next action',next?.title || 'Not set']].map(([label,value]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 font-medium capitalize">{value}</dd></div>)}</dl>
    <div className="mt-5 flex flex-wrap gap-2">{actions.map(([key,label]) => <Button key={key} type="button" size="sm" variant={key === 'log' ? 'default' : 'outline'} disabled={!canEdit || (key === 'opportunity' && account?.account_type !== 'client')} onClick={() => onAction(key)}>{label}</Button>)}{account && <Link className="rounded-lg border border-border px-3 py-2 text-xs hover:bg-muted" to={`/accounts/${account.id}`}>Open organisation</Link>}{canEdit && <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm">More</Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem disabled={account?.account_type!=='client'} onSelect={()=>onAction('opportunity')}>Add opportunity</DropdownMenuItem><DropdownMenuItem onSelect={()=>onAction('followup')}>Schedule follow-up</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}</div>
  </header>;
}