import React, { useEffect, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
export default function ContactKeyDates({ contact, user, canEdit }) {
  const [rows, setRows] = useState([]), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState('');
  const [form, setForm] = useState({ label: '', date_label: '', remind_at: '' });
  const load = async () => { try { const page = await base44.entities.CRMContactKeyDate.filter({ contact_id: contact.id }, { sort: 'date_label', limit: 50 }); setRows(page.items); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [contact.id]);
  const save = async e => { e.preventDefault(); setSaving(true); setError(''); try { await base44.entities.CRMContactKeyDate.create({ contact_id: contact.id, label: form.label.trim(), date_label: form.date_label.trim(), ...(form.remind_at ? { remind_at: new Date(form.remind_at).toISOString(), owner_id: user.id } : {}) }); const reminder = form.remind_at; const label = form.label.trim(); setForm({ label: '', date_label: '', remind_at: '' }); await load(); if (reminder) { try { await base44.entities.CRMReminder.create({ user_id: user.id, contact_id: contact.id, subject: `${contact.full_name}: ${label}`, remind_at: new Date(reminder).toISOString() }); } catch (err) { setError(`Date saved, but reminder failed: ${err.message}`); } } } catch (e) { setError(e.message); } finally { setSaving(false); } };
  return <section className="rounded-xl border border-border bg-card p-5"><h2 className="font-semibold">Key dates</h2>{error && <p role="alert" className="mt-2 text-sm text-destructive">{error}</p>}{loading ? <p className="mt-3 text-sm text-muted-foreground">Loading dates…</p> : !rows.length ? <p className="mt-3 text-sm text-muted-foreground">No key dates recorded.</p> : <ul className="mt-3 space-y-2 text-sm">{rows.map(row => <li key={row.id}><strong>{row.date_label}</strong> · {row.label}{row.remind_at && <span className="block text-xs text-muted-foreground">Reminder: {new Date(row.remind_at).toLocaleString('en-GB')}</span>}</li>)}</ul>}
    {canEdit && <form onSubmit={save} className="mt-3 space-y-2"><input required maxLength={100} aria-label="Date name" placeholder="Date name (e.g. birthday)" value={form.label} onChange={e => setForm({ ...form, label: e.target.value })} className="w-full rounded-lg border border-input bg-background p-2 text-sm" /><input required maxLength={100} aria-label="Date" placeholder="Date (e.g. 14 March, no year needed)" value={form.date_label} onChange={e => setForm({ ...form, date_label: e.target.value })} className="w-full rounded-lg border border-input bg-background p-2 text-sm" /><label className="block text-xs">Remind me (optional)<input type="datetime-local" value={form.remind_at} onChange={e => setForm({ ...form, remind_at: e.target.value })} className="mt-1 w-full rounded-lg border border-input bg-background p-2 text-sm" /></label><Button size="sm" disabled={saving}>{saving ? 'Saving…' : 'Add date'}</Button></form>}
  </section>;
}