import React, { useEffect, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { createContactAction, completeContactAction } from './contactActions';
export default function ContactTasks({ contact, account, user, canEdit, mode, onClose, onChanged }) {
  const [rows, setRows] = useState([]), [cursor, setCursor] = useState(null), [more, setMore] = useState(false), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [title, setTitle] = useState(''), [due, setDue] = useState('');
  const load = async (next = null) => { setLoading(true); try { const page = await base44.entities.CRMContactTask.filter({ contact_id: contact.id, status: 'open' }, { sort: 'due_at', limit: 20, ...(next ? { cursor: next } : {}) }); setRows(old => next ? [...old,...page.items] : page.items); setCursor(page.next_cursor); setMore(page.has_more); onChanged?.(); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [contact.id]);
  const save = async e => { e.preventDefault(); setBusy(true); setError(''); try { const { warning } = await createContactAction({ contact_id: contact.id, ...(account?.id ? { account_id: account.id } : {}), title: title.trim(), ...(due ? { due_at: new Date(due).toISOString() } : {}), owner_id: user.id, line_manager_id: user.line_manager_id || user.data?.line_manager_id || '', status: 'open' }, user, contact); setTitle(''); setDue(''); onClose?.(); await load(); if (warning) setError(warning); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const complete = async row => { setBusy(true); setError(''); try { await completeContactAction(row, user); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <section className="rounded-xl border border-border bg-card p-5"><h2 className="font-semibold">Next action</h2>{canEdit && ['task','followup'].includes(mode) && <form onSubmit={save} className="mt-3 space-y-2"><input required maxLength={200} aria-label="Action" placeholder={mode === 'followup' ? 'Follow-up with contact' : 'Action title'} value={title} onChange={e => setTitle(e.target.value)} className="w-full rounded-lg border border-input bg-background p-2 text-sm" /><label className="block text-sm">Due date &amp; time<input type="datetime-local" required={mode === 'followup'} value={due} onChange={e => setDue(e.target.value)} className="mt-1 w-full rounded-lg border border-input bg-background p-2" /></label><Button disabled={busy}>{busy ? 'Saving…' : 'Save action'}</Button> <Button type="button" variant="outline" onClick={onClose}>Cancel</Button></form>}{error && <p role="alert" className="mt-2 text-sm text-destructive">{error}</p>}{loading && !rows.length ? <p className="mt-3 text-sm text-muted-foreground">Loading actions…</p> : !rows.length ? <p className="mt-3 text-sm text-muted-foreground">No open actions.</p> : <ul className="mt-3 space-y-2">{rows.map(row => <li key={row.id} className="rounded-lg border border-border p-3 text-sm"><p className="font-medium">{row.title}</p><p className="text-xs text-muted-foreground">{row.due_at ? new Date(row.due_at).toLocaleString('en-GB') : 'No due date'}</p>{row.owner_id === user.id && <button type="button" disabled={busy} onClick={() => complete(row)} className="mt-1 text-xs text-primary hover:underline">Mark complete</button>}</li>)}</ul>}{more && <Button type="button" size="sm" variant="outline" disabled={loading} onClick={() => load(cursor)}>Load more</Button>}</section>;
}