import React, { useEffect, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import {useQueryClient} from '@tanstack/react-query';
import { isoToday, logCRMActivity } from '@/components/crm/crm';

export default function CRMTaskList({ item, user, canEdit }) {
  const cache=useQueryClient();
  const refresh=()=>{cache.invalidateQueries({queryKey:['commercial-next-action',item.id]});cache.invalidateQueries({queryKey:['commercial-workspace']});};
  const [tasks, setTasks] = useState([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [form, setForm] = useState({ title: '', due_date: '', priority: 'normal', description: '' });
  const load = async () => { setLoading(true); try { const page = await base44.entities.CRMTask.filter({ opportunity_id: item.id }, { sort: 'due_date', limit: 50 }); setTasks(page.items);refresh(); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [item.id]);
  const add = async e => { e.preventDefault(); setBusy(true); setError(''); try { const currentUser = await base44.auth.me(); await base44.entities.CRMTask.create({ ...form, opportunity_id: item.id, account_id: item.account_id, owner_id: currentUser.id, owner_name: (user?.id === currentUser.id && user.full_name) || currentUser.full_name || currentUser.email, line_manager_id: currentUser.data?.line_manager_id || currentUser.line_manager_id || '', status: 'open' }); setForm({ title: '', due_date: '', priority: 'normal', description: '' }); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const complete = async task => { setBusy(true); setError(''); try { await base44.entities.CRMTask.update(task.id, { status: 'completed', completed_at: new Date().toISOString() }); await logCRMActivity(item, user, 'task_completed', `Task completed: ${task.title}`); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <section className="space-y-3 rounded-xl border border-border bg-card p-5"><h2 className="font-semibold">Next actions &amp; tasks</h2>
    {loading ? <p className="text-sm text-muted-foreground">Loading tasks…</p> : !tasks.length ? <p className="text-sm text-muted-foreground">No tasks yet. Add the next action to keep this opportunity moving.</p> : <ul className="space-y-2">{tasks.map(task => <li key={task.id} className="flex flex-wrap items-center gap-2 rounded-lg border border-border p-2 text-sm"><span className={task.status === 'completed' ? 'min-w-0 break-words line-through text-muted-foreground' : 'min-w-0 break-words font-medium'}>{task.title}</span><span className={task.due_date && task.due_date < isoToday() && !['completed','cancelled'].includes(task.status) ? 'text-destructive' : 'text-muted-foreground'}>{task.due_date || 'No due date'}</span><span className="text-xs text-muted-foreground">{task.priority}</span><span className="ml-auto text-xs">{task.status}</span>{canEdit && task.status !== 'completed' && task.status !== 'cancelled' && <Button size="sm" variant="outline" disabled={busy} onClick={() => complete(task)}>Complete</Button>}</li>)}</ul>}
    {canEdit && item.status === 'open' && <form onSubmit={add} className="grid min-w-0 gap-2"><input required maxLength={200} aria-label="Task" placeholder="Next action" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className="min-w-0 rounded-lg border border-input p-2 text-sm" /><input type="date" aria-label="Due date" value={form.due_date} onChange={e => setForm({ ...form, due_date: e.target.value })} className="min-w-0 w-full rounded-lg border border-input p-2 text-sm" /><select aria-label="Priority" value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })} className="rounded-lg border border-input p-2 text-sm">{['low','normal','high','urgent'].map(v => <option key={v}>{v}</option>)}</select><Button disabled={busy}>{busy ? 'Saving…' : 'Add task'}</Button></form>}
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
  </section>;
}