import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { formatCurrency } from '@/lib/portal';
import OpportunityTeamFees from '@/components/crm/OpportunityTeamFees';

const STAGES = ['RIBA 1', 'RIBA 2', 'RIBA 3', 'RIBA 4', 'RIBA 5-7', 'Pre-construction', 'Construction', 'Other'];
const FIELDS = [['fee_services_included', 'Services included'], ['fee_services_excluded', 'Services excluded'], ['fee_consultants_required', 'Consultants required']];
export default function OpportunityFee({ item, onSave, canEdit, saving }) {
  const [draft, setDraft] = useState({ fee_basis: item.fee_basis || '', fee_status: item.fee_status || 'draft', fee_issued_date: item.fee_issued_date || '', fee_client_approval_date: item.fee_client_approval_date || '', fee_link_to_file: item.fee_link_to_file || '', fee_lines: item.fee_lines || [], ...Object.fromEntries(FIELDS.map(([key]) => [key, item[key] || ''])) });
  const editable = canEdit && item.status === 'open';
  const set = (key, value) => setDraft({ ...draft, [key]: value });
  const line = (index, patch) => set('fee_lines', draft.fee_lines.map((row, i) => i === index ? { ...row, ...patch } : row));
  const total = draft.fee_lines.reduce((sum, row) => sum + (Number(row.internal_fee) || 0), 0);
  return <section className="space-y-4 rounded-xl border border-border bg-card p-5">
    <div><h2 className="font-semibold">Fee proposal</h2><p className="text-sm text-muted-foreground">Build an indicative proposal that follows the opportunity into the project.</p></div>
    <OpportunityTeamFees team={item.design_team} />
    <div className="grid min-w-0 gap-3 sm:grid-cols-2"><label className="text-sm">Fee basis<select disabled={!editable} value={draft.fee_basis} onChange={e => set('fee_basis', e.target.value)} className="mt-1 w-full rounded-lg border border-input p-2"><option value="">Select basis</option><option value="fixed">Fixed</option><option value="percentage">% of works</option><option value="day_rate">Day rate</option></select></label><label className="text-sm">Proposal status<select disabled={!editable} value={draft.fee_status} onChange={e => set('fee_status', e.target.value)} className="mt-1 w-full rounded-lg border border-input p-2">{['draft','internal_review','sent','negotiation','accepted','lost'].map(v => <option key={v} value={v}>{v.replace('_', ' ')}</option>)}</select></label>
      <label className="text-sm">Date issued<input disabled={!editable} type="date" value={draft.fee_issued_date} onChange={e => set('fee_issued_date', e.target.value)} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm">Client approval date<input disabled={!editable} type="date" value={draft.fee_client_approval_date} onChange={e => set('fee_client_approval_date', e.target.value)} className="mt-1 w-full rounded-lg border border-input p-2" /></label></div>
    {FIELDS.map(([key, label]) => <label key={key} className="block text-sm">{label}<textarea disabled={!editable} rows={2} maxLength={5000} value={draft[key]} onChange={e => set(key, e.target.value)} className="mt-1 w-full rounded-lg border border-input p-2" /></label>)}
    <label className="block text-sm">Proposal document link<input disabled={!editable} type="url" value={draft.fee_link_to_file} onChange={e => set('fee_link_to_file', e.target.value)} className="mt-1 w-full rounded-lg border border-input p-2" /></label>
    <div className="space-y-2"><h3 className="text-sm font-semibold">ALS &amp; internal fee lines</h3>{draft.fee_lines.map((row, index) => <div key={index} className="flex flex-wrap items-end gap-2"><label className="min-w-0 basis-36 flex-1 text-xs">RIBA stage<select disabled={!editable} value={row.riba_stage || ''} onChange={e => line(index, { riba_stage: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2 text-sm"><option value="">Select stage</option>{STAGES.map(stage => <option key={stage}>{stage}</option>)}</select></label><label className="min-w-0 basis-44 flex-[2] text-xs">Description<input disabled={!editable} maxLength={200} value={row.description || ''} onChange={e => line(index, { description: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2 text-sm" /></label><label className="w-28 text-xs">Fee (£)<input disabled={!editable} type="number" min="0" step="0.01" value={row.internal_fee ?? ''} onChange={e => line(index, { internal_fee: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2 text-sm" /></label>{editable && <button type="button" onClick={() => set('fee_lines', draft.fee_lines.filter((_, i) => i !== index))} className="pb-2 text-xs text-destructive">Remove</button>}</div>)}</div>
    <p className="text-sm font-semibold">Proposed ALS fee: {formatCurrency(total)}</p>
    {editable && <div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={() => set('fee_lines', [...draft.fee_lines, { riba_stage: '', description: '', internal_fee: '' }])}>Add fee line</Button><Button type="button" disabled={saving || draft.fee_lines.some(row => !row.description)} onClick={() => onSave(draft)}>{saving ? 'Saving…' : 'Save fee proposal'}</Button></div>}
  </section>;
}