import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { formatCurrency } from '@/lib/portal';
import { STAGES, chance, stageLabel, weighted } from '@/components/crm/crm';
export default function OpportunityHeader({ item, account, contacts, canEdit, canConvert, busy, onSave, onStage, onOutcome, onConvert }) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState({ title: item.title, contact_id: item.contact_id || '', project_details: item.project_details || '', budget: item.budget ?? '', alliance_fee: item.alliance_fee ?? '', probability: chance(item), expected_decision_date: item.expected_decision_date || '', location: item.location || '', site_postcode: item.site_postcode || '' });
  const stage = item.stage || 'lead';
  return <div className="space-y-5 rounded-xl border border-border bg-card p-5 sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Link to={`/accounts/${account.id}`} className="text-sm text-primary hover:underline">{account.name}</Link><h1 className="font-heading text-2xl font-semibold sm:text-3xl">{item.title}</h1><p className="text-sm text-muted-foreground">Owner: {item.owner_name || 'Unassigned'} · {item.location || item.site_postcode || 'Location not set'}</p></div><div className="flex flex-wrap gap-2">{canEdit && item.status === 'open' && <><Button variant="outline" onClick={() => setEditing(v => !v)}>{editing ? 'Cancel editing' : 'Edit summary'}</Button><Button variant="outline" onClick={() => onOutcome('lost')}>Mark Lost</Button><Button onClick={() => onOutcome('won')}>Mark Won</Button></>}{item.status === 'won' && !item.project_id && canConvert && <Button onClick={onConvert}>Convert to Project</Button>}{item.project_id && <Button asChild variant="outline"><Link to={`/projects/${item.project_id}`}>View Project</Link></Button>}</div></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6">{[['Stage', stageLabel(stage)], ['Project value', formatCurrency(item.budget)], ['Alliance fee', formatCurrency(item.alliance_fee)], ['Probability', `${chance(item)}%`], ['Weighted value', formatCurrency(weighted(item))], ['Expected decision', item.expected_decision_date || '—']].map(([label,value]) => <div key={label} className="rounded-lg bg-muted p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div>
    <div className="flex gap-1 overflow-x-auto pb-1" aria-label="Opportunity stage journey">{STAGES.filter(s => !['on_hold','lost'].includes(s.value)).map(s => <span key={s.value} className={`shrink-0 rounded-full px-3 py-1 text-xs ${s.value === stage ? 'bg-primary text-primary-foreground font-semibold' : 'bg-muted text-muted-foreground'}`}>{s.label}</span>)}</div>
    {canEdit && item.status === 'open' && <label className="flex flex-wrap items-center gap-2 text-sm">Change stage <select aria-label="Change stage" value={stage} disabled={busy} onChange={e => onStage(e.target.value)} className="rounded-lg border border-input bg-background px-3 py-2">{STAGES.filter(s => !['won','lost'].includes(s.value)).map(s => <option key={s.value} value={s.value}>{s.label}</option>)}<option value="won">Won</option><option value="lost">Lost</option></select></label>}
    {editing && <form onSubmit={async e => { e.preventDefault(); if (await onSave({ title: draft.title.trim(), contact_id: draft.contact_id, project_details: draft.project_details, budget: draft.budget === '' ? 0 : Number(draft.budget), alliance_fee: draft.alliance_fee === '' ? 0 : Number(draft.alliance_fee), probability: Number(draft.probability), expected_decision_date: draft.expected_decision_date, location: draft.location, site_postcode: draft.site_postcode })) setEditing(false); }} className="grid gap-3 sm:grid-cols-3"><label className="text-sm">Opportunity name<input required maxLength={200} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm">Primary contact<select value={draft.contact_id} onChange={e => setDraft({ ...draft, contact_id: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2"><option value="">Select contact</option>{contacts.map(c => <option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label><label className="text-sm">Project value (£)<input type="number" min="0" value={draft.budget} onChange={e => setDraft({ ...draft, budget: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm">Alliance fee (£)<input type="number" min="0" value={draft.alliance_fee} onChange={e => setDraft({ ...draft, alliance_fee: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm">Probability (%)<input type="number" min="0" max="100" value={draft.probability} onChange={e => setDraft({ ...draft, probability: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm">Expected decision<input type="date" value={draft.expected_decision_date} onChange={e => setDraft({ ...draft, expected_decision_date: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm">Location<input value={draft.location} onChange={e => setDraft({ ...draft, location: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm">Postcode<input value={draft.site_postcode} onChange={e => setDraft({ ...draft, site_postcode: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm sm:col-span-3">Project description<textarea maxLength={5000} value={draft.project_details} onChange={e => setDraft({ ...draft, project_details: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><Button disabled={busy}>Save summary</Button></form>}
  </div>;
}