import React, { useState } from 'react';
import RecordUpdatedAt from '@/components/RecordUpdatedAt';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import SearchableSelect from '@/components/forms/SearchableSelect';
import { formatCurrency } from '@/lib/portal';
import { STAGES, chance, stageLabel, weighted } from '@/components/crm/crm';
import OpportunityRecordActions from '@/components/crm/OpportunityRecordActions';
import OpportunityNextAction from '@/components/commercial/OpportunityNextAction';
export default function OpportunityHeader({ item, account, contacts, canEdit, canConvert, busy, onSave, onStage, onOutcome, onConvert, onActivity, onAction }) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState({ title: item.title, contact_id: item.contact_id || '', project_details: item.project_details || '', budget: item.budget ?? '', probability: chance(item), expected_decision_date: item.expected_decision_date || '', location: item.location || '', site_postcode: item.site_postcode || '' });
  const stage = item.stage || 'lead';
  return <div id="opportunity-context" className="space-y-5 rounded-xl border border-border bg-card p-5 sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0 break-words"><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Commercial opportunity · {item.status}</p><Link to={`/accounts/${account.id}`} className="text-sm text-primary hover:underline">{account.name}</Link><h1 className="font-heading text-2xl font-semibold sm:text-3xl">{item.title}</h1><p className="text-sm text-muted-foreground">Owner: {item.owner_name || 'Unassigned'} · {item.location || item.site_postcode || 'Location not set'}</p></div><OpportunityRecordActions item={item} canEdit={canEdit} canConvert={canConvert} busy={busy} onUpdate={()=>setEditing(v=>!v)} onActivity={onActivity} onStage={onStage} onOutcome={onOutcome} onConvert={onConvert}/></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{[['Stage', stageLabel(stage)], ['Value', formatCurrency(item.budget)], ['Probability', `${chance(item)}%`], ['Expected close', item.expected_decision_date || 'Not set'], ['Opportunity owner', item.owner_name || 'Not assigned']].map(([label,value]) => <div key={label} className="min-w-0 rounded-lg bg-muted p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words text-sm font-semibold">{value}</p></div>)}</div>
    <RecordUpdatedAt record={item} />
    <OpportunityNextAction item={item} canEdit={canEdit} onAction={onAction}/>
    <details className="text-xs text-muted-foreground"><summary className="cursor-pointer font-medium">Review commercial context</summary><p className="mt-2">Recorded probability: {chance(item)}% · Weighted value: {formatCurrency(weighted(item))}</p></details>
    {item.stage_entered_at && Number.isFinite(Date.parse(item.stage_entered_at)) && <p className="text-xs text-muted-foreground">Age in recorded stage: {Math.max(0,Math.floor((Date.now()-Date.parse(item.stage_entered_at))/86400000))} days</p>}
    <div className="flex flex-wrap gap-2" aria-label="Opportunity stages">{STAGES.filter(s => !['on_hold', 'won', 'lost'].includes(s.value)).map(s => <button key={s.value} type="button" aria-label={`Set stage to ${s.label}`} aria-pressed={s.value === stage} disabled={!canEdit || busy || item.status !== 'open' || s.value === stage} onClick={() => onStage(s.value)} className={`rounded-full px-3 py-1.5 text-xs transition-colors ${s.value === stage ? 'bg-primary font-semibold text-primary-foreground' : 'bg-muted text-muted-foreground enabled:hover:bg-primary/20 enabled:hover:text-foreground'} disabled:cursor-default`}>{s.label}</button>)}</div>
    {editing && <form onSubmit={async e => { e.preventDefault(); if (await onSave({ title: draft.title.trim(), contact_id: draft.contact_id, project_details: draft.project_details, budget: draft.budget === '' ? 0 : Number(draft.budget), probability: Number(draft.probability), expected_decision_date: draft.expected_decision_date || null, location: draft.location, site_postcode: draft.site_postcode })) setEditing(false); }} className="grid gap-3 sm:grid-cols-3"><label className="text-sm">Opportunity name<input required maxLength={200} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm">Primary person<SearchableSelect value={draft.contact_id} onChange={e => setDraft({ ...draft, contact_id: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2"><option value="">Select person</option>{contacts.map(c => <option key={c.id} value={c.id}>{c.full_name}</option>)}</SearchableSelect></label><label className="text-sm">Project value (£)<input type="number" min="0" value={draft.budget} onChange={e => setDraft({ ...draft, budget: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm">Probability (%)<input type="number" min="0" max="100" value={draft.probability} onChange={e => setDraft({ ...draft, probability: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm">Expected decision<input type="date" value={draft.expected_decision_date} onChange={e => setDraft({ ...draft, expected_decision_date: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm">Location<input value={draft.location} onChange={e => setDraft({ ...draft, location: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm">Postcode<input value={draft.site_postcode} onChange={e => setDraft({ ...draft, site_postcode: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="text-sm sm:col-span-3">Project description<textarea maxLength={5000} value={draft.project_details} onChange={e => setDraft({ ...draft, project_details: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><Button disabled={busy}>Save opportunity</Button></form>}
  </div>;
}