import React from 'react';
import {useQuery} from '@tanstack/react-query';
import {base44} from '@/api/base44Client';
import AlsightAttention from '@/components/AlsightAttention';
import {formatDate} from '@/lib/portal';
const interactionTypes=['call','email','meeting','teams_meeting','client_visit','internal_meeting','lunch','site_visit'];
export default function OpportunityAttention({item,user,canEdit,onActivity,onReview}) {
 const query=useQuery({queryKey:['opportunity-attention',item.id,user.id,user.role],queryFn:async()=>{const [activity,conversation,changes]=await Promise.all([base44.entities.CRMActivity.filter({opportunity_id:item.id,type:{$in:interactionTypes}},{sort:'-occurred_at',limit:1,fields:['occurred_at']}),base44.entities.Conversation.filter({opportunity_id:item.id},{sort:'-occurred_at',limit:1,fields:['occurred_at']}),base44.entities.CRMActivity.filter({opportunity_id:item.id,type:{$in:['stage_change','decision','note','document_sent','proposal_sent','task_completed']}},{sort:'-occurred_at',limit:1,fields:['subject','occurred_at','type']})]);return {last:[activity.items[0]?.occurred_at,conversation.items[0]?.occurred_at].filter(Boolean).sort().at(-1),change:changes.items[0]};}});
 const today=new Date().toLocaleDateString('en-CA'),age=query.data?.last ? Math.floor((Date.now()-Date.parse(query.data.last))/86400000) : null;
 const decision=item.status==='open' && item.expected_decision_date && item.expected_decision_date.slice(0,10)<today;
 const stale=item.status==='open' && age>=21;
 const fee=item.status==='open' && ['sent','accepted'].includes(item.fee_status) && ['lead','qualified','scope_development','design_feasibility','proposal_preparation'].includes(item.stage);
 return <section className="space-y-3"><h2 className="text-sm font-semibold">What matters</h2>{query.isPending ? <p role="status" className="text-xs text-muted-foreground">Checking recorded activity…</p> : query.error ? <p role="alert" className="text-xs text-destructive">Activity could not be checked. <button className="underline" onClick={()=>query.refetch()}>Retry</button></p> : <p className="text-xs text-muted-foreground">Last accessible interaction: {query.data.last ? formatDate(query.data.last) : 'Not recorded'}.</p>}{decision && <AlsightAttention title="Expected decision date has passed" explanation={`The recorded date is ${formatDate(item.expected_decision_date)}; this does not establish a client decision. Review the opportunity information in ALSight.`} actions={[{label:'Review opportunity',onClick:onReview},{label:canEdit ? 'Add interaction' : 'Review activity',onClick:onActivity}]}/>} {stale && <AlsightAttention title={`No interaction recorded for ${age} days`} explanation="The latest accessible interaction is older than 21 days. This is a record follow-up prompt, not an instruction to contact the client." actions={[{label:canEdit ? 'Add interaction' : 'Review activity',onClick:onActivity}]}/>} {fee && <AlsightAttention title="Fee proposal recorded; opportunity is still at an earlier stage" explanation="The fee status and opportunity stage may need a record review. ALSight does not infer that the stage should change." actions={[{label:'Review opportunity',onClick:onReview}]}/>} {!decision && !stale && !fee && !query.isPending && !query.error && <p className="text-xs text-muted-foreground">No decision-date, recorded-activity or fee-stage prompts currently require attention.</p>}{query.data?.change && <div className="border-t border-border pt-3"><h2 className="text-sm font-semibold">What changed</h2><p className="mt-1 text-xs text-muted-foreground">{query.data.change.subject} · {formatDate(query.data.change.occurred_at)}</p><button type="button" onClick={onActivity} className="mt-1 text-xs font-medium underline">Review recorded activity</button></div>}</section>;
}