import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import SearchableSelect from '@/components/forms/SearchableSelect';
import { isoToday } from '@/components/crm/crm';
const REASONS = ['Price','Competitor Selected','Project Cancelled','Funding Unavailable','Client Decision','Programme','Scope Changed','Procurement Route','No Longer Viable','Duplicate','Other'];
export default function OpportunityOutcome({ type, onClose, onSubmit, busy }) {
  const [form, setForm] = useState({ date: isoToday(), reason: '', competitor: '', notes: '', project_value: '', alliance_fee: '', award_details: '', project_start: '' });
  return <Dialog open={!!type} onOpenChange={open => !open && onClose()}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{type === 'won' ? 'Mark opportunity won' : 'Mark opportunity lost'}</DialogTitle></DialogHeader>
    <form onSubmit={e => { e.preventDefault(); onSubmit(type === 'won' ? { stage: 'won', won_date: form.date, confirmed_project_value: form.project_value === '' ? undefined : Number(form.project_value), confirmed_alliance_fee: form.alliance_fee === '' ? undefined : Number(form.alliance_fee), award_details: form.award_details, expected_project_start: form.project_start } : { stage: 'lost', lost_date: form.date, lost_reason: form.reason, lost_competitor: form.competitor, lost_notes: form.notes }); }} className="space-y-3 text-sm">
      <label className="block">{type === 'won' ? 'Award date' : 'Lost date'}<input required type="date" value={form.date} onChange={e => setForm({ ...form, date: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label>
      {type === 'lost' ? <><label className="block">Primary loss reason<SearchableSelect required value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2"><option value="">Choose a reason</option>{REASONS.map(r => <option key={r}>{r}</option>)}</SearchableSelect></label><label className="block">Competitor (optional)<input value={form.competitor} onChange={e => setForm({ ...form, competitor: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="block">Notes<textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label></> : <><label className="block">Confirmed project value (£)<input type="number" min="0" value={form.project_value} onChange={e => setForm({ ...form, project_value: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="block">Confirmed Alliance fee (£)<input type="number" min="0" value={form.alliance_fee} onChange={e => setForm({ ...form, alliance_fee: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="block">Expected project start<input type="date" value={form.project_start} onChange={e => setForm({ ...form, project_start: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label><label className="block">Client confirmation details<textarea value={form.award_details} onChange={e => setForm({ ...form, award_details: e.target.value })} className="mt-1 w-full rounded-lg border border-input p-2" /></label></>}
      <div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button disabled={busy}>{busy ? 'Saving…' : type === 'won' ? 'Mark Won' : 'Mark Lost'}</Button></div>
    </form>
  </DialogContent></Dialog>;
}