import React, { useEffect, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
const INTERNAL = ['admin','director','regional_director','bsm','finance','bdm'];
export default function PipelineManagers({ onUpdated }) {
  const [people, setPeople] = useState([]), [chosen, setChosen] = useState({}), [busy, setBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const load = async () => { try { const users = (await base44.entities.User.list()).filter(u => INTERNAL.includes(u.role)); setPeople(users); setChosen(Object.fromEntries(users.map(u => [u.id, u.line_manager_id || u.data?.line_manager_id || '']))); } catch (e) { setError(e.message); } };
  useEffect(() => { load(); }, []);
  const assign = async person => { setBusy(person.id); setError(''); setNotice(''); try { await base44.functions.invoke('assignPipelineManager', { employeeId: person.id, managerId: chosen[person.id] || '' }); await load(); onUpdated?.(); setNotice(`Updated ${person.full_name || person.email}'s line manager.`); } catch (e) { setError(e.response?.data?.error || e.message); } finally { setBusy(''); } };
  return <details className="rounded-xl border border-border bg-card p-5"><summary className="cursor-pointer font-semibold">Staff reporting lines</summary><p className="mt-2 text-sm text-muted-foreground">Assign each colleague’s direct line manager to share their pipeline with that person.</p>{error && <p role="alert" className="mt-2 text-sm text-destructive">{error}</p>}{notice && <p role="status" className="mt-2 text-sm">{notice}</p>}<div className="mt-3 space-y-2">{people.map(person => <div key={person.id} className="flex flex-wrap items-center gap-2 border-t border-border pt-2 text-sm"><span className="min-w-40 flex-1">{person.full_name || person.email}</span><select aria-label={`Line manager for ${person.full_name || person.email}`} value={chosen[person.id] || ''} onChange={e => setChosen(old => ({ ...old, [person.id]: e.target.value }))} className="rounded-lg border border-input bg-background p-2"><option value="">No line manager</option>{people.filter(u => u.id !== person.id).map(u => <option key={u.id} value={u.id}>{u.full_name || u.email}</option>)}</select><Button size="sm" variant="outline" disabled={busy !== '' || (chosen[person.id] || '') === (person.line_manager_id || person.data?.line_manager_id || '')} onClick={() => assign(person)}>{busy === person.id ? 'Saving…' : 'Save'}</Button></div>)}</div></details>;
}